var annotated_dup =
[
    [ "gaia", "namespacegaia.html", [
      [ "cnt", null, [
        [ "detail", null, [
          [ "mem_page", "classgaia_1_1cnt_1_1detail_1_1mem__page.html", null ],
          [ "mem_page_data", "structgaia_1_1cnt_1_1detail_1_1mem__page__data.html", "structgaia_1_1cnt_1_1detail_1_1mem__page__data" ],
          [ "mem_page_iterator", "structgaia_1_1cnt_1_1detail_1_1mem__page__iterator.html", null ],
          [ "mem_page_iterator_soa", "structgaia_1_1cnt_1_1detail_1_1mem__page__iterator__soa.html", null ],
          [ "sparse_page", "classgaia_1_1cnt_1_1detail_1_1sparse__page.html", null ],
          [ "sparse_page< T, PageCapacity, Allocator, std::enable_if_t< std::is_empty_v< T > > >", "classgaia_1_1cnt_1_1detail_1_1sparse__page_3_01T_00_01PageCapacity_00_01Allocator_00_01std_1_1en6e95dfa070ac2a122b9692da81356b71.html", null ]
        ] ],
        [ "bitset", "classgaia_1_1cnt_1_1bitset.html", "classgaia_1_1cnt_1_1bitset" ],
        [ "bitset_const_iterator", "classgaia_1_1cnt_1_1bitset__const__iterator.html", null ],
        [ "const_darr_ext_soa_iterator", "structgaia_1_1cnt_1_1const__darr__ext__soa__iterator.html", null ],
        [ "const_darr_soa_iterator", "structgaia_1_1cnt_1_1const__darr__soa__iterator.html", null ],
        [ "const_page_iterator", "structgaia_1_1cnt_1_1const__page__iterator.html", null ],
        [ "const_page_iterator_soa", "structgaia_1_1cnt_1_1const__page__iterator__soa.html", null ],
        [ "const_sarr_ext_soa_iterator", "structgaia_1_1cnt_1_1const__sarr__ext__soa__iterator.html", null ],
        [ "const_sarr_soa_iterator", "structgaia_1_1cnt_1_1const__sarr__soa__iterator.html", null ],
        [ "const_sparse_iterator", "structgaia_1_1cnt_1_1const__sparse__iterator.html", null ],
        [ "const_sparse_iterator< T, PageCapacity, Allocator, std::enable_if_t< std::is_empty_v< T > > >", "structgaia_1_1cnt_1_1const__sparse__iterator_3_01T_00_01PageCapacity_00_01Allocator_00_01std_1_1ac6071468172e14d5e0cd6a6d6bb0e21.html", null ],
        [ "darr", "classgaia_1_1cnt_1_1darr.html", "classgaia_1_1cnt_1_1darr" ],
        [ "darr_ext", "classgaia_1_1cnt_1_1darr__ext.html", "classgaia_1_1cnt_1_1darr__ext" ],
        [ "darr_ext_soa", "classgaia_1_1cnt_1_1darr__ext__soa.html", "classgaia_1_1cnt_1_1darr__ext__soa" ],
        [ "darr_ext_soa_iterator", "structgaia_1_1cnt_1_1darr__ext__soa__iterator.html", null ],
        [ "darr_soa", "classgaia_1_1cnt_1_1darr__soa.html", "classgaia_1_1cnt_1_1darr__soa" ],
        [ "darr_soa_iterator", "structgaia_1_1cnt_1_1darr__soa__iterator.html", null ],
        [ "darray_ilist_storage", "structgaia_1_1cnt_1_1darray__ilist__storage.html", null ],
        [ "dbitset", "classgaia_1_1cnt_1_1dbitset.html", "classgaia_1_1cnt_1_1dbitset" ],
        [ "fwd_llist", "structgaia_1_1cnt_1_1fwd__llist.html", "structgaia_1_1cnt_1_1fwd__llist" ],
        [ "fwd_llist_base", "structgaia_1_1cnt_1_1fwd__llist__base.html", null ],
        [ "fwd_llist_iterator", "structgaia_1_1cnt_1_1fwd__llist__iterator.html", null ],
        [ "fwd_llist_link", "structgaia_1_1cnt_1_1fwd__llist__link.html", "structgaia_1_1cnt_1_1fwd__llist__link" ],
        [ "ilist", "structgaia_1_1cnt_1_1ilist.html", "structgaia_1_1cnt_1_1ilist" ],
        [ "ilist_item", "structgaia_1_1cnt_1_1ilist__item.html", "structgaia_1_1cnt_1_1ilist__item" ],
        [ "ilist_item_base", "structgaia_1_1cnt_1_1ilist__item__base.html", null ],
        [ "page_iterator", "structgaia_1_1cnt_1_1page__iterator.html", null ],
        [ "page_iterator_soa", "structgaia_1_1cnt_1_1page__iterator__soa.html", null ],
        [ "page_storage", "classgaia_1_1cnt_1_1page__storage.html", "classgaia_1_1cnt_1_1page__storage" ],
        [ "sarr", "classgaia_1_1cnt_1_1sarr.html", "classgaia_1_1cnt_1_1sarr" ],
        [ "sarr_ext", "classgaia_1_1cnt_1_1sarr__ext.html", "classgaia_1_1cnt_1_1sarr__ext" ],
        [ "sarr_ext_soa", "classgaia_1_1cnt_1_1sarr__ext__soa.html", "classgaia_1_1cnt_1_1sarr__ext__soa" ],
        [ "sarr_ext_soa_iterator", "structgaia_1_1cnt_1_1sarr__ext__soa__iterator.html", null ],
        [ "sarr_soa", "classgaia_1_1cnt_1_1sarr__soa.html", "classgaia_1_1cnt_1_1sarr__soa" ],
        [ "sarr_soa_iterator", "structgaia_1_1cnt_1_1sarr__soa__iterator.html", null ],
        [ "sparse_iterator", "structgaia_1_1cnt_1_1sparse__iterator.html", null ],
        [ "sparse_iterator< T, PageCapacity, Allocator, std::enable_if_t< std::is_empty_v< T > > >", "structgaia_1_1cnt_1_1sparse__iterator_3_01T_00_01PageCapacity_00_01Allocator_00_01std_1_1enable_a04ec75195309ee4c5d26ce99aa078a9.html", null ],
        [ "sparse_storage", "classgaia_1_1cnt_1_1sparse__storage.html", "classgaia_1_1cnt_1_1sparse__storage" ],
        [ "sparse_storage< T, PageCapacity, Allocator, std::enable_if_t< std::is_empty_v< T > > >", "classgaia_1_1cnt_1_1sparse__storage_3_01T_00_01PageCapacity_00_01Allocator_00_01std_1_1enable__ie087b7e8314b32ca924843d3e0f50e85.html", "classgaia_1_1cnt_1_1sparse__storage_3_01T_00_01PageCapacity_00_01Allocator_00_01std_1_1enable__ie087b7e8314b32ca924843d3e0f50e85" ],
        [ "sringbuffer", "classgaia_1_1cnt_1_1sringbuffer.html", null ],
        [ "sringbuffer_iterator", "structgaia_1_1cnt_1_1sringbuffer__iterator.html", null ],
        [ "to_page_storage_id", "structgaia_1_1cnt_1_1to__page__storage__id.html", null ],
        [ "to_page_storage_id< ecs::EntityContainer >", "structgaia_1_1cnt_1_1to__page__storage__id_3_01ecs_1_1EntityContainer_01_4.html", null ],
        [ "to_sparse_id", "structgaia_1_1cnt_1_1to__sparse__id.html", null ],
        [ "to_sparse_id< ecs::Entity >", "structgaia_1_1cnt_1_1to__sparse__id_3_01ecs_1_1Entity_01_4.html", null ]
      ] ],
      [ "core", null, [
        [ "detail", null, [
          [ "is_complete", "structgaia_1_1core_1_1detail_1_1is__complete.html", null ],
          [ "is_complete< T, decltype(sizeof(T))>", "structgaia_1_1core_1_1detail_1_1is__complete_3_01T_00_01decltype_07sizeof_07T_08_08_4.html", null ],
          [ "is_container", "structgaia_1_1core_1_1detail_1_1is__container.html", null ],
          [ "is_container_element_kind_compatible", "structgaia_1_1core_1_1detail_1_1is__container__element__kind__compatible.html", null ],
          [ "is_container_element_kind_compatible< T, E, typename std::enable_if< !std::is_same< typename std::remove_cv< decltype(detail::data(std::declval< T >()))>::type, void >::value &&std::is_convertible< typename std::remove_pointer_t< decltype(detail::data(std::declval< T >()))>(*)[], E(*)[]>::value >::type >", "structgaia_1_1core_1_1detail_1_1is__container__element__kind__compatible_3_01T_00_01E_00_01typen25493d4f5b646d1ff43bb65fcbf4e827.html", null ],
          [ "is_direct_hash_key", "structgaia_1_1core_1_1detail_1_1is__direct__hash__key.html", null ],
          [ "is_direct_hash_key< T, std::void_t< decltype(T::IsDirectHashKey)> >", "structgaia_1_1core_1_1detail_1_1is__direct__hash__key_3_01T_00_01std_1_1void__t_3_01decltype_07T_1_1IsDirectHashKey_08_4_01_4.html", null ],
          [ "is_mut", "structgaia_1_1core_1_1detail_1_1is__mut.html", null ],
          [ "is_span", "structgaia_1_1core_1_1detail_1_1is__span.html", null ],
          [ "is_span< span< T, S > >", "structgaia_1_1core_1_1detail_1_1is__span_3_01span_3_01T_00_01S_01_4_01_4.html", null ],
          [ "is_std_array", "structgaia_1_1core_1_1detail_1_1is__std__array.html", null ],
          [ "is_std_array< gaia::cnt::sarray< T, N > >", "structgaia_1_1core_1_1detail_1_1is__std__array_3_01gaia_1_1cnt_1_1sarray_3_01T_00_01N_01_4_01_4.html", null ],
          [ "iterator_traits", "structgaia_1_1core_1_1detail_1_1iterator__traits.html", null ],
          [ "iterator_traits< T * >", "structgaia_1_1core_1_1detail_1_1iterator__traits_3_01T_01_5_01_4.html", null ],
          [ "iterator_traits_base", "structgaia_1_1core_1_1detail_1_1iterator__traits__base.html", null ],
          [ "iterator_traits_base< It, std::void_t< typename It::iterator_category, typename It::value_type, typename It::difference_type, typename It::pointer, typename It::reference > >", "structgaia_1_1core_1_1detail_1_1iterator__traits__base_3_01It_00_01std_1_1void__t_3_01typename_0a642e18983b55d789445bd71d4933245.html", null ],
          [ "iterator_traits_pointer_base", "structgaia_1_1core_1_1detail_1_1iterator__traits__pointer__base.html", null ],
          [ "iterator_traits_pointer_base< T, false >", "structgaia_1_1core_1_1detail_1_1iterator__traits__pointer__base_3_01T_00_01false_01_4.html", null ],
          [ "member_func_checker", "structgaia_1_1core_1_1detail_1_1member__func__checker.html", null ],
          [ "member_func_checker< Default, std::void_t< Op< Args... > >, Op, Args... >", "structgaia_1_1core_1_1detail_1_1member__func__checker_3_01Default_00_01std_1_1void__t_3_01Op_3_0222e17dad8904d328c48bb2ccd61015b.html", null ],
          [ "member_func_none", "structgaia_1_1core_1_1detail_1_1member__func__none.html", null ],
          [ "rem_rp", "structgaia_1_1core_1_1detail_1_1rem__rp.html", null ],
          [ "span_storage", "structgaia_1_1core_1_1detail_1_1span__storage.html", null ],
          [ "span_storage< T, DynamicSpanExtent >", "structgaia_1_1core_1_1detail_1_1span__storage_3_01T_00_01DynamicSpanExtent_01_4.html", null ],
          [ "type_identity", "structgaia_1_1core_1_1detail_1_1type__identity.html", null ]
        ] ],
        [ "bidirectional_iterator_tag", "structgaia_1_1core_1_1bidirectional__iterator__tag.html", null ],
        [ "bit_view", "structgaia_1_1core_1_1bit__view.html", null ],
        [ "contiguous_iterator_tag", "structgaia_1_1core_1_1contiguous__iterator__tag.html", null ],
        [ "direct_hash_key", "structgaia_1_1core_1_1direct__hash__key.html", null ],
        [ "dyn_singleton", "classgaia_1_1core_1_1dyn__singleton.html", null ],
        [ "equal_to", "structgaia_1_1core_1_1equal__to.html", null ],
        [ "forward_iterator_tag", "structgaia_1_1core_1_1forward__iterator__tag.html", null ],
        [ "func_type_list", "structgaia_1_1core_1_1func__type__list.html", null ],
        [ "has_data_size", "structgaia_1_1core_1_1has__data__size.html", null ],
        [ "has_data_size< T, std::void_t< decltype(detail::data(std::declval< T >())), decltype(detail::size(std::declval< T >())) > >", "structgaia_1_1core_1_1has__data__size_3_01T_00_01std_1_1void__t_3_01decltype_07detail_1_1data_0731442a81cf4e1da91ee338fd93279e3c.html", null ],
        [ "has_ffunc_equals", "structgaia_1_1core_1_1has__ffunc__equals.html", null ],
        [ "has_func_equals", "structgaia_1_1core_1_1has__func__equals.html", null ],
        [ "has_size_begin_end", "structgaia_1_1core_1_1has__size__begin__end.html", null ],
        [ "has_size_begin_end< T, std::void_t< decltype(std::declval< T >().begin()), decltype(std::declval< T >().end()), decltype(detail::size(std::declval< T >())) > >", "structgaia_1_1core_1_1has__size__begin__end_3_01T_00_01std_1_1void__t_3_01decltype_07std_1_1decled3338d74af8cc0bacdf33bd2a865cfb.html", null ],
        [ "input_iterator_tag", "structgaia_1_1core_1_1input__iterator__tag.html", null ],
        [ "is_greater", "structgaia_1_1core_1_1is__greater.html", null ],
        [ "is_iterator", "structgaia_1_1core_1_1is__iterator.html", null ],
        [ "is_smaller", "structgaia_1_1core_1_1is__smaller.html", null ],
        [ "is_smaller_or_equal", "structgaia_1_1core_1_1is__smaller__or__equal.html", null ],
        [ "lock_scope", "structgaia_1_1core_1_1lock__scope.html", null ],
        [ "output_iterator_tag", "structgaia_1_1core_1_1output__iterator__tag.html", null ],
        [ "random_access_iterator_tag", "structgaia_1_1core_1_1random__access__iterator__tag.html", null ],
        [ "reverse_iterator_tag", "structgaia_1_1core_1_1reverse__iterator__tag.html", null ],
        [ "span", "classgaia_1_1core_1_1span.html", null ],
        [ "StringLookupKey", "structgaia_1_1core_1_1StringLookupKey.html", "structgaia_1_1core_1_1StringLookupKey" ],
        [ "type_list", "structgaia_1_1core_1_1type__list.html", null ],
        [ "type_list_concat", "structgaia_1_1core_1_1type__list__concat.html", null ],
        [ "type_list_concat< type_list< TypesA... >, type_list< TypesB... > >", "structgaia_1_1core_1_1type__list__concat_3_01type__list_3_01TypesA_8_8_8_01_4_00_01type__list_3_01TypesB_8_8_8_01_4_01_4.html", null ],
        [ "unique", "structgaia_1_1core_1_1unique.html", null ],
        [ "unique< std::tuple< Ts... >, U, Us... >", "structgaia_1_1core_1_1unique_3_01std_1_1tuple_3_01Ts_8_8_8_01_4_00_01U_00_01Us_8_8_8_01_4.html", null ],
        [ "zero_t", "structgaia_1_1core_1_1zero__t.html", null ]
      ] ],
      [ "detail", null, [
        [ "is_reference_wrapper", "structgaia_1_1detail_1_1is__reference__wrapper.html", null ],
        [ "is_reference_wrapper< std::reference_wrapper< U > >", "structgaia_1_1detail_1_1is__reference__wrapper_3_01std_1_1reference__wrapper_3_01U_01_4_01_4.html", null ]
      ] ],
      [ "ecs", null, [
        [ "detail", null, [
          [ "actual_type", "structgaia_1_1ecs_1_1detail_1_1actual__type.html", null ],
          [ "actual_type< T, std::enable_if_t< is_pair< T >::value > >", "structgaia_1_1ecs_1_1detail_1_1actual__type_3_01T_00_01std_1_1enable__if__t_3_01is__pair_3_01T_01_4_1_1value_01_4_01_4.html", null ],
          [ "ChunkIterImpl", "classgaia_1_1ecs_1_1detail_1_1ChunkIterImpl.html", "classgaia_1_1ecs_1_1detail_1_1ChunkIterImpl" ],
          [ "CommandBuffer", "classgaia_1_1ecs_1_1detail_1_1CommandBuffer.html", "classgaia_1_1ecs_1_1detail_1_1CommandBuffer" ],
          [ "component_type", "structgaia_1_1ecs_1_1detail_1_1component__type.html", null ],
          [ "component_type< T, std::void_t< decltype(T::Kind)> >", "structgaia_1_1ecs_1_1detail_1_1component__type_3_01T_00_01std_1_1void__t_3_01decltype_07T_1_1Kind_08_4_01_4.html", null ],
          [ "ComponentDesc", "structgaia_1_1ecs_1_1detail_1_1ComponentDesc.html", null ],
          [ "ExtractComponentType_NoEntityKind", "structgaia_1_1ecs_1_1detail_1_1ExtractComponentType__NoEntityKind.html", "structgaia_1_1ecs_1_1detail_1_1ExtractComponentType__NoEntityKind" ],
          [ "ExtractComponentType_WithEntityKind", "structgaia_1_1ecs_1_1detail_1_1ExtractComponentType__WithEntityKind.html", "structgaia_1_1ecs_1_1detail_1_1ExtractComponentType__WithEntityKind" ],
          [ "has_entity_kind", "structgaia_1_1ecs_1_1detail_1_1has__entity__kind.html", null ],
          [ "has_entity_kind< T, std::void_t< decltype(T::Kind)> >", "structgaia_1_1ecs_1_1detail_1_1has__entity__kind_3_01T_00_01std_1_1void__t_3_01decltype_07T_1_1Kind_08_4_01_4.html", null ],
          [ "is_gen_component", "structgaia_1_1ecs_1_1detail_1_1is__gen__component.html", null ],
          [ "is_gen_component< T, std::void_t< decltype(T::Kind)> >", "structgaia_1_1ecs_1_1detail_1_1is__gen__component_3_01T_00_01std_1_1void__t_3_01decltype_07T_1_1Kind_08_4_01_4.html", null ],
          [ "pair_base", "structgaia_1_1ecs_1_1detail_1_1pair__base.html", null ],
          [ "QueryCmd_AddFilter", "structgaia_1_1ecs_1_1detail_1_1QueryCmd__AddFilter.html", null ],
          [ "QueryCmd_AddItem", "structgaia_1_1ecs_1_1detail_1_1QueryCmd__AddItem.html", null ],
          [ "QueryCmd_GroupBy", "structgaia_1_1ecs_1_1detail_1_1QueryCmd__GroupBy.html", null ],
          [ "QueryCmd_SetGroupId", "structgaia_1_1ecs_1_1detail_1_1QueryCmd__SetGroupId.html", null ],
          [ "QueryCmd_SortBy", "structgaia_1_1ecs_1_1detail_1_1QueryCmd__SortBy.html", null ],
          [ "QueryImpl", "classgaia_1_1ecs_1_1detail_1_1QueryImpl.html", "classgaia_1_1ecs_1_1detail_1_1QueryImpl" ],
          [ "QueryImplStorage", "structgaia_1_1ecs_1_1detail_1_1QueryImplStorage.html", "structgaia_1_1ecs_1_1detail_1_1QueryImplStorage" ],
          [ "QueryImplStorage< false >", "structgaia_1_1ecs_1_1detail_1_1QueryImplStorage_3_01false_01_4.html", "structgaia_1_1ecs_1_1detail_1_1QueryImplStorage_3_01false_01_4" ],
          [ "storage_type", "structgaia_1_1ecs_1_1detail_1_1storage__type.html", null ],
          [ "storage_type< T, std::void_t< decltype(T::gaia_Storage_Type)> >", "structgaia_1_1ecs_1_1detail_1_1storage__type_3_01T_00_01std_1_1void__t_3_01decltype_07T_1_1gaia__Storage__Type_08_4_01_4.html", null ]
        ] ],
        [ "vm", null, [
          [ "detail", null, [
            [ "CompiledOp", "structgaia_1_1ecs_1_1vm_1_1detail_1_1CompiledOp.html", "structgaia_1_1ecs_1_1vm_1_1detail_1_1CompiledOp" ],
            [ "IdCmpResult", "structgaia_1_1ecs_1_1vm_1_1detail_1_1IdCmpResult.html", null ],
            [ "OpAll", "structgaia_1_1ecs_1_1vm_1_1detail_1_1OpAll.html", null ],
            [ "OpAny", "structgaia_1_1ecs_1_1vm_1_1detail_1_1OpAny.html", null ],
            [ "OpcodeAll_Complex", "structgaia_1_1ecs_1_1vm_1_1detail_1_1OpcodeAll__Complex.html", null ],
            [ "OpcodeAll_Simple", "structgaia_1_1ecs_1_1vm_1_1detail_1_1OpcodeAll__Simple.html", null ],
            [ "OpcodeAll_Wildcard", "structgaia_1_1ecs_1_1vm_1_1detail_1_1OpcodeAll__Wildcard.html", null ],
            [ "OpcodeAny_NoAll", "structgaia_1_1ecs_1_1vm_1_1detail_1_1OpcodeAny__NoAll.html", null ],
            [ "OpcodeAny_WithAll", "structgaia_1_1ecs_1_1vm_1_1detail_1_1OpcodeAny__WithAll.html", null ],
            [ "OpcodeNot_Complex", "structgaia_1_1ecs_1_1vm_1_1detail_1_1OpcodeNot__Complex.html", null ],
            [ "OpcodeNot_Simple", "structgaia_1_1ecs_1_1vm_1_1detail_1_1OpcodeNot__Simple.html", null ],
            [ "OpcodeNot_Wildcard", "structgaia_1_1ecs_1_1vm_1_1detail_1_1OpcodeNot__Wildcard.html", null ],
            [ "OpNo", "structgaia_1_1ecs_1_1vm_1_1detail_1_1OpNo.html", null ],
            [ "QueryCompileCtx", "structgaia_1_1ecs_1_1vm_1_1detail_1_1QueryCompileCtx.html", "structgaia_1_1ecs_1_1vm_1_1detail_1_1QueryCompileCtx" ]
          ] ],
          [ "MatchingCtx", "structgaia_1_1ecs_1_1vm_1_1MatchingCtx.html", "structgaia_1_1ecs_1_1vm_1_1MatchingCtx" ],
          [ "VirtualMachine", "classgaia_1_1ecs_1_1vm_1_1VirtualMachine.html", "classgaia_1_1ecs_1_1vm_1_1VirtualMachine" ]
        ] ],
        [ "_Var0", "structgaia_1_1ecs_1_1__Var0.html", null ],
        [ "_Var1", "structgaia_1_1ecs_1_1__Var1.html", null ],
        [ "_Var2", "structgaia_1_1ecs_1_1__Var2.html", null ],
        [ "_Var3", "structgaia_1_1ecs_1_1__Var3.html", null ],
        [ "_Var4", "structgaia_1_1ecs_1_1__Var4.html", null ],
        [ "_Var5", "structgaia_1_1ecs_1_1__Var5.html", null ],
        [ "_Var6", "structgaia_1_1ecs_1_1__Var6.html", null ],
        [ "_Var7", "structgaia_1_1ecs_1_1__Var7.html", null ],
        [ "AccessContextMT", "structgaia_1_1ecs_1_1AccessContextMT.html", null ],
        [ "AccessContextST", "structgaia_1_1ecs_1_1AccessContextST.html", null ],
        [ "Acyclic_", "structgaia_1_1ecs_1_1Acyclic__.html", null ],
        [ "All_", "structgaia_1_1ecs_1_1All__.html", null ],
        [ "Archetype", "classgaia_1_1ecs_1_1Archetype.html", "classgaia_1_1ecs_1_1Archetype" ],
        [ "ArchetypeBase", "classgaia_1_1ecs_1_1ArchetypeBase.html", "classgaia_1_1ecs_1_1ArchetypeBase" ],
        [ "ArchetypeCacheData", "structgaia_1_1ecs_1_1ArchetypeCacheData.html", null ],
        [ "ArchetypeChunkPair", "structgaia_1_1ecs_1_1ArchetypeChunkPair.html", null ],
        [ "ArchetypeGraph", "classgaia_1_1ecs_1_1ArchetypeGraph.html", "classgaia_1_1ecs_1_1ArchetypeGraph" ],
        [ "ArchetypeIdHashPair", "structgaia_1_1ecs_1_1ArchetypeIdHashPair.html", null ],
        [ "ArchetypeIdLookupKey", "classgaia_1_1ecs_1_1ArchetypeIdLookupKey.html", null ],
        [ "ArchetypeLookupChecker", "classgaia_1_1ecs_1_1ArchetypeLookupChecker.html", null ],
        [ "ArchetypeLookupKey", "classgaia_1_1ecs_1_1ArchetypeLookupKey.html", null ],
        [ "BinarySerializer", "classgaia_1_1ecs_1_1BinarySerializer.html", null ],
        [ "CantCombine_", "structgaia_1_1ecs_1_1CantCombine__.html", null ],
        [ "ChildOf_", "structgaia_1_1ecs_1_1ChildOf__.html", null ],
        [ "Chunk", "classgaia_1_1ecs_1_1Chunk.html", "classgaia_1_1ecs_1_1Chunk" ],
        [ "ChunkDataOffsets", "structgaia_1_1ecs_1_1ChunkDataOffsets.html", "structgaia_1_1ecs_1_1ChunkDataOffsets" ],
        [ "ChunkHeader", "structgaia_1_1ecs_1_1ChunkHeader.html", "structgaia_1_1ecs_1_1ChunkHeader" ],
        [ "ChunkRecords", "structgaia_1_1ecs_1_1ChunkRecords.html", "structgaia_1_1ecs_1_1ChunkRecords" ],
        [ "Component", "structgaia_1_1ecs_1_1Component.html", "structgaia_1_1ecs_1_1Component" ],
        [ "ComponentCache", "classgaia_1_1ecs_1_1ComponentCache.html", "classgaia_1_1ecs_1_1ComponentCache" ],
        [ "ComponentCacheItem", "structgaia_1_1ecs_1_1ComponentCacheItem.html", "structgaia_1_1ecs_1_1ComponentCacheItem" ],
        [ "ComponentGetter", "structgaia_1_1ecs_1_1ComponentGetter.html", "structgaia_1_1ecs_1_1ComponentGetter" ],
        [ "ComponentRecord", "structgaia_1_1ecs_1_1ComponentRecord.html", "structgaia_1_1ecs_1_1ComponentRecord" ],
        [ "ComponentSetter", "structgaia_1_1ecs_1_1ComponentSetter.html", "structgaia_1_1ecs_1_1ComponentSetter" ],
        [ "CopyIter", "classgaia_1_1ecs_1_1CopyIter.html", "classgaia_1_1ecs_1_1CopyIter" ],
        [ "Core_", "structgaia_1_1ecs_1_1Core__.html", null ],
        [ "Delete_", "structgaia_1_1ecs_1_1Delete__.html", null ],
        [ "DependsOn_", "structgaia_1_1ecs_1_1DependsOn__.html", null ],
        [ "Entity", "structgaia_1_1ecs_1_1Entity.html", "structgaia_1_1ecs_1_1Entity" ],
        [ "EntityContainer", "structgaia_1_1ecs_1_1EntityContainer.html", "structgaia_1_1ecs_1_1EntityContainer" ],
        [ "EntityContainerCtx", "structgaia_1_1ecs_1_1EntityContainerCtx.html", null ],
        [ "EntityContainers", "structgaia_1_1ecs_1_1EntityContainers.html", "structgaia_1_1ecs_1_1EntityContainers" ],
        [ "EntityDesc", "structgaia_1_1ecs_1_1EntityDesc.html", null ],
        [ "EntityLookupKey", "structgaia_1_1ecs_1_1EntityLookupKey.html", null ],
        [ "Error_", "structgaia_1_1ecs_1_1Error__.html", null ],
        [ "Exclusive_", "structgaia_1_1ecs_1_1Exclusive__.html", null ],
        [ "Is_", "structgaia_1_1ecs_1_1Is__.html", null ],
        [ "is_pair", "structgaia_1_1ecs_1_1is__pair.html", null ],
        [ "Iter", "classgaia_1_1ecs_1_1Iter.html", null ],
        [ "IterAll", "classgaia_1_1ecs_1_1IterAll.html", "classgaia_1_1ecs_1_1IterAll" ],
        [ "IterDisabled", "classgaia_1_1ecs_1_1IterDisabled.html", null ],
        [ "Observer_", "structgaia_1_1ecs_1_1Observer__.html", null ],
        [ "OnDelete_", "structgaia_1_1ecs_1_1OnDelete__.html", null ],
        [ "OnDeleteTarget_", "structgaia_1_1ecs_1_1OnDeleteTarget__.html", null ],
        [ "pair", "classgaia_1_1ecs_1_1pair.html", null ],
        [ "pair< Entity, Entity >", "classgaia_1_1ecs_1_1pair_3_01Entity_00_01Entity_01_4.html", null ],
        [ "query_sort_cond", "structgaia_1_1ecs_1_1query__sort__cond.html", null ],
        [ "QueryCache", "classgaia_1_1ecs_1_1QueryCache.html", "classgaia_1_1ecs_1_1QueryCache" ],
        [ "QueryCtx", "structgaia_1_1ecs_1_1QueryCtx.html", "structgaia_1_1ecs_1_1QueryCtx" ],
        [ "QueryHandle", "structgaia_1_1ecs_1_1QueryHandle.html", null ],
        [ "QueryHandleLookupKey", "structgaia_1_1ecs_1_1QueryHandleLookupKey.html", null ],
        [ "QueryIdentity", "structgaia_1_1ecs_1_1QueryIdentity.html", "structgaia_1_1ecs_1_1QueryIdentity" ],
        [ "QueryInfo", "classgaia_1_1ecs_1_1QueryInfo.html", "classgaia_1_1ecs_1_1QueryInfo" ],
        [ "QueryInfoCreationCtx", "structgaia_1_1ecs_1_1QueryInfoCreationCtx.html", null ],
        [ "QueryInput", "structgaia_1_1ecs_1_1QueryInput.html", "structgaia_1_1ecs_1_1QueryInput" ],
        [ "QueryLookupKey", "classgaia_1_1ecs_1_1QueryLookupKey.html", null ],
        [ "QueryTerm", "structgaia_1_1ecs_1_1QueryTerm.html", "structgaia_1_1ecs_1_1QueryTerm" ],
        [ "Remove_", "structgaia_1_1ecs_1_1Remove__.html", null ],
        [ "Requires_", "structgaia_1_1ecs_1_1Requires__.html", null ],
        [ "Traversable_", "structgaia_1_1ecs_1_1Traversable__.html", null ],
        [ "uni", "structgaia_1_1ecs_1_1uni.html", "structgaia_1_1ecs_1_1uni" ],
        [ "World", "classgaia_1_1ecs_1_1World.html", "classgaia_1_1ecs_1_1World" ]
      ] ],
      [ "mem", null, [
        [ "detail", null, [
          [ "AllocationInfo", "structgaia_1_1mem_1_1detail_1_1AllocationInfo.html", "structgaia_1_1mem_1_1detail_1_1AllocationInfo" ],
          [ "auto_view_policy_inter", "structgaia_1_1mem_1_1detail_1_1auto__view__policy__inter.html", null ],
          [ "auto_view_policy_inter< T, std::void_t< decltype(T::gaia_Data_Layout)> >", "structgaia_1_1mem_1_1detail_1_1auto__view__policy__inter_3_01T_00_01std_1_1void__t_3_01decltype_cfe7737336f7c33243e15d4959d4722b.html", null ],
          [ "is_soa_layout", "structgaia_1_1mem_1_1detail_1_1is__soa__layout.html", null ],
          [ "is_soa_layout< T, std::void_t< decltype(T::gaia_Data_Layout)> >", "structgaia_1_1mem_1_1detail_1_1is__soa__layout_3_01T_00_01std_1_1void__t_3_01decltype_07T_1_1gaia__Data__Layout_08_4_01_4.html", null ],
          [ "PagedAllocatorImpl", "classgaia_1_1mem_1_1detail_1_1PagedAllocatorImpl.html", "classgaia_1_1mem_1_1detail_1_1PagedAllocatorImpl" ],
          [ "raw_data_holder", "structgaia_1_1mem_1_1detail_1_1raw__data__holder.html", null ],
          [ "raw_data_holder< Size, 0 >", "structgaia_1_1mem_1_1detail_1_1raw__data__holder_3_01Size_00_010_01_4.html", null ]
        ] ],
        [ "AllocHelper", "structgaia_1_1mem_1_1AllocHelper.html", null ],
        [ "data_layout_properties", "structgaia_1_1mem_1_1data__layout__properties.html", null ],
        [ "data_layout_properties< DataLayout::AoS, TItem >", "structgaia_1_1mem_1_1data__layout__properties_3_01DataLayout_1_1AoS_00_01TItem_01_4.html", null ],
        [ "data_layout_properties< DataLayout::SoA, TItem >", "structgaia_1_1mem_1_1data__layout__properties_3_01DataLayout_1_1SoA_00_01TItem_01_4.html", null ],
        [ "data_layout_properties< DataLayout::SoA16, TItem >", "structgaia_1_1mem_1_1data__layout__properties_3_01DataLayout_1_1SoA16_00_01TItem_01_4.html", null ],
        [ "data_layout_properties< DataLayout::SoA8, TItem >", "structgaia_1_1mem_1_1data__layout__properties_3_01DataLayout_1_1SoA8_00_01TItem_01_4.html", null ],
        [ "data_view_policy", "structgaia_1_1mem_1_1data__view__policy.html", null ],
        [ "data_view_policy< DataLayout::AoS, ValueType >", "structgaia_1_1mem_1_1data__view__policy_3_01DataLayout_1_1AoS_00_01ValueType_01_4.html", null ],
        [ "data_view_policy< DataLayout::SoA, ValueType >", "structgaia_1_1mem_1_1data__view__policy_3_01DataLayout_1_1SoA_00_01ValueType_01_4.html", null ],
        [ "data_view_policy< DataLayout::SoA16, ValueType >", "structgaia_1_1mem_1_1data__view__policy_3_01DataLayout_1_1SoA16_00_01ValueType_01_4.html", null ],
        [ "data_view_policy< DataLayout::SoA8, ValueType >", "structgaia_1_1mem_1_1data__view__policy_3_01DataLayout_1_1SoA8_00_01ValueType_01_4.html", null ],
        [ "data_view_policy_aos", "structgaia_1_1mem_1_1data__view__policy__aos.html", null ],
        [ "data_view_policy_aos_get", "structgaia_1_1mem_1_1data__view__policy__aos__get.html", "structgaia_1_1mem_1_1data__view__policy__aos__get" ],
        [ "data_view_policy_aos_set", "structgaia_1_1mem_1_1data__view__policy__aos__set.html", "structgaia_1_1mem_1_1data__view__policy__aos__set" ],
        [ "data_view_policy_get", "structgaia_1_1mem_1_1data__view__policy__get.html", null ],
        [ "data_view_policy_get< DataLayout::AoS, ValueType >", "structgaia_1_1mem_1_1data__view__policy__get_3_01DataLayout_1_1AoS_00_01ValueType_01_4.html", null ],
        [ "data_view_policy_get< DataLayout::SoA, ValueType >", "structgaia_1_1mem_1_1data__view__policy__get_3_01DataLayout_1_1SoA_00_01ValueType_01_4.html", null ],
        [ "data_view_policy_get< DataLayout::SoA16, ValueType >", "structgaia_1_1mem_1_1data__view__policy__get_3_01DataLayout_1_1SoA16_00_01ValueType_01_4.html", null ],
        [ "data_view_policy_get< DataLayout::SoA8, ValueType >", "structgaia_1_1mem_1_1data__view__policy__get_3_01DataLayout_1_1SoA8_00_01ValueType_01_4.html", null ],
        [ "data_view_policy_get_idx", "structgaia_1_1mem_1_1data__view__policy__get__idx.html", null ],
        [ "data_view_policy_set", "structgaia_1_1mem_1_1data__view__policy__set.html", null ],
        [ "data_view_policy_set< DataLayout::AoS, ValueType >", "structgaia_1_1mem_1_1data__view__policy__set_3_01DataLayout_1_1AoS_00_01ValueType_01_4.html", null ],
        [ "data_view_policy_set< DataLayout::SoA, ValueType >", "structgaia_1_1mem_1_1data__view__policy__set_3_01DataLayout_1_1SoA_00_01ValueType_01_4.html", null ],
        [ "data_view_policy_set< DataLayout::SoA16, ValueType >", "structgaia_1_1mem_1_1data__view__policy__set_3_01DataLayout_1_1SoA16_00_01ValueType_01_4.html", null ],
        [ "data_view_policy_set< DataLayout::SoA8, ValueType >", "structgaia_1_1mem_1_1data__view__policy__set_3_01DataLayout_1_1SoA8_00_01ValueType_01_4.html", null ],
        [ "data_view_policy_set_idx", "structgaia_1_1mem_1_1data__view__policy__set__idx.html", null ],
        [ "data_view_policy_soa", "structgaia_1_1mem_1_1data__view__policy__soa.html", "structgaia_1_1mem_1_1data__view__policy__soa" ],
        [ "data_view_policy_soa_get", "structgaia_1_1mem_1_1data__view__policy__soa__get.html", "structgaia_1_1mem_1_1data__view__policy__soa__get" ],
        [ "data_view_policy_soa_set", "structgaia_1_1mem_1_1data__view__policy__soa__set.html", "structgaia_1_1mem_1_1data__view__policy__soa__set" ],
        [ "DefaultAllocator", "structgaia_1_1mem_1_1DefaultAllocator.html", null ],
        [ "DefaultAllocatorAdaptor", "structgaia_1_1mem_1_1DefaultAllocatorAdaptor.html", null ],
        [ "MemoryPage", "structgaia_1_1mem_1_1MemoryPage.html", "structgaia_1_1mem_1_1MemoryPage" ],
        [ "MemoryPageContainer", "structgaia_1_1mem_1_1MemoryPageContainer.html", "structgaia_1_1mem_1_1MemoryPageContainer" ],
        [ "MemoryPageHeader", "structgaia_1_1mem_1_1MemoryPageHeader.html", "structgaia_1_1mem_1_1MemoryPageHeader" ],
        [ "MemoryPageStats", "structgaia_1_1mem_1_1MemoryPageStats.html", "structgaia_1_1mem_1_1MemoryPageStats" ],
        [ "StackAllocator", "classgaia_1_1mem_1_1StackAllocator.html", "classgaia_1_1mem_1_1StackAllocator" ],
        [ "unaligned_ref", "classgaia_1_1mem_1_1unaligned__ref.html", null ]
      ] ],
      [ "meta", null, [
        [ "detail", null, [
          [ "any_type", "structgaia_1_1meta_1_1detail_1_1any__type.html", null ]
        ] ],
        [ "type_group", "classgaia_1_1meta_1_1type__group.html", null ],
        [ "type_info", "structgaia_1_1meta_1_1type__info.html", null ]
      ] ],
      [ "mt", null, [
        [ "detail", null, [
          [ "FutexBucket", "structgaia_1_1mt_1_1detail_1_1FutexBucket.html", null ],
          [ "FutexWaitNode", "structgaia_1_1mt_1_1detail_1_1FutexWaitNode.html", null ]
        ] ],
        [ "Event", "classgaia_1_1mt_1_1Event.html", null ],
        [ "Futex", "structgaia_1_1mt_1_1Futex.html", "structgaia_1_1mt_1_1Futex" ],
        [ "Job", "structgaia_1_1mt_1_1Job.html", null ],
        [ "JobAllocCtx", "structgaia_1_1mt_1_1JobAllocCtx.html", null ],
        [ "JobArgs", "structgaia_1_1mt_1_1JobArgs.html", null ],
        [ "JobContainer", "structgaia_1_1mt_1_1JobContainer.html", "structgaia_1_1mt_1_1JobContainer" ],
        [ "JobEdges", "structgaia_1_1mt_1_1JobEdges.html", "structgaia_1_1mt_1_1JobEdges" ],
        [ "JobHandle", "structgaia_1_1mt_1_1JobHandle.html", null ],
        [ "JobManager", "classgaia_1_1mt_1_1JobManager.html", "classgaia_1_1mt_1_1JobManager" ],
        [ "JobNull_t", "structgaia_1_1mt_1_1JobNull__t.html", null ],
        [ "JobParallel", "structgaia_1_1mt_1_1JobParallel.html", null ],
        [ "Semaphore", "classgaia_1_1mt_1_1Semaphore.html", "classgaia_1_1mt_1_1Semaphore" ],
        [ "SemaphoreFast", "classgaia_1_1mt_1_1SemaphoreFast.html", "classgaia_1_1mt_1_1SemaphoreFast" ],
        [ "SpinLock", "classgaia_1_1mt_1_1SpinLock.html", null ],
        [ "ThreadCtx", "structgaia_1_1mt_1_1ThreadCtx.html", "structgaia_1_1mt_1_1ThreadCtx" ],
        [ "ThreadPool", "classgaia_1_1mt_1_1ThreadPool.html", "classgaia_1_1mt_1_1ThreadPool" ]
      ] ],
      [ "ser", null, [
        [ "detail", null, [
          [ "ser_buffer_binary_impl", "classgaia_1_1ser_1_1detail_1_1ser__buffer__binary__impl.html", "classgaia_1_1ser_1_1detail_1_1ser__buffer__binary__impl" ]
        ] ],
        [ "is_flt_kind_id", "structgaia_1_1ser_1_1is__flt__kind__id.html", null ],
        [ "is_int_kind_id", "structgaia_1_1ser_1_1is__int__kind__id.html", null ],
        [ "is_trivially_serializable", "structgaia_1_1ser_1_1is__trivially__serializable.html", null ],
        [ "ISerializer", "structgaia_1_1ser_1_1ISerializer.html", null ],
        [ "load_tag", "structgaia_1_1ser_1_1load__tag.html", null ],
        [ "save_tag", "structgaia_1_1ser_1_1save__tag.html", null ],
        [ "ser_buffer_binary", "classgaia_1_1ser_1_1ser__buffer__binary.html", null ],
        [ "ser_buffer_binary_dyn", "classgaia_1_1ser_1_1ser__buffer__binary__dyn.html", null ]
      ] ],
      [ "util", null, [
        [ "detail", null, [
          [ "connect_arg_t", "structgaia_1_1util_1_1detail_1_1connect__arg__t.html", null ],
          [ "LogBuffer", "structgaia_1_1util_1_1detail_1_1LogBuffer.html", "structgaia_1_1util_1_1detail_1_1LogBuffer" ]
        ] ],
        [ "delegate", "classgaia_1_1util_1_1delegate.html", null ],
        [ "delegate< Ret(Args...)>", "classgaia_1_1util_1_1delegate_3_01Ret_07Args_8_8_8_08_4.html", "classgaia_1_1util_1_1delegate_3_01Ret_07Args_8_8_8_08_4" ],
        [ "signal", "classgaia_1_1util_1_1signal.html", null ],
        [ "signal< Ret(Args...)>", "classgaia_1_1util_1_1signal_3_01Ret_07Args_8_8_8_08_4.html", "classgaia_1_1util_1_1signal_3_01Ret_07Args_8_8_8_08_4" ],
        [ "sink", "classgaia_1_1util_1_1sink.html", null ],
        [ "sink< Ret(Args...)>", "classgaia_1_1util_1_1sink_3_01Ret_07Args_8_8_8_08_4.html", "classgaia_1_1util_1_1sink_3_01Ret_07Args_8_8_8_08_4" ]
      ] ]
    ] ],
    [ "robin_hood", null, [
      [ "detail", null, [
        [ "swappable", null, [
          [ "nothrow", "structrobin__hood_1_1detail_1_1swappable_1_1nothrow.html", null ]
        ] ],
        [ "BulkPoolAllocator", "classrobin__hood_1_1detail_1_1BulkPoolAllocator.html", null ],
        [ "has_hash", "structrobin__hood_1_1detail_1_1has__hash.html", null ],
        [ "has_hash< T, std::void_t< decltype(T::hash)> >", "structrobin__hood_1_1detail_1_1has__hash_3_01T_00_01std_1_1void__t_3_01decltype_07T_1_1hash_08_4_01_4.html", null ],
        [ "has_is_transparent", "structrobin__hood_1_1detail_1_1has__is__transparent.html", null ],
        [ "has_is_transparent< T, std::void_t< decltype(T::is_transparent)> >", "structrobin__hood_1_1detail_1_1has__is__transparent_3_01T_00_01std_1_1void__t_3_01decltype_07T_1_1is__transparent_08_4_01_4.html", null ],
        [ "NodeAllocator", "structrobin__hood_1_1detail_1_1NodeAllocator.html", null ],
        [ "NodeAllocator< T, MinSize, MaxSize, false >", "structrobin__hood_1_1detail_1_1NodeAllocator_3_01T_00_01MinSize_00_01MaxSize_00_01false_01_4.html", null ],
        [ "NodeAllocator< T, MinSize, MaxSize, true >", "structrobin__hood_1_1detail_1_1NodeAllocator_3_01T_00_01MinSize_00_01MaxSize_00_01true_01_4.html", null ],
        [ "Table", "classrobin__hood_1_1detail_1_1Table.html", null ],
        [ "WrapHash", "structrobin__hood_1_1detail_1_1WrapHash.html", null ],
        [ "WrapKeyEqual", "structrobin__hood_1_1detail_1_1WrapKeyEqual.html", null ]
      ] ],
      [ "hash", "structrobin__hood_1_1hash.html", null ],
      [ "hash< Enum, typename std::enable_if< std::is_enum< Enum >::value >::type >", "structrobin__hood_1_1hash_3_01Enum_00_01typename_01std_1_1enable__if_3_01std_1_1is__enum_3_01Enu66d88786d8b4d7158b0da3f501596c68.html", null ],
      [ "hash< T * >", "structrobin__hood_1_1hash_3_01T_01_5_01_4.html", null ],
      [ "hash< T, typename std::enable_if< gaia::core::is_direct_hash_key_v< T > >::type >", "structrobin__hood_1_1hash_3_01T_00_01typename_01std_1_1enable__if_3_01gaia_1_1core_1_1is__directb90c969b64bee2ef071a5927f60384d3.html", null ],
      [ "is_transparent_tag", "structrobin__hood_1_1is__transparent__tag.html", null ],
      [ "pair", "structrobin__hood_1_1pair.html", null ]
    ] ],
    [ "std", null, [
      [ "tuple_element< I, gaia::cnt::sarr< T, N > >", "structstd_1_1tuple__element_3_01I_00_01gaia_1_1cnt_1_1sarr_3_01T_00_01N_01_4_01_4.html", null ],
      [ "tuple_element< I, gaia::cnt::sarr_ext< T, N > >", "structstd_1_1tuple__element_3_01I_00_01gaia_1_1cnt_1_1sarr__ext_3_01T_00_01N_01_4_01_4.html", null ],
      [ "tuple_element< I, gaia::cnt::sarr_ext_soa< T, N > >", "structstd_1_1tuple__element_3_01I_00_01gaia_1_1cnt_1_1sarr__ext__soa_3_01T_00_01N_01_4_01_4.html", null ],
      [ "tuple_element< I, gaia::cnt::sarr_soa< T, N > >", "structstd_1_1tuple__element_3_01I_00_01gaia_1_1cnt_1_1sarr__soa_3_01T_00_01N_01_4_01_4.html", null ],
      [ "tuple_element< I, gaia::core::span< T, Extent > >", "structstd_1_1tuple__element_3_01I_00_01gaia_1_1core_1_1span_3_01T_00_01Extent_01_4_01_4.html", null ],
      [ "tuple_size< gaia::cnt::sarr< T, N > >", "structstd_1_1tuple__size_3_01gaia_1_1cnt_1_1sarr_3_01T_00_01N_01_4_01_4.html", null ],
      [ "tuple_size< gaia::cnt::sarr_ext< T, N > >", "structstd_1_1tuple__size_3_01gaia_1_1cnt_1_1sarr__ext_3_01T_00_01N_01_4_01_4.html", null ],
      [ "tuple_size< gaia::cnt::sarr_ext_soa< T, N > >", "structstd_1_1tuple__size_3_01gaia_1_1cnt_1_1sarr__ext__soa_3_01T_00_01N_01_4_01_4.html", null ],
      [ "tuple_size< gaia::cnt::sarr_soa< T, N > >", "structstd_1_1tuple__size_3_01gaia_1_1cnt_1_1sarr__soa_3_01T_00_01N_01_4_01_4.html", null ],
      [ "tuple_size< gaia::core::span< T, Extent > >", "structstd_1_1tuple__size_3_01gaia_1_1core_1_1span_3_01T_00_01Extent_01_4_01_4.html", null ]
    ] ]
];