var hierarchy =
[
    [ "gaia::ecs::_Var0", "structgaia_1_1ecs_1_1__Var0.html", null ],
    [ "gaia::ecs::_Var1", "structgaia_1_1ecs_1_1__Var1.html", null ],
    [ "gaia::ecs::_Var2", "structgaia_1_1ecs_1_1__Var2.html", null ],
    [ "gaia::ecs::_Var3", "structgaia_1_1ecs_1_1__Var3.html", null ],
    [ "gaia::ecs::_Var4", "structgaia_1_1ecs_1_1__Var4.html", null ],
    [ "gaia::ecs::_Var5", "structgaia_1_1ecs_1_1__Var5.html", null ],
    [ "gaia::ecs::_Var6", "structgaia_1_1ecs_1_1__Var6.html", null ],
    [ "gaia::ecs::_Var7", "structgaia_1_1ecs_1_1__Var7.html", null ],
    [ "gaia::ecs::AccessContextMT", "structgaia_1_1ecs_1_1AccessContextMT.html", null ],
    [ "gaia::ecs::AccessContextST", "structgaia_1_1ecs_1_1AccessContextST.html", null ],
    [ "gaia::mem::data_view_policy_soa< TDataLayout, ValueType >::accessor", "classgaia_1_1mem_1_1data__view__policy__soa_1_1accessor.html", null ],
    [ "gaia::mem::data_view_policy_soa_set< TDataLayout, ValueType >::accessor", "structgaia_1_1mem_1_1data__view__policy__soa__set_1_1accessor.html", null ],
    [ "gaia::ecs::detail::actual_type< T, U >", "structgaia_1_1ecs_1_1detail_1_1actual__type.html", null ],
    [ "gaia::ecs::detail::actual_type< T, std::enable_if_t< is_pair< T >::value > >", "structgaia_1_1ecs_1_1detail_1_1actual__type_3_01T_00_01std_1_1enable__if__t_3_01is__pair_3_01T_01_4_1_1value_01_4_01_4.html", null ],
    [ "gaia::ecs::Acyclic_", "structgaia_1_1ecs_1_1Acyclic__.html", null ],
    [ "gaia::ecs::All_", "structgaia_1_1ecs_1_1All__.html", null ],
    [ "gaia::mem::detail::AllocationInfo", "structgaia_1_1mem_1_1detail_1_1AllocationInfo.html", null ],
    [ "gaia::mem::AllocHelper", "structgaia_1_1mem_1_1AllocHelper.html", null ],
    [ "gaia::meta::detail::any_type", "structgaia_1_1meta_1_1detail_1_1any__type.html", null ],
    [ "gaia::ecs::ArchetypeBase", "classgaia_1_1ecs_1_1ArchetypeBase.html", [
      [ "gaia::ecs::Archetype", "classgaia_1_1ecs_1_1Archetype.html", null ],
      [ "gaia::ecs::ArchetypeLookupChecker", "classgaia_1_1ecs_1_1ArchetypeLookupChecker.html", null ]
    ] ],
    [ "gaia::ecs::ArchetypeCacheData", "structgaia_1_1ecs_1_1ArchetypeCacheData.html", null ],
    [ "gaia::ecs::ArchetypeChunkPair", "structgaia_1_1ecs_1_1ArchetypeChunkPair.html", null ],
    [ "gaia::ecs::ArchetypeGraph", "classgaia_1_1ecs_1_1ArchetypeGraph.html", null ],
    [ "gaia::ecs::ArchetypeIdHashPair", "structgaia_1_1ecs_1_1ArchetypeIdHashPair.html", null ],
    [ "gaia::ecs::ArchetypeIdLookupKey", "classgaia_1_1ecs_1_1ArchetypeIdLookupKey.html", null ],
    [ "gaia::ecs::ArchetypeLookupKey", "classgaia_1_1ecs_1_1ArchetypeLookupKey.html", null ],
    [ "gaia::mem::detail::auto_view_policy_inter< typename, typename >", "structgaia_1_1mem_1_1detail_1_1auto__view__policy__inter.html", null ],
    [ "gaia::mem::detail::auto_view_policy_inter< T, std::void_t< decltype(T::gaia_Data_Layout)> >", "structgaia_1_1mem_1_1detail_1_1auto__view__policy__inter_3_01T_00_01std_1_1void__t_3_01decltype_cfe7737336f7c33243e15d4959d4722b.html", null ],
    [ "gaia::core::bit_view< BlockBits >", "structgaia_1_1core_1_1bit__view.html", null ],
    [ "gaia::cnt::bitset< NBits >", "classgaia_1_1cnt_1_1bitset.html", null ],
    [ "gaia::cnt::bitset< PageCapacity >", "classgaia_1_1cnt_1_1bitset.html", null ],
    [ "gaia::cnt::bitset_const_iterator< TBitset, IsFwd, IsInverse >", "classgaia_1_1cnt_1_1bitset__const__iterator.html", null ],
    [ "std::bool_constant", null, [
      [ "gaia::core::detail::is_mut< T >", "structgaia_1_1core_1_1detail_1_1is__mut.html", null ],
      [ "gaia::core::is_iterator< T >", "structgaia_1_1core_1_1is__iterator.html", null ],
      [ "gaia::ecs::detail::is_gen_component< T, std::void_t< decltype(T::Kind)> >", "structgaia_1_1ecs_1_1detail_1_1is__gen__component_3_01T_00_01std_1_1void__t_3_01decltype_07T_1_1Kind_08_4_01_4.html", null ],
      [ "gaia::mem::detail::is_soa_layout< T, std::void_t< decltype(T::gaia_Data_Layout)> >", "structgaia_1_1mem_1_1detail_1_1is__soa__layout_3_01T_00_01std_1_1void__t_3_01decltype_07T_1_1gaia__Data__Layout_08_4_01_4.html", null ]
    ] ],
    [ "robin_hood::detail::BulkPoolAllocator< T, MinNumAllocs, MaxNumAllocs >", "classrobin__hood_1_1detail_1_1BulkPoolAllocator.html", null ],
    [ "robin_hood::detail::BulkPoolAllocator< T, MinSize, MaxSize >", "classrobin__hood_1_1detail_1_1BulkPoolAllocator.html", [
      [ "robin_hood::detail::NodeAllocator< T, MinSize, MaxSize, false >", "structrobin__hood_1_1detail_1_1NodeAllocator_3_01T_00_01MinSize_00_01MaxSize_00_01false_01_4.html", null ]
    ] ],
    [ "gaia::ecs::CantCombine_", "structgaia_1_1ecs_1_1CantCombine__.html", null ],
    [ "gaia::ecs::ChildOf_", "structgaia_1_1ecs_1_1ChildOf__.html", null ],
    [ "gaia::ecs::Chunk", "classgaia_1_1ecs_1_1Chunk.html", null ],
    [ "gaia::ecs::ChunkDataOffsets", "structgaia_1_1ecs_1_1ChunkDataOffsets.html", null ],
    [ "gaia::ecs::ChunkHeader", "structgaia_1_1ecs_1_1ChunkHeader.html", null ],
    [ "gaia::ecs::detail::ChunkIterImpl< IterConstraint >", "classgaia_1_1ecs_1_1detail_1_1ChunkIterImpl.html", null ],
    [ "gaia::ecs::detail::ChunkIterImpl< Constraints::AcceptAll >", "classgaia_1_1ecs_1_1detail_1_1ChunkIterImpl.html", [
      [ "gaia::ecs::IterAll", "classgaia_1_1ecs_1_1IterAll.html", null ]
    ] ],
    [ "gaia::ecs::detail::ChunkIterImpl< Constraints::DisabledOnly >", "classgaia_1_1ecs_1_1detail_1_1ChunkIterImpl.html", [
      [ "gaia::ecs::IterDisabled", "classgaia_1_1ecs_1_1IterDisabled.html", null ]
    ] ],
    [ "gaia::ecs::detail::ChunkIterImpl< Constraints::EnabledOnly >", "classgaia_1_1ecs_1_1detail_1_1ChunkIterImpl.html", [
      [ "gaia::ecs::Iter", "classgaia_1_1ecs_1_1Iter.html", null ]
    ] ],
    [ "gaia::ecs::ChunkRecords", "structgaia_1_1ecs_1_1ChunkRecords.html", null ],
    [ "gaia::ecs::QueryInfo::CleanUpTmpArchetypeMatches", "structgaia_1_1ecs_1_1QueryInfo_1_1CleanUpTmpArchetypeMatches.html", null ],
    [ "gaia::ecs::detail::CommandBuffer< AccessContext >", "classgaia_1_1ecs_1_1detail_1_1CommandBuffer.html", null ],
    [ "gaia::ecs::vm::detail::CompiledOp", "structgaia_1_1ecs_1_1vm_1_1detail_1_1CompiledOp.html", null ],
    [ "gaia::ecs::Component", "structgaia_1_1ecs_1_1Component.html", null ],
    [ "gaia::ecs::detail::component_type< T, typename >", "structgaia_1_1ecs_1_1detail_1_1component__type.html", null ],
    [ "gaia::ecs::detail::component_type< T, std::void_t< decltype(T::Kind)> >", "structgaia_1_1ecs_1_1detail_1_1component__type_3_01T_00_01std_1_1void__t_3_01decltype_07T_1_1Kind_08_4_01_4.html", null ],
    [ "gaia::ecs::ComponentCache", "classgaia_1_1ecs_1_1ComponentCache.html", null ],
    [ "gaia::ecs::ComponentCacheItem", "structgaia_1_1ecs_1_1ComponentCacheItem.html", null ],
    [ "gaia::ecs::detail::ComponentDesc< T >", "structgaia_1_1ecs_1_1detail_1_1ComponentDesc.html", null ],
    [ "gaia::ecs::ComponentGetter", "structgaia_1_1ecs_1_1ComponentGetter.html", [
      [ "gaia::ecs::ComponentSetter", "structgaia_1_1ecs_1_1ComponentSetter.html", null ]
    ] ],
    [ "gaia::ecs::ComponentRecord", "structgaia_1_1ecs_1_1ComponentRecord.html", null ],
    [ "std::conditional_t", null, [
      [ "gaia::core::unique< std::tuple< Ts... >, U, Us... >", "structgaia_1_1core_1_1unique_3_01std_1_1tuple_3_01Ts_8_8_8_01_4_00_01U_00_01Us_8_8_8_01_4.html", null ]
    ] ],
    [ "gaia::util::detail::connect_arg_t< auto >", "structgaia_1_1util_1_1detail_1_1connect__arg__t.html", null ],
    [ "gaia::cnt::const_darr_ext_soa_iterator< T >", "structgaia_1_1cnt_1_1const__darr__ext__soa__iterator.html", null ],
    [ "gaia::cnt::const_darr_soa_iterator< T >", "structgaia_1_1cnt_1_1const__darr__soa__iterator.html", null ],
    [ "gaia::cnt::const_page_iterator< T, Allocator, IsFwd >", "structgaia_1_1cnt_1_1const__page__iterator.html", null ],
    [ "gaia::cnt::const_page_iterator_soa< T, Allocator, IsFwd >", "structgaia_1_1cnt_1_1const__page__iterator__soa.html", null ],
    [ "gaia::cnt::const_sarr_ext_soa_iterator< T >", "structgaia_1_1cnt_1_1const__sarr__ext__soa__iterator.html", null ],
    [ "gaia::cnt::const_sarr_soa_iterator< T >", "structgaia_1_1cnt_1_1const__sarr__soa__iterator.html", null ],
    [ "gaia::cnt::const_sparse_iterator< T, PageCapacity, Allocator, typename >", "structgaia_1_1cnt_1_1const__sparse__iterator.html", null ],
    [ "gaia::cnt::const_sparse_iterator< T, PageCapacity, Allocator, std::enable_if_t< std::is_empty_v< T > > >", "structgaia_1_1cnt_1_1const__sparse__iterator_3_01T_00_01PageCapacity_00_01Allocator_00_01std_1_1ac6071468172e14d5e0cd6a6d6bb0e21.html", null ],
    [ "gaia::ecs::CopyIter", "classgaia_1_1ecs_1_1CopyIter.html", null ],
    [ "gaia::ecs::Core_", "structgaia_1_1ecs_1_1Core__.html", null ],
    [ "gaia::cnt::darr< T, Allocator >", "classgaia_1_1cnt_1_1darr.html", [
      [ "gaia::cnt::darray_ilist_storage< gaia::ecs::EntityContainer >", "structgaia_1_1cnt_1_1darray__ilist__storage.html", null ],
      [ "gaia::cnt::darray_ilist_storage< gaia::ecs::QueryInfo >", "structgaia_1_1cnt_1_1darray__ilist__storage.html", null ],
      [ "gaia::cnt::darray_ilist_storage< gaia::mt::JobContainer >", "structgaia_1_1cnt_1_1darray__ilist__storage.html", null ],
      [ "gaia::cnt::darray_ilist_storage< TListItem >", "structgaia_1_1cnt_1_1darray__ilist__storage.html", null ]
    ] ],
    [ "gaia::cnt::darr< Archetype * >", "classgaia_1_1cnt_1_1darr.html", null ],
    [ "gaia::cnt::darr< ChunkBatch >", "classgaia_1_1cnt_1_1darr.html", null ],
    [ "gaia::cnt::darr< const Archetype * >", "classgaia_1_1cnt_1_1darr.html", null ],
    [ "gaia::cnt::darr< const gaia::ecs::Archetype * >", "classgaia_1_1cnt_1_1darr.html", null ],
    [ "gaia::cnt::darr< const gaia::ecs::ComponentCacheItem * >", "classgaia_1_1cnt_1_1darr.html", null ],
    [ "gaia::cnt::darr< gaia::cnt::detail::mem_page >", "classgaia_1_1cnt_1_1darr.html", null ],
    [ "gaia::cnt::darr< gaia::cnt::detail::sparse_page >", "classgaia_1_1cnt_1_1darr.html", null ],
    [ "gaia::cnt::darr< gaia::cnt::detail::sparse_page< T, PageCapacity, Allocator, std::enable_if_t< std::is_empty_v< T > > > >", "classgaia_1_1cnt_1_1darr.html", null ],
    [ "gaia::cnt::darr< gaia::ecs::ArchetypeCacheData >", "classgaia_1_1cnt_1_1darr.html", null ],
    [ "gaia::cnt::darr< gaia::ecs::ArchetypeChunkPair >", "classgaia_1_1cnt_1_1darr.html", null ],
    [ "gaia::cnt::darr< gaia::ecs::Chunk * >", "classgaia_1_1cnt_1_1darr.html", null ],
    [ "gaia::cnt::darr< gaia::ecs::ComponentCacheItem::SchemaField >", "classgaia_1_1cnt_1_1darr.html", null ],
    [ "gaia::cnt::darr< gaia::ecs::vm::detail::CompiledOp >", "classgaia_1_1cnt_1_1darr.html", null ],
    [ "gaia::cnt::darr< GroupData >", "classgaia_1_1cnt_1_1darr.html", null ],
    [ "gaia::cnt::darr< Ret, Args... >", "classgaia_1_1cnt_1_1darr.html", null ],
    [ "gaia::cnt::darr< SortData >", "classgaia_1_1cnt_1_1darr.html", null ],
    [ "gaia::cnt::darr< sparse_id >", "classgaia_1_1cnt_1_1darr.html", null ],
    [ "gaia::cnt::darr_ext< T, N, Allocator >", "classgaia_1_1cnt_1_1darr__ext.html", null ],
    [ "gaia::cnt::darr_ext< gaia::ecs::Entity, 128 >", "classgaia_1_1cnt_1_1darr__ext.html", null ],
    [ "gaia::cnt::darr_ext< Op, 128 >", "classgaia_1_1cnt_1_1darr__ext.html", null ],
    [ "gaia::cnt::darr_ext_soa< T, N, Allocator >", "classgaia_1_1cnt_1_1darr__ext__soa.html", null ],
    [ "gaia::cnt::darr_ext_soa_iterator< T >", "structgaia_1_1cnt_1_1darr__ext__soa__iterator.html", null ],
    [ "gaia::cnt::darr_soa< T, Allocator >", "classgaia_1_1cnt_1_1darr__soa.html", null ],
    [ "gaia::cnt::darr_soa_iterator< T >", "structgaia_1_1cnt_1_1darr__soa__iterator.html", null ],
    [ "gaia::ecs::QueryCtx::Data", "structgaia_1_1ecs_1_1QueryCtx_1_1Data.html", null ],
    [ "gaia::mem::data_layout_properties< TDataLayout, TItem >", "structgaia_1_1mem_1_1data__layout__properties.html", null ],
    [ "gaia::mem::data_layout_properties< DataLayout::AoS, TItem >", "structgaia_1_1mem_1_1data__layout__properties_3_01DataLayout_1_1AoS_00_01TItem_01_4.html", null ],
    [ "gaia::mem::data_layout_properties< DataLayout::SoA, TItem >", "structgaia_1_1mem_1_1data__layout__properties_3_01DataLayout_1_1SoA_00_01TItem_01_4.html", null ],
    [ "gaia::mem::data_layout_properties< DataLayout::SoA16, TItem >", "structgaia_1_1mem_1_1data__layout__properties_3_01DataLayout_1_1SoA16_00_01TItem_01_4.html", null ],
    [ "gaia::mem::data_layout_properties< DataLayout::SoA8, TItem >", "structgaia_1_1mem_1_1data__layout__properties_3_01DataLayout_1_1SoA8_00_01TItem_01_4.html", null ],
    [ "gaia::mem::data_view_policy< TDataLayout, TItem >", "structgaia_1_1mem_1_1data__view__policy.html", null ],
    [ "gaia::mem::data_view_policy_aos< ValueType >", "structgaia_1_1mem_1_1data__view__policy__aos.html", [
      [ "gaia::mem::data_view_policy< DataLayout::AoS, ValueType >", "structgaia_1_1mem_1_1data__view__policy_3_01DataLayout_1_1AoS_00_01ValueType_01_4.html", null ]
    ] ],
    [ "gaia::mem::data_view_policy_aos_get< ValueType >", "structgaia_1_1mem_1_1data__view__policy__aos__get.html", [
      [ "gaia::mem::data_view_policy_get< DataLayout::AoS, ValueType >", "structgaia_1_1mem_1_1data__view__policy__get_3_01DataLayout_1_1AoS_00_01ValueType_01_4.html", null ]
    ] ],
    [ "gaia::mem::data_view_policy_aos_set< ValueType >", "structgaia_1_1mem_1_1data__view__policy__aos__set.html", [
      [ "gaia::mem::data_view_policy_set< DataLayout::AoS, ValueType >", "structgaia_1_1mem_1_1data__view__policy__set_3_01DataLayout_1_1AoS_00_01ValueType_01_4.html", null ]
    ] ],
    [ "gaia::mem::data_view_policy_get< TDataLayout, TItem >", "structgaia_1_1mem_1_1data__view__policy__get.html", null ],
    [ "gaia::mem::data_view_policy_get_idx< TDataLayout, TItem, Ids >", "structgaia_1_1mem_1_1data__view__policy__get__idx.html", null ],
    [ "gaia::mem::data_view_policy_soa_get< TDataLayout, ValueType >::data_view_policy_idx_info< Item >", "structgaia_1_1mem_1_1data__view__policy__soa__get_1_1data__view__policy__idx__info.html", null ],
    [ "gaia::mem::data_view_policy_soa_set< TDataLayout, ValueType >::data_view_policy_idx_info< Item >", "structgaia_1_1mem_1_1data__view__policy__soa__set_1_1data__view__policy__idx__info.html", null ],
    [ "gaia::mem::data_view_policy_set< TDataLayout, TItem >", "structgaia_1_1mem_1_1data__view__policy__set.html", null ],
    [ "gaia::mem::data_view_policy_set_idx< TDataLayout, TItem, Ids >", "structgaia_1_1mem_1_1data__view__policy__set__idx.html", null ],
    [ "gaia::mem::data_view_policy_soa< TDataLayout, ValueType >", "structgaia_1_1mem_1_1data__view__policy__soa.html", null ],
    [ "gaia::mem::data_view_policy_soa< DataLayout::SoA, ValueType >", "structgaia_1_1mem_1_1data__view__policy__soa.html", [
      [ "gaia::mem::data_view_policy< DataLayout::SoA, ValueType >", "structgaia_1_1mem_1_1data__view__policy_3_01DataLayout_1_1SoA_00_01ValueType_01_4.html", null ]
    ] ],
    [ "gaia::mem::data_view_policy_soa< DataLayout::SoA16, ValueType >", "structgaia_1_1mem_1_1data__view__policy__soa.html", [
      [ "gaia::mem::data_view_policy< DataLayout::SoA16, ValueType >", "structgaia_1_1mem_1_1data__view__policy_3_01DataLayout_1_1SoA16_00_01ValueType_01_4.html", null ]
    ] ],
    [ "gaia::mem::data_view_policy_soa< DataLayout::SoA8, ValueType >", "structgaia_1_1mem_1_1data__view__policy__soa.html", [
      [ "gaia::mem::data_view_policy< DataLayout::SoA8, ValueType >", "structgaia_1_1mem_1_1data__view__policy_3_01DataLayout_1_1SoA8_00_01ValueType_01_4.html", null ]
    ] ],
    [ "gaia::mem::data_view_policy_soa_get< TDataLayout, ValueType >", "structgaia_1_1mem_1_1data__view__policy__soa__get.html", null ],
    [ "gaia::mem::data_view_policy_soa_get< DataLayout::SoA, ValueType >", "structgaia_1_1mem_1_1data__view__policy__soa__get.html", [
      [ "gaia::mem::data_view_policy_get< DataLayout::SoA, ValueType >", "structgaia_1_1mem_1_1data__view__policy__get_3_01DataLayout_1_1SoA_00_01ValueType_01_4.html", null ]
    ] ],
    [ "gaia::mem::data_view_policy_soa_get< DataLayout::SoA16, ValueType >", "structgaia_1_1mem_1_1data__view__policy__soa__get.html", [
      [ "gaia::mem::data_view_policy_get< DataLayout::SoA16, ValueType >", "structgaia_1_1mem_1_1data__view__policy__get_3_01DataLayout_1_1SoA16_00_01ValueType_01_4.html", null ]
    ] ],
    [ "gaia::mem::data_view_policy_soa_get< DataLayout::SoA8, ValueType >", "structgaia_1_1mem_1_1data__view__policy__soa__get.html", [
      [ "gaia::mem::data_view_policy_get< DataLayout::SoA8, ValueType >", "structgaia_1_1mem_1_1data__view__policy__get_3_01DataLayout_1_1SoA8_00_01ValueType_01_4.html", null ]
    ] ],
    [ "gaia::mem::data_view_policy_soa_set< TDataLayout, ValueType >", "structgaia_1_1mem_1_1data__view__policy__soa__set.html", null ],
    [ "gaia::mem::data_view_policy_soa_set< DataLayout::SoA, ValueType >", "structgaia_1_1mem_1_1data__view__policy__soa__set.html", [
      [ "gaia::mem::data_view_policy_set< DataLayout::SoA, ValueType >", "structgaia_1_1mem_1_1data__view__policy__set_3_01DataLayout_1_1SoA_00_01ValueType_01_4.html", null ]
    ] ],
    [ "gaia::mem::data_view_policy_soa_set< DataLayout::SoA16, ValueType >", "structgaia_1_1mem_1_1data__view__policy__soa__set.html", [
      [ "gaia::mem::data_view_policy_set< DataLayout::SoA16, ValueType >", "structgaia_1_1mem_1_1data__view__policy__set_3_01DataLayout_1_1SoA16_00_01ValueType_01_4.html", null ]
    ] ],
    [ "gaia::mem::data_view_policy_soa_set< DataLayout::SoA8, ValueType >", "structgaia_1_1mem_1_1data__view__policy__soa__set.html", [
      [ "gaia::mem::data_view_policy_set< DataLayout::SoA8, ValueType >", "structgaia_1_1mem_1_1data__view__policy__set_3_01DataLayout_1_1SoA8_00_01ValueType_01_4.html", null ]
    ] ],
    [ "gaia::cnt::dbitset< Allocator >", "classgaia_1_1cnt_1_1dbitset.html", null ],
    [ "gaia::cnt::dbitset< gaia::mem::DefaultAllocatorAdaptor >", "classgaia_1_1cnt_1_1dbitset.html", null ],
    [ "gaia::mem::DefaultAllocator", "structgaia_1_1mem_1_1DefaultAllocator.html", null ],
    [ "gaia::mem::DefaultAllocatorAdaptor", "structgaia_1_1mem_1_1DefaultAllocatorAdaptor.html", null ],
    [ "gaia::util::delegate< typename >", "classgaia_1_1util_1_1delegate.html", null ],
    [ "gaia::util::delegate< Ret(Args...)>", "classgaia_1_1util_1_1delegate_3_01Ret_07Args_8_8_8_08_4.html", null ],
    [ "gaia::ecs::Delete_", "structgaia_1_1ecs_1_1Delete__.html", null ],
    [ "gaia::ecs::DependsOn_", "structgaia_1_1ecs_1_1DependsOn__.html", null ],
    [ "gaia::core::direct_hash_key< T >", "structgaia_1_1core_1_1direct__hash__key.html", null ],
    [ "gaia::core::direct_hash_key< uint32_t >", "structgaia_1_1core_1_1direct__hash__key.html", null ],
    [ "gaia::core::direct_hash_key< uint64_t >", "structgaia_1_1core_1_1direct__hash__key.html", null ],
    [ "std::disjunction", null, [
      [ "gaia::ser::is_flt_kind_id< T >", "structgaia_1_1ser_1_1is__flt__kind__id.html", null ],
      [ "gaia::ser::is_int_kind_id< T >", "structgaia_1_1ser_1_1is__int__kind__id.html", null ]
    ] ],
    [ "gaia::core::dyn_singleton< T >", "classgaia_1_1core_1_1dyn__singleton.html", null ],
    [ "gaia::ecs::Entity", "structgaia_1_1ecs_1_1Entity.html", null ],
    [ "gaia::ecs::World::EntityBuilder", "structgaia_1_1ecs_1_1World_1_1EntityBuilder.html", null ],
    [ "gaia::ecs::EntityContainerCtx", "structgaia_1_1ecs_1_1EntityContainerCtx.html", null ],
    [ "gaia::ecs::EntityContainers", "structgaia_1_1ecs_1_1EntityContainers.html", null ],
    [ "gaia::ecs::EntityContainer::EntityData", "structgaia_1_1ecs_1_1EntityContainer_1_1EntityData.html", null ],
    [ "gaia::ecs::EntityDesc", "structgaia_1_1ecs_1_1EntityDesc.html", null ],
    [ "gaia::ecs::EntityLookupKey", "structgaia_1_1ecs_1_1EntityLookupKey.html", null ],
    [ "gaia::core::equal_to< T >", "structgaia_1_1core_1_1equal__to.html", null ],
    [ "gaia::ecs::Error_", "structgaia_1_1ecs_1_1Error__.html", null ],
    [ "gaia::mt::Event", "classgaia_1_1mt_1_1Event.html", null ],
    [ "gaia::ecs::Exclusive_", "structgaia_1_1ecs_1_1Exclusive__.html", null ],
    [ "gaia::ecs::detail::ExtractComponentType_NoEntityKind< T >", "structgaia_1_1ecs_1_1detail_1_1ExtractComponentType__NoEntityKind.html", null ],
    [ "gaia::ecs::detail::ExtractComponentType_WithEntityKind< T >", "structgaia_1_1ecs_1_1detail_1_1ExtractComponentType__WithEntityKind.html", null ],
    [ "std::false_type", null, [
      [ "gaia::core::detail::is_complete< typename, typename >", "structgaia_1_1core_1_1detail_1_1is__complete.html", null ],
      [ "gaia::core::detail::is_container_element_kind_compatible< typename, typename, typename >", "structgaia_1_1core_1_1detail_1_1is__container__element__kind__compatible.html", null ],
      [ "gaia::core::detail::is_direct_hash_key< typename, typename >", "structgaia_1_1core_1_1detail_1_1is__direct__hash__key.html", null ],
      [ "gaia::core::detail::is_span< typename >", "structgaia_1_1core_1_1detail_1_1is__span.html", null ],
      [ "gaia::core::detail::is_std_array< typename >", "structgaia_1_1core_1_1detail_1_1is__std__array.html", null ],
      [ "gaia::core::has_data_size< typename, typename >", "structgaia_1_1core_1_1has__data__size.html", null ],
      [ "gaia::core::has_size_begin_end< typename, typename >", "structgaia_1_1core_1_1has__size__begin__end.html", null ],
      [ "gaia::detail::is_reference_wrapper< T >", "structgaia_1_1detail_1_1is__reference__wrapper.html", null ],
      [ "gaia::ecs::detail::has_entity_kind< typename, typename >", "structgaia_1_1ecs_1_1detail_1_1has__entity__kind.html", null ],
      [ "gaia::mem::detail::is_soa_layout< typename, typename >", "structgaia_1_1mem_1_1detail_1_1is__soa__layout.html", null ],
      [ "robin_hood::detail::has_hash< typename, typename >", "structrobin__hood_1_1detail_1_1has__hash.html", null ],
      [ "robin_hood::detail::has_is_transparent< typename, typename >", "structrobin__hood_1_1detail_1_1has__is__transparent.html", null ]
    ] ],
    [ "gaia::core::func_type_list< Type >", "structgaia_1_1core_1_1func__type__list.html", null ],
    [ "gaia::mt::Futex", "structgaia_1_1mt_1_1Futex.html", null ],
    [ "gaia::mt::detail::FutexBucket", "structgaia_1_1mt_1_1detail_1_1FutexBucket.html", null ],
    [ "gaia::mt::detail::FutexWaitNode", "structgaia_1_1mt_1_1detail_1_1FutexWaitNode.html", null ],
    [ "gaia::cnt::fwd_llist< T >", "structgaia_1_1cnt_1_1fwd__llist.html", null ],
    [ "gaia::cnt::fwd_llist< gaia::mem::MemoryPage< T, RequestedBlockSize > >", "structgaia_1_1cnt_1_1fwd__llist.html", null ],
    [ "gaia::cnt::fwd_llist_base< T >", "structgaia_1_1cnt_1_1fwd__llist__base.html", null ],
    [ "gaia::cnt::fwd_llist_base< MemoryPage< T, RequestedBlockSize > >", "structgaia_1_1cnt_1_1fwd__llist__base.html", [
      [ "gaia::mem::MemoryPage< T, RequestedBlockSize >", "structgaia_1_1mem_1_1MemoryPage.html", null ]
    ] ],
    [ "gaia::cnt::fwd_llist_iterator< T >", "structgaia_1_1cnt_1_1fwd__llist__iterator.html", null ],
    [ "gaia::cnt::fwd_llist_link< T >", "structgaia_1_1cnt_1_1fwd__llist__link.html", null ],
    [ "gaia::cnt::fwd_llist_link< MemoryPage< T, RequestedBlockSize > >", "structgaia_1_1cnt_1_1fwd__llist__link.html", null ],
    [ "gaia::core::has_ffunc_equals< T >", "structgaia_1_1core_1_1has__ffunc__equals.html", null ],
    [ "gaia::core::has_func_equals< T >", "structgaia_1_1core_1_1has__func__equals.html", null ],
    [ "Hash", null, [
      [ "robin_hood::detail::WrapHash< Hash >", "structrobin__hood_1_1detail_1_1WrapHash.html", [
        [ "robin_hood::detail::Table< EntityLookupKey, ArchetypeGraphEdge >", "classrobin__hood_1_1detail_1_1Table.html", null ],
        [ "robin_hood::detail::Table< detail::ComponentDescId, const gaia::ecs::ComponentCacheItem * >", "classrobin__hood_1_1detail_1_1Table.html", null ],
        [ "robin_hood::detail::Table< gaia::core::StringLookupKey, const gaia::ecs::ComponentCacheItem * >", "classrobin__hood_1_1detail_1_1Table.html", null ],
        [ "robin_hood::detail::Table< gaia::ecs::EntityLookupKey, const gaia::ecs::ComponentCacheItem * >", "classrobin__hood_1_1detail_1_1Table.html", null ],
        [ "robin_hood::detail::Table< gaia::ecs::EntityLookupKey, gaia::ecs::EntityContainer >", "classrobin__hood_1_1detail_1_1Table.html", null ],
        [ "robin_hood::detail::Table< gaia::ecs::QueryLookupKey, uint32_t >", "classrobin__hood_1_1detail_1_1Table.html", null ],
        [ "robin_hood::detail::Table< gaia::ecs::EntityLookupKey, gaia::cnt::darr< gaia::ecs::QueryHandle > >", "classrobin__hood_1_1detail_1_1Table.html", null ],
        [ "robin_hood::detail::Table< EntityLookupKey, uint32_t >", "classrobin__hood_1_1detail_1_1Table.html", null ],
        [ "robin_hood::detail::Table< const gaia::ecs::Archetype * >", "classrobin__hood_1_1detail_1_1Table.html", null ],
        [ "robin_hood::detail::Table< QueryId, QuerySerBuffer >", "classrobin__hood_1_1detail_1_1Table.html", null ],
        [ "robin_hood::detail::Table< EntityLookupKey, ArchetypeDArray >", "classrobin__hood_1_1detail_1_1Table.html", null ],
        [ "robin_hood::detail::Table< EntityLookupKey, cnt::set< EntityLookupKey > >", "classrobin__hood_1_1detail_1_1Table.html", null ],
        [ "robin_hood::detail::Table< ArchetypeLookupKey, Archetype * >", "classrobin__hood_1_1detail_1_1Table.html", null ],
        [ "robin_hood::detail::Table< ArchetypeIdLookupKey, Archetype * >", "classrobin__hood_1_1detail_1_1Table.html", null ],
        [ "robin_hood::detail::Table< gaia::core::StringLookupKey, gaia::ecs::Entity >", "classrobin__hood_1_1detail_1_1Table.html", null ],
        [ "robin_hood::detail::Table< gaia::ecs::ArchetypeLookupKey >", "classrobin__hood_1_1detail_1_1Table.html", null ],
        [ "robin_hood::detail::Table< gaia::ecs::EntityLookupKey >", "classrobin__hood_1_1detail_1_1Table.html", null ],
        [ "robin_hood::detail::Table< IsFlat, MaxLoadFactor100, Key, T, Hash, KeyEqual >", "classrobin__hood_1_1detail_1_1Table.html", null ]
      ] ]
    ] ],
    [ "robin_hood::hash< T, Enable >", "structrobin__hood_1_1hash.html", null ],
    [ "robin_hood::hash< Enum, typename std::enable_if< std::is_enum< Enum >::value >::type >", "structrobin__hood_1_1hash_3_01Enum_00_01typename_01std_1_1enable__if_3_01std_1_1is__enum_3_01Enu66d88786d8b4d7158b0da3f501596c68.html", null ],
    [ "robin_hood::hash< T * >", "structrobin__hood_1_1hash_3_01T_01_5_01_4.html", null ],
    [ "robin_hood::hash< T, typename std::enable_if< gaia::core::is_direct_hash_key_v< T > >::type >", "structrobin__hood_1_1hash_3_01T_00_01typename_01std_1_1enable__if_3_01gaia_1_1core_1_1is__directb90c969b64bee2ef071a5927f60384d3.html", null ],
    [ "gaia::ecs::vm::detail::IdCmpResult", "structgaia_1_1ecs_1_1vm_1_1detail_1_1IdCmpResult.html", null ],
    [ "gaia::cnt::ilist< TListItem, TItemHandle, TInternalStorage >", "structgaia_1_1cnt_1_1ilist.html", null ],
    [ "gaia::cnt::ilist< gaia::ecs::EntityContainer, gaia::ecs::Entity >", "structgaia_1_1cnt_1_1ilist.html", null ],
    [ "gaia::cnt::ilist< gaia::ecs::QueryInfo, gaia::ecs::QueryHandle >", "structgaia_1_1cnt_1_1ilist.html", null ],
    [ "gaia::cnt::ilist< gaia::mt::JobContainer, gaia::mt::JobHandle >", "structgaia_1_1cnt_1_1ilist.html", null ],
    [ "gaia::cnt::ilist_item_base", "structgaia_1_1cnt_1_1ilist__item__base.html", [
      [ "gaia::cnt::ilist_item", "structgaia_1_1cnt_1_1ilist__item.html", [
        [ "gaia::ecs::QueryInfo", "classgaia_1_1ecs_1_1QueryInfo.html", null ],
        [ "gaia::mt::JobContainer", "structgaia_1_1mt_1_1JobContainer.html", null ]
      ] ],
      [ "gaia::ecs::EntityContainer", "structgaia_1_1ecs_1_1EntityContainer.html", null ]
    ] ],
    [ "gaia::core::input_iterator_tag", "structgaia_1_1core_1_1input__iterator__tag.html", [
      [ "gaia::core::forward_iterator_tag", "structgaia_1_1core_1_1forward__iterator__tag.html", [
        [ "gaia::core::bidirectional_iterator_tag", "structgaia_1_1core_1_1bidirectional__iterator__tag.html", [
          [ "gaia::core::random_access_iterator_tag", "structgaia_1_1core_1_1random__access__iterator__tag.html", [
            [ "gaia::core::contiguous_iterator_tag", "structgaia_1_1core_1_1contiguous__iterator__tag.html", null ]
          ] ]
        ] ]
      ] ],
      [ "gaia::core::reverse_iterator_tag", "structgaia_1_1core_1_1reverse__iterator__tag.html", null ]
    ] ],
    [ "std::integral_constant", null, [
      [ "std::tuple_size< gaia::cnt::sarr< T, N > >", "structstd_1_1tuple__size_3_01gaia_1_1cnt_1_1sarr_3_01T_00_01N_01_4_01_4.html", null ],
      [ "std::tuple_size< gaia::cnt::sarr_ext< T, N > >", "structstd_1_1tuple__size_3_01gaia_1_1cnt_1_1sarr__ext_3_01T_00_01N_01_4_01_4.html", null ],
      [ "std::tuple_size< gaia::cnt::sarr_ext_soa< T, N > >", "structstd_1_1tuple__size_3_01gaia_1_1cnt_1_1sarr__ext__soa_3_01T_00_01N_01_4_01_4.html", null ],
      [ "std::tuple_size< gaia::cnt::sarr_soa< T, N > >", "structstd_1_1tuple__size_3_01gaia_1_1cnt_1_1sarr__soa_3_01T_00_01N_01_4_01_4.html", null ],
      [ "std::tuple_size< gaia::core::span< T, Extent > >", "structstd_1_1tuple__size_3_01gaia_1_1core_1_1span_3_01T_00_01Extent_01_4_01_4.html", null ]
    ] ],
    [ "gaia::ecs::Component::InternalData", "structgaia_1_1ecs_1_1Component_1_1InternalData.html", null ],
    [ "gaia::ecs::Entity::InternalData", "structgaia_1_1ecs_1_1Entity_1_1InternalData.html", null ],
    [ "gaia::ecs::Is_", "structgaia_1_1ecs_1_1Is__.html", null ],
    [ "gaia::core::detail::is_container< C, U >", "structgaia_1_1core_1_1detail_1_1is__container.html", null ],
    [ "gaia::core::is_greater< T >", "structgaia_1_1core_1_1is__greater.html", null ],
    [ "gaia::ecs::is_pair< T >", "structgaia_1_1ecs_1_1is__pair.html", null ],
    [ "gaia::core::is_smaller< T >", "structgaia_1_1core_1_1is__smaller.html", null ],
    [ "gaia::core::is_smaller_or_equal< T >", "structgaia_1_1core_1_1is__smaller__or__equal.html", null ],
    [ "robin_hood::is_transparent_tag", "structrobin__hood_1_1is__transparent__tag.html", null ],
    [ "gaia::ser::is_trivially_serializable< T >", "structgaia_1_1ser_1_1is__trivially__serializable.html", null ],
    [ "gaia::ser::ISerializer", "structgaia_1_1ser_1_1ISerializer.html", [
      [ "gaia::ecs::BinarySerializer", "classgaia_1_1ecs_1_1BinarySerializer.html", null ]
    ] ],
    [ "gaia::cnt::ilist_item::ItemData", "structgaia_1_1cnt_1_1ilist__item_1_1ItemData.html", null ],
    [ "gaia::core::detail::iterator_traits_base< typename, typename >", "structgaia_1_1core_1_1detail_1_1iterator__traits__base.html", null ],
    [ "gaia::core::detail::iterator_traits_base< It >", "structgaia_1_1core_1_1detail_1_1iterator__traits__base.html", [
      [ "gaia::core::detail::iterator_traits< It >", "structgaia_1_1core_1_1detail_1_1iterator__traits.html", null ]
    ] ],
    [ "gaia::core::detail::iterator_traits_base< It, std::void_t< typename It::iterator_category, typename It::value_type, typename It::difference_type, typename It::pointer, typename It::reference > >", "structgaia_1_1core_1_1detail_1_1iterator__traits__base_3_01It_00_01std_1_1void__t_3_01typename_0a642e18983b55d789445bd71d4933245.html", null ],
    [ "gaia::core::detail::iterator_traits_pointer_base< T, bool >", "structgaia_1_1core_1_1detail_1_1iterator__traits__pointer__base.html", [
      [ "gaia::core::detail::iterator_traits< T * >", "structgaia_1_1core_1_1detail_1_1iterator__traits_3_01T_01_5_01_4.html", null ]
    ] ],
    [ "gaia::core::detail::iterator_traits_pointer_base< T, false >", "structgaia_1_1core_1_1detail_1_1iterator__traits__pointer__base_3_01T_00_01false_01_4.html", null ],
    [ "gaia::mt::Job", "structgaia_1_1mt_1_1Job.html", null ],
    [ "gaia::mt::JobAllocCtx", "structgaia_1_1mt_1_1JobAllocCtx.html", null ],
    [ "gaia::mt::JobArgs", "structgaia_1_1mt_1_1JobArgs.html", null ],
    [ "gaia::mt::JobEdges", "structgaia_1_1mt_1_1JobEdges.html", null ],
    [ "gaia::mt::JobHandle", "structgaia_1_1mt_1_1JobHandle.html", null ],
    [ "gaia::mt::JobManager", "classgaia_1_1mt_1_1JobManager.html", null ],
    [ "gaia::mt::JobNull_t", "structgaia_1_1mt_1_1JobNull__t.html", null ],
    [ "gaia::mt::JobParallel", "structgaia_1_1mt_1_1JobParallel.html", null ],
    [ "KeyEqual", null, [
      [ "robin_hood::detail::WrapKeyEqual< KeyEqual >", "structrobin__hood_1_1detail_1_1WrapKeyEqual.html", [
        [ "robin_hood::detail::Table< EntityLookupKey, ArchetypeGraphEdge >", "classrobin__hood_1_1detail_1_1Table.html", null ],
        [ "robin_hood::detail::Table< detail::ComponentDescId, const gaia::ecs::ComponentCacheItem * >", "classrobin__hood_1_1detail_1_1Table.html", null ],
        [ "robin_hood::detail::Table< gaia::core::StringLookupKey, const gaia::ecs::ComponentCacheItem * >", "classrobin__hood_1_1detail_1_1Table.html", null ],
        [ "robin_hood::detail::Table< gaia::ecs::EntityLookupKey, const gaia::ecs::ComponentCacheItem * >", "classrobin__hood_1_1detail_1_1Table.html", null ],
        [ "robin_hood::detail::Table< gaia::ecs::EntityLookupKey, gaia::ecs::EntityContainer >", "classrobin__hood_1_1detail_1_1Table.html", null ],
        [ "robin_hood::detail::Table< gaia::ecs::QueryLookupKey, uint32_t >", "classrobin__hood_1_1detail_1_1Table.html", null ],
        [ "robin_hood::detail::Table< gaia::ecs::EntityLookupKey, gaia::cnt::darr< gaia::ecs::QueryHandle > >", "classrobin__hood_1_1detail_1_1Table.html", null ],
        [ "robin_hood::detail::Table< EntityLookupKey, uint32_t >", "classrobin__hood_1_1detail_1_1Table.html", null ],
        [ "robin_hood::detail::Table< const gaia::ecs::Archetype * >", "classrobin__hood_1_1detail_1_1Table.html", null ],
        [ "robin_hood::detail::Table< QueryId, QuerySerBuffer >", "classrobin__hood_1_1detail_1_1Table.html", null ],
        [ "robin_hood::detail::Table< EntityLookupKey, ArchetypeDArray >", "classrobin__hood_1_1detail_1_1Table.html", null ],
        [ "robin_hood::detail::Table< EntityLookupKey, cnt::set< EntityLookupKey > >", "classrobin__hood_1_1detail_1_1Table.html", null ],
        [ "robin_hood::detail::Table< ArchetypeLookupKey, Archetype * >", "classrobin__hood_1_1detail_1_1Table.html", null ],
        [ "robin_hood::detail::Table< ArchetypeIdLookupKey, Archetype * >", "classrobin__hood_1_1detail_1_1Table.html", null ],
        [ "robin_hood::detail::Table< gaia::core::StringLookupKey, gaia::ecs::Entity >", "classrobin__hood_1_1detail_1_1Table.html", null ],
        [ "robin_hood::detail::Table< gaia::ecs::ArchetypeLookupKey >", "classrobin__hood_1_1detail_1_1Table.html", null ],
        [ "robin_hood::detail::Table< gaia::ecs::EntityLookupKey >", "classrobin__hood_1_1detail_1_1Table.html", null ],
        [ "robin_hood::detail::Table< IsFlat, MaxLoadFactor100, Key, T, Hash, KeyEqual >", "classrobin__hood_1_1detail_1_1Table.html", null ]
      ] ]
    ] ],
    [ "gaia::ser::load_tag", "structgaia_1_1ser_1_1load__tag.html", null ],
    [ "gaia::core::lock_scope< T >", "structgaia_1_1core_1_1lock__scope.html", null ],
    [ "gaia::util::detail::LogBuffer", "structgaia_1_1util_1_1detail_1_1LogBuffer.html", null ],
    [ "gaia::util::detail::LogBuffer::LogRecord", "structgaia_1_1util_1_1detail_1_1LogBuffer_1_1LogRecord.html", null ],
    [ "gaia::ecs::vm::MatchingCtx", "structgaia_1_1ecs_1_1vm_1_1MatchingCtx.html", null ],
    [ "gaia::cnt::detail::mem_page< T, Allocator >", "classgaia_1_1cnt_1_1detail_1_1mem__page.html", null ],
    [ "gaia::cnt::detail::mem_page_data< T >", "structgaia_1_1cnt_1_1detail_1_1mem__page__data.html", null ],
    [ "gaia::cnt::detail::mem_page_iterator< T, Allocator, IsFwd >", "structgaia_1_1cnt_1_1detail_1_1mem__page__iterator.html", null ],
    [ "gaia::cnt::detail::mem_page_iterator_soa< T, Allocator, IsFwd >", "structgaia_1_1cnt_1_1detail_1_1mem__page__iterator__soa.html", null ],
    [ "gaia::core::detail::member_func_checker< Default, AlwaysVoid, Op, Args >", "structgaia_1_1core_1_1detail_1_1member__func__checker.html", null ],
    [ "gaia::core::detail::member_func_checker< Default, std::void_t< Op< Args... > >, Op, Args... >", "structgaia_1_1core_1_1detail_1_1member__func__checker_3_01Default_00_01std_1_1void__t_3_01Op_3_0222e17dad8904d328c48bb2ccd61015b.html", null ],
    [ "gaia::core::detail::member_func_none", "structgaia_1_1core_1_1detail_1_1member__func__none.html", null ],
    [ "gaia::mem::MemoryPageContainer< T, RequestedBlockSize >", "structgaia_1_1mem_1_1MemoryPageContainer.html", null ],
    [ "gaia::mem::MemoryPageHeader", "structgaia_1_1mem_1_1MemoryPageHeader.html", [
      [ "gaia::mem::MemoryPage< T, RequestedBlockSize >", "structgaia_1_1mem_1_1MemoryPage.html", null ]
    ] ],
    [ "gaia::mem::MemoryPageStats", "structgaia_1_1mem_1_1MemoryPageStats.html", null ],
    [ "robin_hood::detail::NodeAllocator< T, MinSize, MaxSize, IsFlat >", "structrobin__hood_1_1detail_1_1NodeAllocator.html", [
      [ "robin_hood::detail::Table< EntityLookupKey, ArchetypeGraphEdge >", "classrobin__hood_1_1detail_1_1Table.html", null ],
      [ "robin_hood::detail::Table< detail::ComponentDescId, const gaia::ecs::ComponentCacheItem * >", "classrobin__hood_1_1detail_1_1Table.html", null ],
      [ "robin_hood::detail::Table< gaia::core::StringLookupKey, const gaia::ecs::ComponentCacheItem * >", "classrobin__hood_1_1detail_1_1Table.html", null ],
      [ "robin_hood::detail::Table< gaia::ecs::EntityLookupKey, const gaia::ecs::ComponentCacheItem * >", "classrobin__hood_1_1detail_1_1Table.html", null ],
      [ "robin_hood::detail::Table< gaia::ecs::EntityLookupKey, gaia::ecs::EntityContainer >", "classrobin__hood_1_1detail_1_1Table.html", null ],
      [ "robin_hood::detail::Table< gaia::ecs::QueryLookupKey, uint32_t >", "classrobin__hood_1_1detail_1_1Table.html", null ],
      [ "robin_hood::detail::Table< gaia::ecs::EntityLookupKey, gaia::cnt::darr< gaia::ecs::QueryHandle > >", "classrobin__hood_1_1detail_1_1Table.html", null ],
      [ "robin_hood::detail::Table< EntityLookupKey, uint32_t >", "classrobin__hood_1_1detail_1_1Table.html", null ],
      [ "robin_hood::detail::Table< const gaia::ecs::Archetype * >", "classrobin__hood_1_1detail_1_1Table.html", null ],
      [ "robin_hood::detail::Table< QueryId, QuerySerBuffer >", "classrobin__hood_1_1detail_1_1Table.html", null ],
      [ "robin_hood::detail::Table< EntityLookupKey, ArchetypeDArray >", "classrobin__hood_1_1detail_1_1Table.html", null ],
      [ "robin_hood::detail::Table< EntityLookupKey, cnt::set< EntityLookupKey > >", "classrobin__hood_1_1detail_1_1Table.html", null ],
      [ "robin_hood::detail::Table< ArchetypeLookupKey, Archetype * >", "classrobin__hood_1_1detail_1_1Table.html", null ],
      [ "robin_hood::detail::Table< ArchetypeIdLookupKey, Archetype * >", "classrobin__hood_1_1detail_1_1Table.html", null ],
      [ "robin_hood::detail::Table< gaia::core::StringLookupKey, gaia::ecs::Entity >", "classrobin__hood_1_1detail_1_1Table.html", null ],
      [ "robin_hood::detail::Table< gaia::ecs::ArchetypeLookupKey >", "classrobin__hood_1_1detail_1_1Table.html", null ],
      [ "robin_hood::detail::Table< gaia::ecs::EntityLookupKey >", "classrobin__hood_1_1detail_1_1Table.html", null ],
      [ "robin_hood::detail::Table< IsFlat, MaxLoadFactor100, Key, T, Hash, KeyEqual >", "classrobin__hood_1_1detail_1_1Table.html", null ]
    ] ],
    [ "robin_hood::detail::NodeAllocator< std::conditional< std::is_void< T >::value, Key, robin_hood::pair< std::conditional< IsFlat, Key, Key const >::type, T > >::type, 4, 16384, IsFlat >", "structrobin__hood_1_1detail_1_1NodeAllocator.html", null ],
    [ "robin_hood::detail::NodeAllocator< T, MinSize, MaxSize, true >", "structrobin__hood_1_1detail_1_1NodeAllocator_3_01T_00_01MinSize_00_01MaxSize_00_01true_01_4.html", null ],
    [ "robin_hood::detail::swappable::nothrow< T >", "structrobin__hood_1_1detail_1_1swappable_1_1nothrow.html", null ],
    [ "gaia::ecs::Observer_", "structgaia_1_1ecs_1_1Observer__.html", null ],
    [ "gaia::ecs::OnDelete_", "structgaia_1_1ecs_1_1OnDelete__.html", null ],
    [ "gaia::ecs::OnDeleteTarget_", "structgaia_1_1ecs_1_1OnDeleteTarget__.html", null ],
    [ "gaia::ecs::vm::detail::OpAll", "structgaia_1_1ecs_1_1vm_1_1detail_1_1OpAll.html", null ],
    [ "gaia::ecs::vm::detail::OpAny", "structgaia_1_1ecs_1_1vm_1_1detail_1_1OpAny.html", null ],
    [ "gaia::ecs::vm::detail::OpcodeAll_Complex", "structgaia_1_1ecs_1_1vm_1_1detail_1_1OpcodeAll__Complex.html", null ],
    [ "gaia::ecs::vm::detail::OpcodeAll_Simple", "structgaia_1_1ecs_1_1vm_1_1detail_1_1OpcodeAll__Simple.html", null ],
    [ "gaia::ecs::vm::detail::OpcodeAll_Wildcard", "structgaia_1_1ecs_1_1vm_1_1detail_1_1OpcodeAll__Wildcard.html", null ],
    [ "gaia::ecs::vm::detail::OpcodeAny_NoAll", "structgaia_1_1ecs_1_1vm_1_1detail_1_1OpcodeAny__NoAll.html", null ],
    [ "gaia::ecs::vm::detail::OpcodeAny_WithAll", "structgaia_1_1ecs_1_1vm_1_1detail_1_1OpcodeAny__WithAll.html", null ],
    [ "gaia::ecs::vm::detail::OpcodeNot_Complex", "structgaia_1_1ecs_1_1vm_1_1detail_1_1OpcodeNot__Complex.html", null ],
    [ "gaia::ecs::vm::detail::OpcodeNot_Simple", "structgaia_1_1ecs_1_1vm_1_1detail_1_1OpcodeNot__Simple.html", null ],
    [ "gaia::ecs::vm::detail::OpcodeNot_Wildcard", "structgaia_1_1ecs_1_1vm_1_1detail_1_1OpcodeNot__Wildcard.html", null ],
    [ "gaia::ecs::vm::detail::OpNo", "structgaia_1_1ecs_1_1vm_1_1detail_1_1OpNo.html", null ],
    [ "gaia::core::output_iterator_tag", "structgaia_1_1core_1_1output__iterator__tag.html", null ],
    [ "gaia::cnt::page_iterator< T, Allocator, IsFwd >", "structgaia_1_1cnt_1_1page__iterator.html", null ],
    [ "gaia::cnt::page_iterator_soa< T, Allocator, IsFwd >", "structgaia_1_1cnt_1_1page__iterator__soa.html", null ],
    [ "gaia::cnt::page_storage< T >", "classgaia_1_1cnt_1_1page__storage.html", null ],
    [ "gaia::mem::detail::PagedAllocatorImpl< T, RequestedBlockSize >", "classgaia_1_1mem_1_1detail_1_1PagedAllocatorImpl.html", null ],
    [ "gaia::cnt::detail::mem_page_data< T >::PageHeader", "structgaia_1_1cnt_1_1detail_1_1mem__page__data_1_1PageHeader.html", null ],
    [ "robin_hood::pair< T1, T2 >", "structrobin__hood_1_1pair.html", null ],
    [ "gaia::ecs::detail::pair_base", "structgaia_1_1ecs_1_1detail_1_1pair__base.html", [
      [ "gaia::ecs::pair< Rel, Tgt >", "classgaia_1_1ecs_1_1pair.html", null ],
      [ "gaia::ecs::pair< Entity, Entity >", "classgaia_1_1ecs_1_1pair_3_01Entity_00_01Entity_01_4.html", null ]
    ] ],
    [ "gaia::ecs::Archetype::Properties", "structgaia_1_1ecs_1_1Archetype_1_1Properties.html", null ],
    [ "gaia::ecs::query_sort_cond", "structgaia_1_1ecs_1_1query__sort__cond.html", null ],
    [ "gaia::ecs::QueryCache", "classgaia_1_1ecs_1_1QueryCache.html", null ],
    [ "gaia::ecs::detail::QueryCmd_AddFilter", "structgaia_1_1ecs_1_1detail_1_1QueryCmd__AddFilter.html", null ],
    [ "gaia::ecs::detail::QueryCmd_AddItem", "structgaia_1_1ecs_1_1detail_1_1QueryCmd__AddItem.html", null ],
    [ "gaia::ecs::detail::QueryCmd_GroupBy", "structgaia_1_1ecs_1_1detail_1_1QueryCmd__GroupBy.html", null ],
    [ "gaia::ecs::detail::QueryCmd_SetGroupId", "structgaia_1_1ecs_1_1detail_1_1QueryCmd__SetGroupId.html", null ],
    [ "gaia::ecs::detail::QueryCmd_SortBy", "structgaia_1_1ecs_1_1detail_1_1QueryCmd__SortBy.html", null ],
    [ "gaia::ecs::vm::detail::QueryCompileCtx", "structgaia_1_1ecs_1_1vm_1_1detail_1_1QueryCompileCtx.html", null ],
    [ "gaia::ecs::QueryCtx", "structgaia_1_1ecs_1_1QueryCtx.html", null ],
    [ "gaia::ecs::QueryHandle", "structgaia_1_1ecs_1_1QueryHandle.html", null ],
    [ "gaia::ecs::QueryHandleLookupKey", "structgaia_1_1ecs_1_1QueryHandleLookupKey.html", null ],
    [ "gaia::ecs::QueryIdentity", "structgaia_1_1ecs_1_1QueryIdentity.html", null ],
    [ "gaia::ecs::detail::QueryImpl< UseCaching >", "classgaia_1_1ecs_1_1detail_1_1QueryImpl.html", null ],
    [ "gaia::ecs::detail::QueryImpl< true >", "classgaia_1_1ecs_1_1detail_1_1QueryImpl.html", null ],
    [ "gaia::ecs::detail::QueryImplStorage< Cached >", "structgaia_1_1ecs_1_1detail_1_1QueryImplStorage.html", null ],
    [ "gaia::ecs::detail::QueryImplStorage< false >", "structgaia_1_1ecs_1_1detail_1_1QueryImplStorage_3_01false_01_4.html", null ],
    [ "gaia::ecs::detail::QueryImplStorage< true >", "structgaia_1_1ecs_1_1detail_1_1QueryImplStorage.html", null ],
    [ "gaia::ecs::detail::QueryImplStorage< UseCaching >", "structgaia_1_1ecs_1_1detail_1_1QueryImplStorage.html", null ],
    [ "gaia::ecs::QueryInfoCreationCtx", "structgaia_1_1ecs_1_1QueryInfoCreationCtx.html", null ],
    [ "gaia::ecs::QueryInput", "structgaia_1_1ecs_1_1QueryInput.html", null ],
    [ "gaia::ecs::QueryLookupKey", "classgaia_1_1ecs_1_1QueryLookupKey.html", null ],
    [ "gaia::ecs::QueryTerm", "structgaia_1_1ecs_1_1QueryTerm.html", null ],
    [ "gaia::mem::detail::raw_data_holder< Size, Alignment >", "structgaia_1_1mem_1_1detail_1_1raw__data__holder.html", null ],
    [ "gaia::mem::detail::raw_data_holder< 1024, 16 >", "structgaia_1_1mem_1_1detail_1_1raw__data__holder.html", null ],
    [ "gaia::mem::detail::raw_data_holder< Entity, allocated_bytes >", "structgaia_1_1mem_1_1detail_1_1raw__data__holder.html", null ],
    [ "gaia::mem::detail::raw_data_holder< gaia::ecs::Entity, allocated_bytes >", "structgaia_1_1mem_1_1detail_1_1raw__data__holder.html", null ],
    [ "gaia::mem::detail::raw_data_holder< gaia::ecs::QueryTerm, allocated_bytes >", "structgaia_1_1mem_1_1detail_1_1raw__data__holder.html", null ],
    [ "gaia::mem::detail::raw_data_holder< gaia::mt::ThreadCtx, allocated_bytes >", "structgaia_1_1mem_1_1detail_1_1raw__data__holder.html", null ],
    [ "gaia::mem::detail::raw_data_holder< GAIA_THREAD, allocated_bytes >", "structgaia_1_1mem_1_1detail_1_1raw__data__holder.html", null ],
    [ "gaia::mem::detail::raw_data_holder< Op, allocated_bytes >", "structgaia_1_1mem_1_1detail_1_1raw__data__holder.html", null ],
    [ "gaia::mem::detail::raw_data_holder< Size, 0 >", "structgaia_1_1mem_1_1detail_1_1raw__data__holder_3_01Size_00_010_01_4.html", null ],
    [ "gaia::mem::detail::raw_data_holder< T, allocated_bytes >", "structgaia_1_1mem_1_1detail_1_1raw__data__holder.html", null ],
    [ "gaia::mem::detail::raw_data_holder< T, AllocatedBytes >", "structgaia_1_1mem_1_1detail_1_1raw__data__holder.html", null ],
    [ "gaia::mem::detail::raw_data_holder< uint8_t, allocated_bytes >", "structgaia_1_1mem_1_1detail_1_1raw__data__holder.html", null ],
    [ "gaia::core::detail::rem_rp< T >", "structgaia_1_1core_1_1detail_1_1rem__rp.html", null ],
    [ "gaia::ecs::Remove_", "structgaia_1_1ecs_1_1Remove__.html", null ],
    [ "gaia::ecs::Requires_", "structgaia_1_1ecs_1_1Requires__.html", null ],
    [ "gaia::cnt::sarr< T, N >", "classgaia_1_1cnt_1_1sarr.html", null ],
    [ "gaia::cnt::sarr< Entity, MAX_ITEMS_IN_QUERY >", "classgaia_1_1cnt_1_1sarr.html", null ],
    [ "gaia::cnt::sarr< gaia::ecs::QueryTerm, MAX_ITEMS_IN_QUERY >", "classgaia_1_1cnt_1_1sarr.html", null ],
    [ "gaia::cnt::sarr< uint8_t, BlockArrayBytes >", "classgaia_1_1cnt_1_1sarr.html", null ],
    [ "gaia::cnt::sarr< uint8_t, MAX_ITEMS_IN_QUERY >", "classgaia_1_1cnt_1_1sarr.html", null ],
    [ "gaia::cnt::sarr_ext< T, N >", "classgaia_1_1cnt_1_1sarr__ext.html", null ],
    [ "gaia::cnt::sarr_ext< gaia::ecs::Entity, MAX_ITEMS_IN_QUERY >", "classgaia_1_1cnt_1_1sarr__ext.html", null ],
    [ "gaia::cnt::sarr_ext< gaia::mt::ThreadCtx, MaxWorkers >", "classgaia_1_1cnt_1_1sarr__ext.html", null ],
    [ "gaia::cnt::sarr_ext< GAIA_THREAD, MaxWorkers >", "classgaia_1_1cnt_1_1sarr__ext.html", null ],
    [ "gaia::cnt::sarr_ext_soa< T, N >", "classgaia_1_1cnt_1_1sarr__ext__soa.html", null ],
    [ "gaia::cnt::sarr_ext_soa_iterator< T >", "structgaia_1_1cnt_1_1sarr__ext__soa__iterator.html", null ],
    [ "gaia::cnt::sarr_soa< T, N >", "classgaia_1_1cnt_1_1sarr__soa.html", null ],
    [ "gaia::cnt::sarr_soa_iterator< T >", "structgaia_1_1cnt_1_1sarr__soa__iterator.html", null ],
    [ "gaia::ser::save_tag", "structgaia_1_1ser_1_1save__tag.html", null ],
    [ "gaia::ecs::ComponentCacheItem::SchemaField", "structgaia_1_1ecs_1_1ComponentCacheItem_1_1SchemaField.html", null ],
    [ "gaia::mt::Semaphore", "classgaia_1_1mt_1_1Semaphore.html", null ],
    [ "gaia::mt::SemaphoreFast", "classgaia_1_1mt_1_1SemaphoreFast.html", null ],
    [ "gaia::ser::detail::ser_buffer_binary_impl< DataContainer >", "classgaia_1_1ser_1_1detail_1_1ser__buffer__binary__impl.html", null ],
    [ "gaia::ser::detail::ser_buffer_binary_impl< ser_buffer_binary_storage >", "classgaia_1_1ser_1_1detail_1_1ser__buffer__binary__impl.html", [
      [ "gaia::ser::ser_buffer_binary", "classgaia_1_1ser_1_1ser__buffer__binary.html", null ]
    ] ],
    [ "gaia::ser::detail::ser_buffer_binary_impl< ser_buffer_binary_storage_dyn >", "classgaia_1_1ser_1_1detail_1_1ser__buffer__binary__impl.html", [
      [ "gaia::ser::ser_buffer_binary_dyn", "classgaia_1_1ser_1_1ser__buffer__binary__dyn.html", null ]
    ] ],
    [ "gaia::util::signal< Function >", "classgaia_1_1util_1_1signal.html", null ],
    [ "gaia::util::signal< Ret(Args...)>", "classgaia_1_1util_1_1signal_3_01Ret_07Args_8_8_8_08_4.html", null ],
    [ "gaia::util::sink< Function >", "classgaia_1_1util_1_1sink.html", null ],
    [ "gaia::util::sink< Ret(Args...)>", "classgaia_1_1util_1_1sink_3_01Ret_07Args_8_8_8_08_4.html", null ],
    [ "gaia::core::span< T, Extent >", "classgaia_1_1core_1_1span.html", null ],
    [ "gaia::core::span< const Entity >", "classgaia_1_1core_1_1span.html", null ],
    [ "gaia::core::span< const gaia::ecs::Archetype * >", "classgaia_1_1core_1_1span.html", null ],
    [ "gaia::core::span< const uint8_t >", "classgaia_1_1core_1_1span.html", null ],
    [ "gaia::core::span< uint8_t >", "classgaia_1_1core_1_1span.html", null ],
    [ "gaia::core::detail::span_storage< T, Extent >", "structgaia_1_1core_1_1detail_1_1span__storage.html", null ],
    [ "gaia::core::detail::span_storage< const Entity, Extent >", "structgaia_1_1core_1_1detail_1_1span__storage.html", null ],
    [ "gaia::core::detail::span_storage< const gaia::ecs::Archetype *, Extent >", "structgaia_1_1core_1_1detail_1_1span__storage.html", null ],
    [ "gaia::core::detail::span_storage< const uint8_t, Extent >", "structgaia_1_1core_1_1detail_1_1span__storage.html", null ],
    [ "gaia::core::detail::span_storage< T, DynamicSpanExtent >", "structgaia_1_1core_1_1detail_1_1span__storage_3_01T_00_01DynamicSpanExtent_01_4.html", null ],
    [ "gaia::core::detail::span_storage< uint8_t, Extent >", "structgaia_1_1core_1_1detail_1_1span__storage.html", null ],
    [ "gaia::cnt::sparse_iterator< T, PageCapacity, Allocator, typename >", "structgaia_1_1cnt_1_1sparse__iterator.html", null ],
    [ "gaia::cnt::sparse_iterator< T, PageCapacity, Allocator, std::enable_if_t< std::is_empty_v< T > > >", "structgaia_1_1cnt_1_1sparse__iterator_3_01T_00_01PageCapacity_00_01Allocator_00_01std_1_1enable_a04ec75195309ee4c5d26ce99aa078a9.html", null ],
    [ "gaia::cnt::detail::sparse_page< T, PageCapacity, Allocator, typename >", "classgaia_1_1cnt_1_1detail_1_1sparse__page.html", null ],
    [ "gaia::cnt::detail::sparse_page< T, PageCapacity, Allocator, std::enable_if_t< std::is_empty_v< T > > >", "classgaia_1_1cnt_1_1detail_1_1sparse__page_3_01T_00_01PageCapacity_00_01Allocator_00_01std_1_1en6e95dfa070ac2a122b9692da81356b71.html", null ],
    [ "gaia::cnt::sparse_storage< T, PageCapacity, Allocator, typename >", "classgaia_1_1cnt_1_1sparse__storage.html", null ],
    [ "gaia::cnt::sparse_storage< T, PageCapacity, Allocator, std::enable_if_t< std::is_empty_v< T > > >", "classgaia_1_1cnt_1_1sparse__storage_3_01T_00_01PageCapacity_00_01Allocator_00_01std_1_1enable__ie087b7e8314b32ca924843d3e0f50e85.html", null ],
    [ "gaia::mt::SpinLock", "classgaia_1_1mt_1_1SpinLock.html", null ],
    [ "gaia::cnt::sringbuffer< T, N >", "classgaia_1_1cnt_1_1sringbuffer.html", null ],
    [ "gaia::cnt::sringbuffer_iterator< T, N >", "structgaia_1_1cnt_1_1sringbuffer__iterator.html", null ],
    [ "gaia::mem::StackAllocator< CapacityInBytes >", "classgaia_1_1mem_1_1StackAllocator.html", null ],
    [ "gaia::ecs::detail::storage_type< typename, typename >", "structgaia_1_1ecs_1_1detail_1_1storage__type.html", null ],
    [ "gaia::ecs::detail::storage_type< T, std::void_t< decltype(T::gaia_Storage_Type)> >", "structgaia_1_1ecs_1_1detail_1_1storage__type_3_01T_00_01std_1_1void__t_3_01decltype_07T_1_1gaia__Storage__Type_08_4_01_4.html", null ],
    [ "gaia::core::StringLookupKey< MaxLen >", "structgaia_1_1core_1_1StringLookupKey.html", null ],
    [ "gaia::core::StringLookupKey< 256 >", "structgaia_1_1core_1_1StringLookupKey.html", null ],
    [ "gaia::core::StringLookupKey< 512 >", "structgaia_1_1core_1_1StringLookupKey.html", null ],
    [ "T", null, [
      [ "robin_hood::detail::WrapHash< T >", "structrobin__hood_1_1detail_1_1WrapHash.html", null ],
      [ "robin_hood::detail::WrapKeyEqual< T >", "structrobin__hood_1_1detail_1_1WrapKeyEqual.html", null ]
    ] ],
    [ "gaia::mt::ThreadCtx", "structgaia_1_1mt_1_1ThreadCtx.html", null ],
    [ "gaia::mt::ThreadPool", "classgaia_1_1mt_1_1ThreadPool.html", null ],
    [ "gaia::cnt::to_page_storage_id< T >", "structgaia_1_1cnt_1_1to__page__storage__id.html", null ],
    [ "gaia::cnt::to_page_storage_id< ecs::EntityContainer >", "structgaia_1_1cnt_1_1to__page__storage__id_3_01ecs_1_1EntityContainer_01_4.html", null ],
    [ "gaia::cnt::to_sparse_id< T >", "structgaia_1_1cnt_1_1to__sparse__id.html", null ],
    [ "gaia::cnt::to_sparse_id< ecs::Entity >", "structgaia_1_1cnt_1_1to__sparse__id_3_01ecs_1_1Entity_01_4.html", null ],
    [ "gaia::ecs::Traversable_", "structgaia_1_1ecs_1_1Traversable__.html", null ],
    [ "std::true_type", null, [
      [ "gaia::core::detail::is_complete< T, decltype(sizeof(T))>", "structgaia_1_1core_1_1detail_1_1is__complete_3_01T_00_01decltype_07sizeof_07T_08_08_4.html", null ],
      [ "gaia::core::detail::is_container_element_kind_compatible< T, E, typename std::enable_if< !std::is_same< typename std::remove_cv< decltype(detail::data(std::declval< T >()))>::type, void >::value &&std::is_convertible< typename std::remove_pointer_t< decltype(detail::data(std::declval< T >()))>(*)[], E(*)[]>::value >::type >", "structgaia_1_1core_1_1detail_1_1is__container__element__kind__compatible_3_01T_00_01E_00_01typen25493d4f5b646d1ff43bb65fcbf4e827.html", null ],
      [ "gaia::core::detail::is_direct_hash_key< T, std::void_t< decltype(T::IsDirectHashKey)> >", "structgaia_1_1core_1_1detail_1_1is__direct__hash__key_3_01T_00_01std_1_1void__t_3_01decltype_07T_1_1IsDirectHashKey_08_4_01_4.html", null ],
      [ "gaia::core::detail::is_span< span< T, S > >", "structgaia_1_1core_1_1detail_1_1is__span_3_01span_3_01T_00_01S_01_4_01_4.html", null ],
      [ "gaia::core::detail::is_std_array< gaia::cnt::sarray< T, N > >", "structgaia_1_1core_1_1detail_1_1is__std__array_3_01gaia_1_1cnt_1_1sarray_3_01T_00_01N_01_4_01_4.html", null ],
      [ "gaia::core::has_data_size< T, std::void_t< decltype(detail::data(std::declval< T >())), decltype(detail::size(std::declval< T >())) > >", "structgaia_1_1core_1_1has__data__size_3_01T_00_01std_1_1void__t_3_01decltype_07detail_1_1data_0731442a81cf4e1da91ee338fd93279e3c.html", null ],
      [ "gaia::core::has_size_begin_end< T, std::void_t< decltype(std::declval< T >().begin()), decltype(std::declval< T >().end()), decltype(detail::size(std::declval< T >())) > >", "structgaia_1_1core_1_1has__size__begin__end_3_01T_00_01std_1_1void__t_3_01decltype_07std_1_1decled3338d74af8cc0bacdf33bd2a865cfb.html", null ],
      [ "gaia::detail::is_reference_wrapper< std::reference_wrapper< U > >", "structgaia_1_1detail_1_1is__reference__wrapper_3_01std_1_1reference__wrapper_3_01U_01_4_01_4.html", null ],
      [ "gaia::ecs::detail::has_entity_kind< T, std::void_t< decltype(T::Kind)> >", "structgaia_1_1ecs_1_1detail_1_1has__entity__kind_3_01T_00_01std_1_1void__t_3_01decltype_07T_1_1Kind_08_4_01_4.html", null ],
      [ "gaia::ecs::detail::is_gen_component< typename, typename >", "structgaia_1_1ecs_1_1detail_1_1is__gen__component.html", null ],
      [ "robin_hood::detail::has_hash< T, std::void_t< decltype(T::hash)> >", "structrobin__hood_1_1detail_1_1has__hash_3_01T_00_01std_1_1void__t_3_01decltype_07T_1_1hash_08_4_01_4.html", null ],
      [ "robin_hood::detail::has_is_transparent< T, std::void_t< decltype(T::is_transparent)> >", "structrobin__hood_1_1detail_1_1has__is__transparent_3_01T_00_01std_1_1void__t_3_01decltype_07T_1_1is__transparent_08_4_01_4.html", null ]
    ] ],
    [ "std::tuple_element< I, gaia::cnt::sarr< T, N > >", "structstd_1_1tuple__element_3_01I_00_01gaia_1_1cnt_1_1sarr_3_01T_00_01N_01_4_01_4.html", null ],
    [ "std::tuple_element< I, gaia::cnt::sarr_ext< T, N > >", "structstd_1_1tuple__element_3_01I_00_01gaia_1_1cnt_1_1sarr__ext_3_01T_00_01N_01_4_01_4.html", null ],
    [ "std::tuple_element< I, gaia::cnt::sarr_ext_soa< T, N > >", "structstd_1_1tuple__element_3_01I_00_01gaia_1_1cnt_1_1sarr__ext__soa_3_01T_00_01N_01_4_01_4.html", null ],
    [ "std::tuple_element< I, gaia::cnt::sarr_soa< T, N > >", "structstd_1_1tuple__element_3_01I_00_01gaia_1_1cnt_1_1sarr__soa_3_01T_00_01N_01_4_01_4.html", null ],
    [ "std::tuple_element< I, gaia::core::span< T, Extent > >", "structstd_1_1tuple__element_3_01I_00_01gaia_1_1core_1_1span_3_01T_00_01Extent_01_4_01_4.html", null ],
    [ "gaia::meta::type_group<... >", "classgaia_1_1meta_1_1type__group.html", null ],
    [ "gaia::core::detail::type_identity< T >", "structgaia_1_1core_1_1detail_1_1type__identity.html", [
      [ "gaia::core::unique< T, Ts >", "structgaia_1_1core_1_1unique.html", null ]
    ] ],
    [ "gaia::meta::type_info", "structgaia_1_1meta_1_1type__info.html", null ],
    [ "gaia::core::type_list< Type >", "structgaia_1_1core_1_1type__list.html", null ],
    [ "gaia::core::type_list_concat< TypesA, TypesB >", "structgaia_1_1core_1_1type__list__concat.html", null ],
    [ "gaia::core::type_list_concat< type_list< TypesA... >, type_list< TypesB... > >", "structgaia_1_1core_1_1type__list__concat_3_01type__list_3_01TypesA_8_8_8_01_4_00_01type__list_3_01TypesB_8_8_8_01_4_01_4.html", null ],
    [ "gaia::mem::unaligned_ref< T >", "classgaia_1_1mem_1_1unaligned__ref.html", null ],
    [ "gaia::ecs::uni< T >", "structgaia_1_1ecs_1_1uni.html", null ],
    [ "gaia::ecs::vm::VirtualMachine", "classgaia_1_1ecs_1_1vm_1_1VirtualMachine.html", null ],
    [ "gaia::ecs::World", "classgaia_1_1ecs_1_1World.html", null ],
    [ "gaia::core::zero_t", "structgaia_1_1core_1_1zero__t.html", null ]
];