@echo off
:: make_single_header.bat
:: Generates single_include\gaia.h from include\gaia.h.
::
:: Uses a pure batch include-walker: only #include directives that resolve to a
:: file under include\ are inlined. Everything else — system headers, external
:: dependencies, preprocessor definitions, conditionals — passes through verbatim.
::
:: The output is then formatted with clang-format using the project's
:: .clang-format config (auto-discovered via --style=file).
::
:: Usage:
::   make_single_header.bat [clang-format-executable]
::
:: Examples:
::   make_single_header.bat                :: auto-detects clang-format on PATH
::   make_single_header.bat clang-format-17

setlocal enabledelayedexpansion

set "REPO_ROOT=%~dp0"
if "%REPO_ROOT:~-1%"=="\" set "REPO_ROOT=%REPO_ROOT:~0,-1%"

set "INPUT=%REPO_ROOT%\include\gaia.h"
set "OUTPUT=%REPO_ROOT%\single_include\gaia.h"
set "INCLUDE_DIR=%REPO_ROOT%\include"
set "CLANG_FORMAT="

set "VISITED_FILE=%TEMP%\gaia_amalg_visited_%RANDOM%.tmp"

:: ============================================================================
:: Resolve clang-format
:: ============================================================================
set "ARG=%~1"

if not "%ARG%"=="" (
    where "%ARG%" >nul 2>&1
    if errorlevel 1 ( echo ERROR: '%ARG%' not found on PATH. 1>&2 & goto :error )
    set "CLANG_FORMAT=%ARG%"
    goto :resolve_done
)

for %%F in (clang-format clang-format-19 clang-format-18 clang-format-17) do (
    where %%F >nul 2>&1
    if not errorlevel 1 (
        set "CLANG_FORMAT=%%F"
        goto :resolve_done
    )
)
echo ERROR: clang-format not found. Install clang-format and make sure it is on PATH. 1>&2
goto :error

:resolve_done
echo Input        : %INPUT%
echo Output       : %OUTPUT%
echo clang-format : %CLANG_FORMAT%

:: ============================================================================
:: Run the include-walker
:: ============================================================================
if not exist "%REPO_ROOT%\single_include" mkdir "%REPO_ROOT%\single_include"
if exist "%OUTPUT%" del /f /q "%OUTPUT%"
if exist "%VISITED_FILE%" del /f /q "%VISITED_FILE%"

(
    echo // Amalgamated single-header build of gaia.h
    echo // Generated by make_single_header.bat -- do not edit manually.
    echo #pragma once
    echo.
) > "%OUTPUT%"

call :walker "%INPUT%"
if errorlevel 1 goto :error

:: ============================================================================
:: Format output with clang-format
:: --style=file auto-discovers .clang-format searching up from OUTPUT's directory
:: ============================================================================
echo Formatting   : %OUTPUT%
"%CLANG_FORMAT%" -i --style=file "%OUTPUT%"
if errorlevel 1 ( echo ERROR: clang-format failed. 1>&2 & goto :error )
goto :done

:: ============================================================================
:: :walker <file>
:: Appends the processed content of <file> to OUTPUT.
::
:: Rules:
::   - #include "..." or #include <...> resolving under INCLUDE_DIR -> inline
::   - Everything else passes through verbatim (#define, #if, system headers, etc.)
::   - #pragma once stripped from inlined files
::   - Already-visited files skipped (honours #pragma once semantics)
:: ============================================================================
:walker
setlocal enabledelayedexpansion

set "FILE=%~f1"
set "FILE_DIR=%~dp1"
if "%FILE_DIR:~-1%"=="\" set "FILE_DIR=%FILE_DIR:~0,-1%"

:: Check visited
if exist "%VISITED_FILE%" (
    findstr /i /x /c:"%FILE%" "%VISITED_FILE%" >nul 2>&1
    if not errorlevel 1 ( endlocal & exit /b 0 )
)
echo %FILE%>> "%VISITED_FILE%"

for /f "usebackq delims=" %%L in ("%FILE%") do (
    set "LINE=%%L"

    :: Strip #pragma once
    set "STRIPPED=!LINE: =!"
    set "STRIPPED=!STRIPPED:	=!"
    echo !STRIPPED! | findstr /r /c:"^#pragma once" >nul 2>&1
    if not errorlevel 1 goto :walker_next_line

    :: Check for a #include directive
    echo !LINE! | findstr /r /c:'#.*include.*[\"<][^\">][^\">]*[\">]' >nul 2>&1
    if errorlevel 1 (
        :: Not an include — emit verbatim
        echo !LINE!>> "%OUTPUT%"
        goto :walker_next_line
    )

    :: Extract the delimiter (first " or <) and the include path
    set "INC=!LINE!"
    set "DELIM="
    echo !LINE! | findstr /r /c:'#.*include.*<' >nul 2>&1
    if not errorlevel 1 set "DELIM=<"
    echo !LINE! | findstr /r /c:'#.*include.*\"' >nul 2>&1
    if not errorlevel 1 if "!DELIM!"=="" set "DELIM=\""

    :: Angle-bracket includes (<...>) are always system/external — never inline.
    if "!DELIM!"=="<" (
        echo !LINE!>> "%OUTPUT%"
        goto :walker_next_line
    )

    :: Quoted includes ("...") — extract path and attempt to resolve inside INCLUDE_DIR
    for /f "tokens=2 delims=\"" %%P in ("!LINE!") do set "INC=%%P"
    for /f "tokens=* delims= " %%T in ("!INC!") do set "INC=%%T"

    if "!INC!"=="" (
        echo !LINE!>> "%OUTPUT%"
        goto :walker_next_line
    )

    :: Try to resolve: relative to current file first, then against INCLUDE_DIR
    set "RESOLVED="

    if exist "!FILE_DIR!\!INC!" (
        for %%A in ("!FILE_DIR!\!INC!") do set "CANDIDATE=%%~fA"
        echo !CANDIDATE! | findstr /i /b /c:"%INCLUDE_DIR%" >nul 2>&1
        if not errorlevel 1 set "RESOLVED=!CANDIDATE!"
    )

    if "!RESOLVED!"=="" (
        if exist "%INCLUDE_DIR%\!INC!" (
            for %%A in ("%INCLUDE_DIR%\!INC!") do set "RESOLVED=%%~fA"
        )
    )

    :: 3. Recursive search under INCLUDE_DIR by basename.
    ::    Catches cases where a header is included by filename only (e.g.
    ::    "version.h") but lives at a subdirectory path inside INCLUDE_DIR.
    if "!RESOLVED!"=="" (
        for /f "tokens=*" %%F in ('dir /s /b "%INCLUDE_DIR%\!INC!" 2^>nul') do (
            if "!RESOLVED!"=="" set "RESOLVED=%%~fF"
        )
    )

    if "!RESOLVED!"=="" (
        :: External / system header — keep verbatim
        echo !LINE!>> "%OUTPUT%"
    ) else (
        :: Internal header — recurse
        call :walker "!RESOLVED!"
    )

    :walker_next_line
)

endlocal & exit /b 0

:: ============================================================================
:done
if exist "%VISITED_FILE%" del /f /q "%VISITED_FILE%"
for /f %%C in ('find /c /v "" ^< "%OUTPUT%"') do set "LINE_COUNT=%%C"
echo Done: %OUTPUT% (%LINE_COUNT% lines)
endlocal
exit /b 0

:error
if exist "%VISITED_FILE%" del /f /q "%VISITED_FILE%"
endlocal
exit /b 1
