var annotated_dup =
[
    [ "gaia", null, [
      [ "cnt", null, [
        [ "bitset", "classgaia_1_1cnt_1_1bitset.html", "classgaia_1_1cnt_1_1bitset" ],
        [ "bitset_const_iterator", "classgaia_1_1cnt_1_1bitset__const__iterator.html", "classgaia_1_1cnt_1_1bitset__const__iterator" ],
        [ "const_page_iterator", "structgaia_1_1cnt_1_1const__page__iterator.html", "structgaia_1_1cnt_1_1const__page__iterator" ],
        [ "const_page_iterator_soa", "structgaia_1_1cnt_1_1const__page__iterator__soa.html", "structgaia_1_1cnt_1_1const__page__iterator__soa" ],
        [ "const_sparse_iterator", "structgaia_1_1cnt_1_1const__sparse__iterator.html", "structgaia_1_1cnt_1_1const__sparse__iterator" ],
        [ "const_sparse_iterator< T, PageCapacity, Allocator, std::enable_if_t< std::is_empty_v< T > > >", "structgaia_1_1cnt_1_1const__sparse__iterator_3_01T_00_01PageCapacity_00_01Allocator_00_01std_1_1ac6071468172e14d5e0cd6a6d6bb0e21.html", "structgaia_1_1cnt_1_1const__sparse__iterator_3_01T_00_01PageCapacity_00_01Allocator_00_01std_1_1ac6071468172e14d5e0cd6a6d6bb0e21" ],
        [ "darr", "classgaia_1_1cnt_1_1darr.html", "classgaia_1_1cnt_1_1darr" ],
        [ "darr_ext", "classgaia_1_1cnt_1_1darr__ext.html", "classgaia_1_1cnt_1_1darr__ext" ],
        [ "darr_ext_soa", "classgaia_1_1cnt_1_1darr__ext__soa.html", "classgaia_1_1cnt_1_1darr__ext__soa" ],
        [ "darr_soa", "classgaia_1_1cnt_1_1darr__soa.html", "classgaia_1_1cnt_1_1darr__soa" ],
        [ "darray_ilist_storage", "structgaia_1_1cnt_1_1darray__ilist__storage.html", "structgaia_1_1cnt_1_1darray__ilist__storage" ],
        [ "dbitset", "classgaia_1_1cnt_1_1dbitset.html", "classgaia_1_1cnt_1_1dbitset" ],
        [ "fwd_llist", "structgaia_1_1cnt_1_1fwd__llist.html", "structgaia_1_1cnt_1_1fwd__llist" ],
        [ "fwd_llist_base", "structgaia_1_1cnt_1_1fwd__llist__base.html", "structgaia_1_1cnt_1_1fwd__llist__base" ],
        [ "fwd_llist_iterator", "structgaia_1_1cnt_1_1fwd__llist__iterator.html", "structgaia_1_1cnt_1_1fwd__llist__iterator" ],
        [ "fwd_llist_link", "structgaia_1_1cnt_1_1fwd__llist__link.html", "structgaia_1_1cnt_1_1fwd__llist__link" ],
        [ "ilist", "structgaia_1_1cnt_1_1ilist.html", "structgaia_1_1cnt_1_1ilist" ],
        [ "ilist_handle_traits", "structgaia_1_1cnt_1_1ilist__handle__traits.html", "structgaia_1_1cnt_1_1ilist__handle__traits" ],
        [ "ilist_handle_traits< TItemHandle, std::void_t< decltype(std::declval< const TItemHandle & >().prio())> >", "structgaia_1_1cnt_1_1ilist__handle__traits_3_01TItemHandle_00_01std_1_1void__t_3_01decltype_07st2a0d0d6f9c6aac50cc62708895916597.html", "structgaia_1_1cnt_1_1ilist__handle__traits_3_01TItemHandle_00_01std_1_1void__t_3_01decltype_07st2a0d0d6f9c6aac50cc62708895916597" ],
        [ "ilist_item", "structgaia_1_1cnt_1_1ilist__item.html", "structgaia_1_1cnt_1_1ilist__item" ],
        [ "ilist_item_traits", "structgaia_1_1cnt_1_1ilist__item__traits.html", "structgaia_1_1cnt_1_1ilist__item__traits" ],
        [ "page_iterator", "structgaia_1_1cnt_1_1page__iterator.html", "structgaia_1_1cnt_1_1page__iterator" ],
        [ "page_iterator_soa", "structgaia_1_1cnt_1_1page__iterator__soa.html", "structgaia_1_1cnt_1_1page__iterator__soa" ],
        [ "page_storage", "classgaia_1_1cnt_1_1page__storage.html", "classgaia_1_1cnt_1_1page__storage" ],
        [ "paged_ilist", "structgaia_1_1cnt_1_1paged__ilist.html", "structgaia_1_1cnt_1_1paged__ilist" ],
        [ "paged_ilist_iterator", "classgaia_1_1cnt_1_1paged__ilist__iterator.html", "classgaia_1_1cnt_1_1paged__ilist__iterator" ],
        [ "sarr", "classgaia_1_1cnt_1_1sarr.html", "classgaia_1_1cnt_1_1sarr" ],
        [ "sarr_ext", "classgaia_1_1cnt_1_1sarr__ext.html", "classgaia_1_1cnt_1_1sarr__ext" ],
        [ "sarr_ext_soa", "classgaia_1_1cnt_1_1sarr__ext__soa.html", "classgaia_1_1cnt_1_1sarr__ext__soa" ],
        [ "sarr_soa", "classgaia_1_1cnt_1_1sarr__soa.html", "classgaia_1_1cnt_1_1sarr__soa" ],
        [ "sparse_iterator", "structgaia_1_1cnt_1_1sparse__iterator.html", "structgaia_1_1cnt_1_1sparse__iterator" ],
        [ "sparse_iterator< T, PageCapacity, Allocator, std::enable_if_t< std::is_empty_v< T > > >", "structgaia_1_1cnt_1_1sparse__iterator_3_01T_00_01PageCapacity_00_01Allocator_00_01std_1_1enable_a04ec75195309ee4c5d26ce99aa078a9.html", "structgaia_1_1cnt_1_1sparse__iterator_3_01T_00_01PageCapacity_00_01Allocator_00_01std_1_1enable_a04ec75195309ee4c5d26ce99aa078a9" ],
        [ "sparse_storage", "classgaia_1_1cnt_1_1sparse__storage.html", "classgaia_1_1cnt_1_1sparse__storage" ],
        [ "sparse_storage< T, PageCapacity, Allocator, std::enable_if_t< std::is_empty_v< T > > >", "classgaia_1_1cnt_1_1sparse__storage_3_01T_00_01PageCapacity_00_01Allocator_00_01std_1_1enable__ie087b7e8314b32ca924843d3e0f50e85.html", "classgaia_1_1cnt_1_1sparse__storage_3_01T_00_01PageCapacity_00_01Allocator_00_01std_1_1enable__ie087b7e8314b32ca924843d3e0f50e85" ],
        [ "sringbuffer", "classgaia_1_1cnt_1_1sringbuffer.html", "classgaia_1_1cnt_1_1sringbuffer" ],
        [ "sringbuffer_iterator", "structgaia_1_1cnt_1_1sringbuffer__iterator.html", "structgaia_1_1cnt_1_1sringbuffer__iterator" ],
        [ "to_page_storage_id", "structgaia_1_1cnt_1_1to__page__storage__id.html", "structgaia_1_1cnt_1_1to__page__storage__id" ],
        [ "to_sparse_id", "structgaia_1_1cnt_1_1to__sparse__id.html", "structgaia_1_1cnt_1_1to__sparse__id" ],
        [ "to_sparse_id< ecs::Entity >", "structgaia_1_1cnt_1_1to__sparse__id_3_01ecs_1_1Entity_01_4.html", null ]
      ] ],
      [ "core", null, [
        [ "bidirectional_iterator_tag", "structgaia_1_1core_1_1bidirectional__iterator__tag.html", null ],
        [ "bit_view", "structgaia_1_1core_1_1bit__view.html", "structgaia_1_1core_1_1bit__view" ],
        [ "contiguous_iterator_tag", "structgaia_1_1core_1_1contiguous__iterator__tag.html", null ],
        [ "direct_hash_key", "structgaia_1_1core_1_1direct__hash__key.html", "structgaia_1_1core_1_1direct__hash__key" ],
        [ "dyn_singleton", "classgaia_1_1core_1_1dyn__singleton.html", "classgaia_1_1core_1_1dyn__singleton" ],
        [ "equal_to", "structgaia_1_1core_1_1equal__to.html", "structgaia_1_1core_1_1equal__to" ],
        [ "forward_iterator_tag", "structgaia_1_1core_1_1forward__iterator__tag.html", null ],
        [ "func_type_list", "structgaia_1_1core_1_1func__type__list.html", null ],
        [ "has_data_size", "structgaia_1_1core_1_1has__data__size.html", null ],
        [ "has_data_size< T, std::void_t< decltype(detail::data(std::declval< T >())), decltype(detail::size(std::declval< T >())) > >", "structgaia_1_1core_1_1has__data__size_3_01T_00_01std_1_1void__t_3_01decltype_07detail_1_1data_0731442a81cf4e1da91ee338fd93279e3c.html", null ],
        [ "has_ffunc_equals", "structgaia_1_1core_1_1has__ffunc__equals.html", "structgaia_1_1core_1_1has__ffunc__equals" ],
        [ "has_func_equals", "structgaia_1_1core_1_1has__func__equals.html", "structgaia_1_1core_1_1has__func__equals" ],
        [ "has_size_begin_end", "structgaia_1_1core_1_1has__size__begin__end.html", null ],
        [ "has_size_begin_end< T, std::void_t< decltype(std::declval< T >().begin()), decltype(std::declval< T >().end()), decltype(detail::size(std::declval< T >())) > >", "structgaia_1_1core_1_1has__size__begin__end_3_01T_00_01std_1_1void__t_3_01decltype_07std_1_1decled3338d74af8cc0bacdf33bd2a865cfb.html", null ],
        [ "input_iterator_tag", "structgaia_1_1core_1_1input__iterator__tag.html", null ],
        [ "is_greater", "structgaia_1_1core_1_1is__greater.html", "structgaia_1_1core_1_1is__greater" ],
        [ "is_iterator", "structgaia_1_1core_1_1is__iterator.html", null ],
        [ "is_smaller", "structgaia_1_1core_1_1is__smaller.html", "structgaia_1_1core_1_1is__smaller" ],
        [ "is_smaller_or_equal", "structgaia_1_1core_1_1is__smaller__or__equal.html", "structgaia_1_1core_1_1is__smaller__or__equal" ],
        [ "lock_scope", "structgaia_1_1core_1_1lock__scope.html", "structgaia_1_1core_1_1lock__scope" ],
        [ "output_iterator_tag", "structgaia_1_1core_1_1output__iterator__tag.html", null ],
        [ "random_access_iterator_tag", "structgaia_1_1core_1_1random__access__iterator__tag.html", null ],
        [ "reverse_iterator_tag", "structgaia_1_1core_1_1reverse__iterator__tag.html", null ],
        [ "span", "classgaia_1_1core_1_1span.html", "classgaia_1_1core_1_1span" ],
        [ "StringLookupKey", "structgaia_1_1core_1_1StringLookupKey.html", "structgaia_1_1core_1_1StringLookupKey" ],
        [ "type_list", "structgaia_1_1core_1_1type__list.html", "structgaia_1_1core_1_1type__list" ],
        [ "type_list_concat", "structgaia_1_1core_1_1type__list__concat.html", null ],
        [ "type_list_concat< type_list< TypesA... >, type_list< TypesB... > >", "structgaia_1_1core_1_1type__list__concat_3_01type__list_3_01TypesA_8_8_8_01_4_00_01type__list_3_01TypesB_8_8_8_01_4_01_4.html", "structgaia_1_1core_1_1type__list__concat_3_01type__list_3_01TypesA_8_8_8_01_4_00_01type__list_3_01TypesB_8_8_8_01_4_01_4" ],
        [ "unique", "structgaia_1_1core_1_1unique.html", null ],
        [ "unique< std::tuple< Ts... >, U, Us... >", "structgaia_1_1core_1_1unique_3_01std_1_1tuple_3_01Ts_8_8_8_01_4_00_01U_00_01Us_8_8_8_01_4.html", null ],
        [ "zero_t", "structgaia_1_1core_1_1zero__t.html", null ]
      ] ],
      [ "ecs", null, [
        [ "detail", null, [
          [ "CommandBuffer", "classgaia_1_1ecs_1_1detail_1_1CommandBuffer.html", "classgaia_1_1ecs_1_1detail_1_1CommandBuffer" ],
          [ "ComponentDesc", "structgaia_1_1ecs_1_1detail_1_1ComponentDesc.html", "structgaia_1_1ecs_1_1detail_1_1ComponentDesc" ],
          [ "CopyIterGroupState", "structgaia_1_1ecs_1_1detail_1_1CopyIterGroupState.html", "structgaia_1_1ecs_1_1detail_1_1CopyIterGroupState" ],
          [ "NonFragmentingRelationStore", "structgaia_1_1ecs_1_1detail_1_1NonFragmentingRelationStore.html", "structgaia_1_1ecs_1_1detail_1_1NonFragmentingRelationStore" ],
          [ "PendingSystemJob", "structgaia_1_1ecs_1_1detail_1_1PendingSystemJob.html", "structgaia_1_1ecs_1_1detail_1_1PendingSystemJob" ],
          [ "PrefabChildEdge", "structgaia_1_1ecs_1_1detail_1_1PrefabChildEdge.html", "structgaia_1_1ecs_1_1detail_1_1PrefabChildEdge" ],
          [ "PrefabInstantiatePlanNode", "structgaia_1_1ecs_1_1detail_1_1PrefabInstantiatePlanNode.html", "structgaia_1_1ecs_1_1detail_1_1PrefabInstantiatePlanNode" ],
          [ "QueryImpl", "classgaia_1_1ecs_1_1detail_1_1QueryImpl.html", "classgaia_1_1ecs_1_1detail_1_1QueryImpl" ],
          [ "SystemCollectCtx", "structgaia_1_1ecs_1_1detail_1_1SystemCollectCtx.html", "structgaia_1_1ecs_1_1detail_1_1SystemCollectCtx" ],
          [ "SystemPhaseScheduleItem", "structgaia_1_1ecs_1_1detail_1_1SystemPhaseScheduleItem.html", "structgaia_1_1ecs_1_1detail_1_1SystemPhaseScheduleItem" ],
          [ "SystemRunCtx", "structgaia_1_1ecs_1_1detail_1_1SystemRunCtx.html", "structgaia_1_1ecs_1_1detail_1_1SystemRunCtx" ],
          [ "SystemScheduleEdge", "structgaia_1_1ecs_1_1detail_1_1SystemScheduleEdge.html", "structgaia_1_1ecs_1_1detail_1_1SystemScheduleEdge" ],
          [ "SystemScheduleItem", "structgaia_1_1ecs_1_1detail_1_1SystemScheduleItem.html", "structgaia_1_1ecs_1_1detail_1_1SystemScheduleItem" ],
          [ "SystemScheduleScratch", "structgaia_1_1ecs_1_1detail_1_1SystemScheduleScratch.html", "structgaia_1_1ecs_1_1detail_1_1SystemScheduleScratch" ]
        ] ],
        [ "vm", null, [
          [ "ArchetypeLookupView", "structgaia_1_1ecs_1_1vm_1_1ArchetypeLookupView.html", "structgaia_1_1ecs_1_1vm_1_1ArchetypeLookupView" ],
          [ "MatchingCtx", "structgaia_1_1ecs_1_1vm_1_1MatchingCtx.html", "structgaia_1_1ecs_1_1vm_1_1MatchingCtx" ],
          [ "VirtualMachine", "classgaia_1_1ecs_1_1vm_1_1VirtualMachine.html", "classgaia_1_1ecs_1_1vm_1_1VirtualMachine" ]
        ] ],
        [ "_Var0", "structgaia_1_1ecs_1_1__Var0.html", null ],
        [ "_Var1", "structgaia_1_1ecs_1_1__Var1.html", null ],
        [ "_Var2", "structgaia_1_1ecs_1_1__Var2.html", null ],
        [ "_Var3", "structgaia_1_1ecs_1_1__Var3.html", null ],
        [ "_Var4", "structgaia_1_1ecs_1_1__Var4.html", null ],
        [ "_Var5", "structgaia_1_1ecs_1_1__Var5.html", null ],
        [ "_Var6", "structgaia_1_1ecs_1_1__Var6.html", null ],
        [ "_Var7", "structgaia_1_1ecs_1_1__Var7.html", null ],
        [ "AccessContextMT", "structgaia_1_1ecs_1_1AccessContextMT.html", null ],
        [ "AccessContextST", "structgaia_1_1ecs_1_1AccessContextST.html", null ],
        [ "Acyclic_", "structgaia_1_1ecs_1_1Acyclic__.html", null ],
        [ "All_", "structgaia_1_1ecs_1_1All__.html", null ],
        [ "Archetype", "classgaia_1_1ecs_1_1Archetype.html", "classgaia_1_1ecs_1_1Archetype" ],
        [ "ArchetypeBase", "classgaia_1_1ecs_1_1ArchetypeBase.html", "classgaia_1_1ecs_1_1ArchetypeBase" ],
        [ "ArchetypeChunkPair", "structgaia_1_1ecs_1_1ArchetypeChunkPair.html", null ],
        [ "ArchetypeCompIndices", "structgaia_1_1ecs_1_1ArchetypeCompIndices.html", "structgaia_1_1ecs_1_1ArchetypeCompIndices" ],
        [ "ArchetypeInheritedData", "structgaia_1_1ecs_1_1ArchetypeInheritedData.html", "structgaia_1_1ecs_1_1ArchetypeInheritedData" ],
        [ "ArchetypeLookupChecker", "classgaia_1_1ecs_1_1ArchetypeLookupChecker.html", null ],
        [ "ArchetypeLookupKey", "classgaia_1_1ecs_1_1ArchetypeLookupKey.html", null ],
        [ "CantCombine_", "structgaia_1_1ecs_1_1CantCombine__.html", null ],
        [ "ChildOf_", "structgaia_1_1ecs_1_1ChildOf__.html", null ],
        [ "Chunk", "classgaia_1_1ecs_1_1Chunk.html", "classgaia_1_1ecs_1_1Chunk" ],
        [ "Component", "structgaia_1_1ecs_1_1Component.html", "structgaia_1_1ecs_1_1Component" ],
        [ "ComponentCursor", "structgaia_1_1ecs_1_1ComponentCursor.html", "structgaia_1_1ecs_1_1ComponentCursor" ],
        [ "ComponentDesc", "structgaia_1_1ecs_1_1ComponentDesc.html", "structgaia_1_1ecs_1_1ComponentDesc" ],
        [ "ComponentGetter", "structgaia_1_1ecs_1_1ComponentGetter.html", "structgaia_1_1ecs_1_1ComponentGetter" ],
        [ "ComponentIndexEntry", "structgaia_1_1ecs_1_1ComponentIndexEntry.html", "structgaia_1_1ecs_1_1ComponentIndexEntry" ],
        [ "ComponentIndexEntryArray", "classgaia_1_1ecs_1_1ComponentIndexEntryArray.html", "classgaia_1_1ecs_1_1ComponentIndexEntryArray" ],
        [ "ComponentRawMutView", "structgaia_1_1ecs_1_1ComponentRawMutView.html", "structgaia_1_1ecs_1_1ComponentRawMutView" ],
        [ "ComponentRawView", "structgaia_1_1ecs_1_1ComponentRawView.html", "structgaia_1_1ecs_1_1ComponentRawView" ],
        [ "ComponentSetter", "structgaia_1_1ecs_1_1ComponentSetter.html", "structgaia_1_1ecs_1_1ComponentSetter" ],
        [ "CopyIter", "classgaia_1_1ecs_1_1CopyIter.html", "classgaia_1_1ecs_1_1CopyIter" ],
        [ "Core_", "structgaia_1_1ecs_1_1Core__.html", null ],
        [ "CursorResult", "structgaia_1_1ecs_1_1CursorResult.html", "structgaia_1_1ecs_1_1CursorResult" ],
        [ "CursorResult< void >", "structgaia_1_1ecs_1_1CursorResult_3_01void_01_4.html", "structgaia_1_1ecs_1_1CursorResult_3_01void_01_4" ],
        [ "Delete_", "structgaia_1_1ecs_1_1Delete__.html", null ],
        [ "DependsOn_", "structgaia_1_1ecs_1_1DependsOn__.html", null ],
        [ "DirectChunkEntry", "structgaia_1_1ecs_1_1DirectChunkEntry.html", "structgaia_1_1ecs_1_1DirectChunkEntry" ],
        [ "DontFragment_", "structgaia_1_1ecs_1_1DontFragment__.html", null ],
        [ "DontInherit_", "structgaia_1_1ecs_1_1DontInherit__.html", null ],
        [ "Entity", "structgaia_1_1ecs_1_1Entity.html", "structgaia_1_1ecs_1_1Entity" ],
        [ "EntityDesc", "structgaia_1_1ecs_1_1EntityDesc.html", null ],
        [ "EntityLookupKey", "structgaia_1_1ecs_1_1EntityLookupKey.html", null ],
        [ "Error_", "structgaia_1_1ecs_1_1Error__.html", null ],
        [ "Exclusive_", "structgaia_1_1ecs_1_1Exclusive__.html", null ],
        [ "Inherit_", "structgaia_1_1ecs_1_1Inherit__.html", null ],
        [ "Is_", "structgaia_1_1ecs_1_1Is__.html", null ],
        [ "is_pair", "structgaia_1_1ecs_1_1is__pair.html", null ],
        [ "Iter", "classgaia_1_1ecs_1_1Iter.html", "classgaia_1_1ecs_1_1Iter" ],
        [ "Observer_", "structgaia_1_1ecs_1_1Observer__.html", null ],
        [ "OnDelete_", "structgaia_1_1ecs_1_1OnDelete__.html", null ],
        [ "OnDeleteTarget_", "structgaia_1_1ecs_1_1OnDeleteTarget__.html", null ],
        [ "OnInstantiate_", "structgaia_1_1ecs_1_1OnInstantiate__.html", null ],
        [ "Override_", "structgaia_1_1ecs_1_1Override__.html", null ],
        [ "pair", "classgaia_1_1ecs_1_1pair.html", null ],
        [ "pair< Entity, Entity >", "classgaia_1_1ecs_1_1pair_3_01Entity_00_01Entity_01_4.html", null ],
        [ "Parent_", "structgaia_1_1ecs_1_1Parent__.html", null ],
        [ "Prefab_", "structgaia_1_1ecs_1_1Prefab__.html", null ],
        [ "query_sort_cond", "structgaia_1_1ecs_1_1query__sort__cond.html", "structgaia_1_1ecs_1_1query__sort__cond" ],
        [ "QueryAccessSet", "structgaia_1_1ecs_1_1QueryAccessSet.html", "structgaia_1_1ecs_1_1QueryAccessSet" ],
        [ "QueryArchetypeCacheCursor", "structgaia_1_1ecs_1_1QueryArchetypeCacheCursor.html", "structgaia_1_1ecs_1_1QueryArchetypeCacheCursor" ],
        [ "QueryCtx", "structgaia_1_1ecs_1_1QueryCtx.html", "structgaia_1_1ecs_1_1QueryCtx" ],
        [ "QueryHandle", "structgaia_1_1ecs_1_1QueryHandle.html", "structgaia_1_1ecs_1_1QueryHandle" ],
        [ "QueryHandleLookupKey", "structgaia_1_1ecs_1_1QueryHandleLookupKey.html", "structgaia_1_1ecs_1_1QueryHandleLookupKey" ],
        [ "QueryIdentity", "structgaia_1_1ecs_1_1QueryIdentity.html", "structgaia_1_1ecs_1_1QueryIdentity" ],
        [ "QueryInfo", "classgaia_1_1ecs_1_1QueryInfo.html", "classgaia_1_1ecs_1_1QueryInfo" ],
        [ "QueryInfoCreationCtx", "structgaia_1_1ecs_1_1QueryInfoCreationCtx.html", "structgaia_1_1ecs_1_1QueryInfoCreationCtx" ],
        [ "QueryInput", "structgaia_1_1ecs_1_1QueryInput.html", "structgaia_1_1ecs_1_1QueryInput" ],
        [ "QueryMatchScratch", "structgaia_1_1ecs_1_1QueryMatchScratch.html", "structgaia_1_1ecs_1_1QueryMatchScratch" ],
        [ "QueryTerm", "structgaia_1_1ecs_1_1QueryTerm.html", "structgaia_1_1ecs_1_1QueryTerm" ],
        [ "QueryTermOptions", "structgaia_1_1ecs_1_1QueryTermOptions.html", "structgaia_1_1ecs_1_1QueryTermOptions" ],
        [ "RawSparseStoreOps", "structgaia_1_1ecs_1_1RawSparseStoreOps.html", "structgaia_1_1ecs_1_1RawSparseStoreOps" ],
        [ "Remove_", "structgaia_1_1ecs_1_1Remove__.html", null ],
        [ "Requires_", "structgaia_1_1ecs_1_1Requires__.html", null ],
        [ "RuntimeConstant", "structgaia_1_1ecs_1_1RuntimeConstant.html", "structgaia_1_1ecs_1_1RuntimeConstant" ],
        [ "RuntimeConstantDesc", "structgaia_1_1ecs_1_1RuntimeConstantDesc.html", "structgaia_1_1ecs_1_1RuntimeConstantDesc" ],
        [ "RuntimeField", "structgaia_1_1ecs_1_1RuntimeField.html", "structgaia_1_1ecs_1_1RuntimeField" ],
        [ "RuntimeFieldDesc", "structgaia_1_1ecs_1_1RuntimeFieldDesc.html", "structgaia_1_1ecs_1_1RuntimeFieldDesc" ],
        [ "RuntimeOpaqueAdapter", "structgaia_1_1ecs_1_1RuntimeOpaqueAdapter.html", "structgaia_1_1ecs_1_1RuntimeOpaqueAdapter" ],
        [ "RuntimeOpaqueScope", "structgaia_1_1ecs_1_1RuntimeOpaqueScope.html", "structgaia_1_1ecs_1_1RuntimeOpaqueScope" ],
        [ "RuntimeOpaqueValue", "structgaia_1_1ecs_1_1RuntimeOpaqueValue.html", "structgaia_1_1ecs_1_1RuntimeOpaqueValue" ],
        [ "RuntimeSequenceAdapter", "structgaia_1_1ecs_1_1RuntimeSequenceAdapter.html", "structgaia_1_1ecs_1_1RuntimeSequenceAdapter" ],
        [ "RuntimeSequenceElement", "structgaia_1_1ecs_1_1RuntimeSequenceElement.html", "structgaia_1_1ecs_1_1RuntimeSequenceElement" ],
        [ "RuntimeSequenceScope", "structgaia_1_1ecs_1_1RuntimeSequenceScope.html", "structgaia_1_1ecs_1_1RuntimeSequenceScope" ],
        [ "Sched", "structgaia_1_1ecs_1_1Sched.html", "structgaia_1_1ecs_1_1Sched" ],
        [ "SchedJob", "classgaia_1_1ecs_1_1SchedJob.html", "classgaia_1_1ecs_1_1SchedJob" ],
        [ "SchedParDesc", "structgaia_1_1ecs_1_1SchedParDesc.html", "structgaia_1_1ecs_1_1SchedParDesc" ],
        [ "SchedTaskDesc", "structgaia_1_1ecs_1_1SchedTaskDesc.html", "structgaia_1_1ecs_1_1SchedTaskDesc" ],
        [ "SchedToken", "structgaia_1_1ecs_1_1SchedToken.html", "structgaia_1_1ecs_1_1SchedToken" ],
        [ "SingleArchetypeLookupItem", "structgaia_1_1ecs_1_1SingleArchetypeLookupItem.html", "structgaia_1_1ecs_1_1SingleArchetypeLookupItem" ],
        [ "Sparse_", "structgaia_1_1ecs_1_1Sparse__.html", null ],
        [ "Traversable_", "structgaia_1_1ecs_1_1Traversable__.html", null ],
        [ "uni", "structgaia_1_1ecs_1_1uni.html", "structgaia_1_1ecs_1_1uni" ],
        [ "World", "classgaia_1_1ecs_1_1World.html", "classgaia_1_1ecs_1_1World" ]
      ] ],
      [ "mem", null, [
        [ "AllocHelper", "structgaia_1_1mem_1_1AllocHelper.html", "structgaia_1_1mem_1_1AllocHelper" ],
        [ "data_layout_properties", "structgaia_1_1mem_1_1data__layout__properties.html", null ],
        [ "data_layout_properties< DataLayout::AoS, TItem >", "structgaia_1_1mem_1_1data__layout__properties_3_01DataLayout_1_1AoS_00_01TItem_01_4.html", "structgaia_1_1mem_1_1data__layout__properties_3_01DataLayout_1_1AoS_00_01TItem_01_4" ],
        [ "data_layout_properties< DataLayout::SoA, TItem >", "structgaia_1_1mem_1_1data__layout__properties_3_01DataLayout_1_1SoA_00_01TItem_01_4.html", "structgaia_1_1mem_1_1data__layout__properties_3_01DataLayout_1_1SoA_00_01TItem_01_4" ],
        [ "data_layout_properties< DataLayout::SoA16, TItem >", "structgaia_1_1mem_1_1data__layout__properties_3_01DataLayout_1_1SoA16_00_01TItem_01_4.html", "structgaia_1_1mem_1_1data__layout__properties_3_01DataLayout_1_1SoA16_00_01TItem_01_4" ],
        [ "data_layout_properties< DataLayout::SoA8, TItem >", "structgaia_1_1mem_1_1data__layout__properties_3_01DataLayout_1_1SoA8_00_01TItem_01_4.html", "structgaia_1_1mem_1_1data__layout__properties_3_01DataLayout_1_1SoA8_00_01TItem_01_4" ],
        [ "data_view_policy", "structgaia_1_1mem_1_1data__view__policy.html", null ],
        [ "data_view_policy< DataLayout::AoS, ValueType >", "structgaia_1_1mem_1_1data__view__policy_3_01DataLayout_1_1AoS_00_01ValueType_01_4.html", null ],
        [ "data_view_policy< DataLayout::SoA, ValueType >", "structgaia_1_1mem_1_1data__view__policy_3_01DataLayout_1_1SoA_00_01ValueType_01_4.html", null ],
        [ "data_view_policy< DataLayout::SoA16, ValueType >", "structgaia_1_1mem_1_1data__view__policy_3_01DataLayout_1_1SoA16_00_01ValueType_01_4.html", null ],
        [ "data_view_policy< DataLayout::SoA8, ValueType >", "structgaia_1_1mem_1_1data__view__policy_3_01DataLayout_1_1SoA8_00_01ValueType_01_4.html", null ],
        [ "data_view_policy_aos", "structgaia_1_1mem_1_1data__view__policy__aos.html", "structgaia_1_1mem_1_1data__view__policy__aos" ],
        [ "data_view_policy_aos_get", "structgaia_1_1mem_1_1data__view__policy__aos__get.html", "structgaia_1_1mem_1_1data__view__policy__aos__get" ],
        [ "data_view_policy_aos_set", "structgaia_1_1mem_1_1data__view__policy__aos__set.html", "structgaia_1_1mem_1_1data__view__policy__aos__set" ],
        [ "data_view_policy_get", "structgaia_1_1mem_1_1data__view__policy__get.html", null ],
        [ "data_view_policy_get< DataLayout::AoS, ValueType >", "structgaia_1_1mem_1_1data__view__policy__get_3_01DataLayout_1_1AoS_00_01ValueType_01_4.html", null ],
        [ "data_view_policy_get< DataLayout::SoA, ValueType >", "structgaia_1_1mem_1_1data__view__policy__get_3_01DataLayout_1_1SoA_00_01ValueType_01_4.html", null ],
        [ "data_view_policy_get< DataLayout::SoA16, ValueType >", "structgaia_1_1mem_1_1data__view__policy__get_3_01DataLayout_1_1SoA16_00_01ValueType_01_4.html", null ],
        [ "data_view_policy_get< DataLayout::SoA8, ValueType >", "structgaia_1_1mem_1_1data__view__policy__get_3_01DataLayout_1_1SoA8_00_01ValueType_01_4.html", null ],
        [ "data_view_policy_get_idx", "structgaia_1_1mem_1_1data__view__policy__get__idx.html", null ],
        [ "data_view_policy_set", "structgaia_1_1mem_1_1data__view__policy__set.html", null ],
        [ "data_view_policy_set< DataLayout::AoS, ValueType >", "structgaia_1_1mem_1_1data__view__policy__set_3_01DataLayout_1_1AoS_00_01ValueType_01_4.html", null ],
        [ "data_view_policy_set< DataLayout::SoA, ValueType >", "structgaia_1_1mem_1_1data__view__policy__set_3_01DataLayout_1_1SoA_00_01ValueType_01_4.html", null ],
        [ "data_view_policy_set< DataLayout::SoA16, ValueType >", "structgaia_1_1mem_1_1data__view__policy__set_3_01DataLayout_1_1SoA16_00_01ValueType_01_4.html", null ],
        [ "data_view_policy_set< DataLayout::SoA8, ValueType >", "structgaia_1_1mem_1_1data__view__policy__set_3_01DataLayout_1_1SoA8_00_01ValueType_01_4.html", null ],
        [ "data_view_policy_set_idx", "structgaia_1_1mem_1_1data__view__policy__set__idx.html", null ],
        [ "data_view_policy_soa", "structgaia_1_1mem_1_1data__view__policy__soa.html", "structgaia_1_1mem_1_1data__view__policy__soa" ],
        [ "data_view_policy_soa_erased", "structgaia_1_1mem_1_1data__view__policy__soa__erased.html", "structgaia_1_1mem_1_1data__view__policy__soa__erased" ],
        [ "data_view_policy_soa_get", "structgaia_1_1mem_1_1data__view__policy__soa__get.html", "structgaia_1_1mem_1_1data__view__policy__soa__get" ],
        [ "data_view_policy_soa_set", "structgaia_1_1mem_1_1data__view__policy__soa__set.html", "structgaia_1_1mem_1_1data__view__policy__soa__set" ],
        [ "DefaultAllocator", "structgaia_1_1mem_1_1DefaultAllocator.html", "structgaia_1_1mem_1_1DefaultAllocator" ],
        [ "DefaultAllocatorAdaptor", "structgaia_1_1mem_1_1DefaultAllocatorAdaptor.html", "structgaia_1_1mem_1_1DefaultAllocatorAdaptor" ],
        [ "MemoryPage", "structgaia_1_1mem_1_1MemoryPage.html", "structgaia_1_1mem_1_1MemoryPage" ],
        [ "MemoryPageContainer", "structgaia_1_1mem_1_1MemoryPageContainer.html", "structgaia_1_1mem_1_1MemoryPageContainer" ],
        [ "MemoryPageHeader", "structgaia_1_1mem_1_1MemoryPageHeader.html", "structgaia_1_1mem_1_1MemoryPageHeader" ],
        [ "MemoryPageStats", "structgaia_1_1mem_1_1MemoryPageStats.html", "structgaia_1_1mem_1_1MemoryPageStats" ],
        [ "SmallBlockAllocatorPageStats", "structgaia_1_1mem_1_1SmallBlockAllocatorPageStats.html", "structgaia_1_1mem_1_1SmallBlockAllocatorPageStats" ],
        [ "SmallBlockAllocatorStats", "structgaia_1_1mem_1_1SmallBlockAllocatorStats.html", "structgaia_1_1mem_1_1SmallBlockAllocatorStats" ],
        [ "StackAllocator", "classgaia_1_1mem_1_1StackAllocator.html", "classgaia_1_1mem_1_1StackAllocator" ],
        [ "unaligned_ref", "classgaia_1_1mem_1_1unaligned__ref.html", "classgaia_1_1mem_1_1unaligned__ref" ]
      ] ],
      [ "meta", null, [
        [ "type_info", "structgaia_1_1meta_1_1type__info.html", "structgaia_1_1meta_1_1type__info" ]
      ] ],
      [ "mt", null, [
        [ "Event", "classgaia_1_1mt_1_1Event.html", "classgaia_1_1mt_1_1Event" ],
        [ "Futex", "structgaia_1_1mt_1_1Futex.html", "structgaia_1_1mt_1_1Futex" ],
        [ "Job", "structgaia_1_1mt_1_1Job.html", "structgaia_1_1mt_1_1Job" ],
        [ "JobAllocCtx", "structgaia_1_1mt_1_1JobAllocCtx.html", "structgaia_1_1mt_1_1JobAllocCtx" ],
        [ "JobArgs", "structgaia_1_1mt_1_1JobArgs.html", "structgaia_1_1mt_1_1JobArgs" ],
        [ "JobArgsFunc", "classgaia_1_1mt_1_1JobArgsFunc.html", null ],
        [ "JobHandle", "structgaia_1_1mt_1_1JobHandle.html", "structgaia_1_1mt_1_1JobHandle" ],
        [ "JobNull_t", "structgaia_1_1mt_1_1JobNull__t.html", "structgaia_1_1mt_1_1JobNull__t" ],
        [ "JobParallel", "structgaia_1_1mt_1_1JobParallel.html", "structgaia_1_1mt_1_1JobParallel" ],
        [ "JobParallelRef", "structgaia_1_1mt_1_1JobParallelRef.html", "structgaia_1_1mt_1_1JobParallelRef" ],
        [ "Semaphore", "classgaia_1_1mt_1_1Semaphore.html", "classgaia_1_1mt_1_1Semaphore" ],
        [ "SemaphoreFast", "classgaia_1_1mt_1_1SemaphoreFast.html", "classgaia_1_1mt_1_1SemaphoreFast" ],
        [ "SpinLock", "classgaia_1_1mt_1_1SpinLock.html", "classgaia_1_1mt_1_1SpinLock" ],
        [ "ThreadCtx", "structgaia_1_1mt_1_1ThreadCtx.html", "structgaia_1_1mt_1_1ThreadCtx" ],
        [ "ThreadPool", "classgaia_1_1mt_1_1ThreadPool.html", "classgaia_1_1mt_1_1ThreadPool" ]
      ] ],
      [ "ser", null, [
        [ "detail", null, [
          [ "has_bytes_fn", "structgaia_1_1ser_1_1detail_1_1has__bytes__fn.html", null ],
          [ "has_bytes_fn< T, std::void_t< decltype(std::declval< const T & >().bytes())> >", "structgaia_1_1ser_1_1detail_1_1has__bytes__fn_3_01T_00_01std_1_1void__t_3_01decltype_07std_1_1de17d36e20086ed372e222cd5cabdcf227.html", null ],
          [ "has_data_ptr", "structgaia_1_1ser_1_1detail_1_1has__data__ptr.html", null ],
          [ "has_data_ptr< T, std::void_t< decltype(std::declval< const T & >().data())> >", "structgaia_1_1ser_1_1detail_1_1has__data__ptr_3_01T_00_01std_1_1void__t_3_01decltype_07std_1_1de5398e0f4947d84658557aa964b5cdec7.html", null ],
          [ "has_load_raw_ptr", "structgaia_1_1ser_1_1detail_1_1has__load__raw__ptr.html", null ],
          [ "has_load_raw_ptr< T, std::void_t< decltype(std::declval< T & >().load_raw((void *) nullptr, uint32_t{}, ser::serialization_type_id{}))> >", "structgaia_1_1ser_1_1detail_1_1has__load__raw__ptr_3_01T_00_01std_1_1void__t_3_01decltype_07std_c7f992cfb0294954c1bac9f9d1fc1e64.html", null ],
          [ "has_reset_fn", "structgaia_1_1ser_1_1detail_1_1has__reset__fn.html", null ],
          [ "has_reset_fn< T, std::void_t< decltype(std::declval< T & >().reset())> >", "structgaia_1_1ser_1_1detail_1_1has__reset__fn_3_01T_00_01std_1_1void__t_3_01decltype_07std_1_1dee4d6fcff1588f9093c259ebf893e533d.html", null ],
          [ "has_save_raw_ptr", "structgaia_1_1ser_1_1detail_1_1has__save__raw__ptr.html", null ],
          [ "has_save_raw_ptr< T, std::void_t< decltype(std::declval< T & >().save_raw((const void *) nullptr, uint32_t{}, ser::serialization_type_id{}))> >", "structgaia_1_1ser_1_1detail_1_1has__save__raw__ptr_3_01T_00_01std_1_1void__t_3_01decltype_07std_c728a9c81f6de8c25093ad94bfbbbc30.html", null ],
          [ "has_seek_fn", "structgaia_1_1ser_1_1detail_1_1has__seek__fn.html", null ],
          [ "has_seek_fn< T, std::void_t< decltype(std::declval< T & >().seek(uint32_t{}))> >", "structgaia_1_1ser_1_1detail_1_1has__seek__fn_3_01T_00_01std_1_1void__t_3_01decltype_07std_1_1decde0c993735b2058fbd9b080718d84786.html", null ],
          [ "has_tell_fn", "structgaia_1_1ser_1_1detail_1_1has__tell__fn.html", null ],
          [ "has_tell_fn< T, std::void_t< decltype(std::declval< const T & >().tell())> >", "structgaia_1_1ser_1_1detail_1_1has__tell__fn_3_01T_00_01std_1_1void__t_3_01decltype_07std_1_1dec16493ebf98a8d23d7877f9f2a01cd59a.html", null ]
        ] ],
        [ "bin_stream", "classgaia_1_1ser_1_1bin__stream.html", "classgaia_1_1ser_1_1bin__stream" ],
        [ "is_flt_kind_id", "structgaia_1_1ser_1_1is__flt__kind__id.html", null ],
        [ "is_int_kind_id", "structgaia_1_1ser_1_1is__int__kind__id.html", null ],
        [ "is_trivially_serializable", "structgaia_1_1ser_1_1is__trivially__serializable.html", "structgaia_1_1ser_1_1is__trivially__serializable" ],
        [ "JsonDiagnostic", "structgaia_1_1ser_1_1JsonDiagnostic.html", "structgaia_1_1ser_1_1JsonDiagnostic" ],
        [ "JsonDiagnostics", "structgaia_1_1ser_1_1JsonDiagnostics.html", "structgaia_1_1ser_1_1JsonDiagnostics" ],
        [ "RuntimeJsonPolicy", "structgaia_1_1ser_1_1RuntimeJsonPolicy.html", "structgaia_1_1ser_1_1RuntimeJsonPolicy" ],
        [ "ser_buffer_binary", "classgaia_1_1ser_1_1ser__buffer__binary.html", null ],
        [ "ser_buffer_binary_dyn", "classgaia_1_1ser_1_1ser__buffer__binary__dyn.html", null ],
        [ "ser_json", "classgaia_1_1ser_1_1ser__json.html", "classgaia_1_1ser_1_1ser__json" ],
        [ "serializer", "structgaia_1_1ser_1_1serializer.html", "structgaia_1_1ser_1_1serializer" ],
        [ "serializer_ctx", "structgaia_1_1ser_1_1serializer__ctx.html", "structgaia_1_1ser_1_1serializer__ctx" ]
      ] ],
      [ "util", null, [
        [ "delegate", "classgaia_1_1util_1_1delegate.html", null ],
        [ "delegate< Ret(Args...)>", "classgaia_1_1util_1_1delegate_3_01Ret_07Args_8_8_8_08_4.html", "classgaia_1_1util_1_1delegate_3_01Ret_07Args_8_8_8_08_4" ],
        [ "MoveFunc", "classgaia_1_1util_1_1MoveFunc.html", null ],
        [ "MoveFunc< R(Args...)>", "classgaia_1_1util_1_1MoveFunc_3_01R_07Args_8_8_8_08_4.html", "classgaia_1_1util_1_1MoveFunc_3_01R_07Args_8_8_8_08_4" ],
        [ "signal", "classgaia_1_1util_1_1signal.html", null ],
        [ "signal< Ret(Args...)>", "classgaia_1_1util_1_1signal_3_01Ret_07Args_8_8_8_08_4.html", "classgaia_1_1util_1_1signal_3_01Ret_07Args_8_8_8_08_4" ],
        [ "sink", "classgaia_1_1util_1_1sink.html", null ],
        [ "sink< Ret(Args...)>", "classgaia_1_1util_1_1sink_3_01Ret_07Args_8_8_8_08_4.html", "classgaia_1_1util_1_1sink_3_01Ret_07Args_8_8_8_08_4" ],
        [ "SmallFunc", "classgaia_1_1util_1_1SmallFunc.html", "classgaia_1_1util_1_1SmallFunc" ],
        [ "str", "structgaia_1_1util_1_1str.html", "structgaia_1_1util_1_1str" ],
        [ "str_view", "structgaia_1_1util_1_1str__view.html", "structgaia_1_1util_1_1str__view" ]
      ] ]
    ] ]
];