var hierarchy =
[
    [ "gaia::ecs::_Var0", "structgaia_1_1ecs_1_1__Var0.html", null ],
    [ "gaia::ecs::_Var1", "structgaia_1_1ecs_1_1__Var1.html", null ],
    [ "gaia::ecs::_Var2", "structgaia_1_1ecs_1_1__Var2.html", null ],
    [ "gaia::ecs::_Var3", "structgaia_1_1ecs_1_1__Var3.html", null ],
    [ "gaia::ecs::_Var4", "structgaia_1_1ecs_1_1__Var4.html", null ],
    [ "gaia::ecs::_Var5", "structgaia_1_1ecs_1_1__Var5.html", null ],
    [ "gaia::ecs::_Var6", "structgaia_1_1ecs_1_1__Var6.html", null ],
    [ "gaia::ecs::_Var7", "structgaia_1_1ecs_1_1__Var7.html", null ],
    [ "gaia::ecs::AccessContextMT", "structgaia_1_1ecs_1_1AccessContextMT.html", null ],
    [ "gaia::ecs::AccessContextST", "structgaia_1_1ecs_1_1AccessContextST.html", null ],
    [ "gaia::mem::data_view_policy_soa< TDataLayout, ValueType >::accessor", "classgaia_1_1mem_1_1data__view__policy__soa_1_1accessor.html", null ],
    [ "gaia::mem::data_view_policy_soa_set< TDataLayout, ValueType >::accessor", "structgaia_1_1mem_1_1data__view__policy__soa__set_1_1accessor.html", null ],
    [ "gaia::ecs::Acyclic_", "structgaia_1_1ecs_1_1Acyclic__.html", null ],
    [ "gaia::ecs::All_", "structgaia_1_1ecs_1_1All__.html", null ],
    [ "gaia::mem::AllocHelper", "structgaia_1_1mem_1_1AllocHelper.html", null ],
    [ "gaia::ecs::ArchetypeBase", "classgaia_1_1ecs_1_1ArchetypeBase.html", [
      [ "gaia::ecs::Archetype", "classgaia_1_1ecs_1_1Archetype.html", null ],
      [ "gaia::ecs::ArchetypeLookupChecker", "classgaia_1_1ecs_1_1ArchetypeLookupChecker.html", null ]
    ] ],
    [ "gaia::ecs::ArchetypeChunkPair", "structgaia_1_1ecs_1_1ArchetypeChunkPair.html", null ],
    [ "gaia::ecs::ArchetypeCompIndices", "structgaia_1_1ecs_1_1ArchetypeCompIndices.html", null ],
    [ "gaia::ecs::ArchetypeInheritedData", "structgaia_1_1ecs_1_1ArchetypeInheritedData.html", null ],
    [ "gaia::ecs::ArchetypeLookupKey", "classgaia_1_1ecs_1_1ArchetypeLookupKey.html", null ],
    [ "gaia::ecs::vm::ArchetypeLookupView", "structgaia_1_1ecs_1_1vm_1_1ArchetypeLookupView.html", null ],
    [ "gaia::ser::bin_stream", "classgaia_1_1ser_1_1bin__stream.html", null ],
    [ "gaia::core::bit_view< BlockBits >", "structgaia_1_1core_1_1bit__view.html", null ],
    [ "gaia::cnt::bitset< NBits >", "classgaia_1_1cnt_1_1bitset.html", null ],
    [ "gaia::cnt::bitset< PageCapacity >", "classgaia_1_1cnt_1_1bitset.html", null ],
    [ "gaia::cnt::bitset_const_iterator< TBitset, IsFwd, IsInverse >", "classgaia_1_1cnt_1_1bitset__const__iterator.html", null ],
    [ "std::bool_constant", null, [
      [ "gaia::core::is_iterator< T >", "structgaia_1_1core_1_1is__iterator.html", null ]
    ] ],
    [ "gaia::ecs::CantCombine_", "structgaia_1_1ecs_1_1CantCombine__.html", null ],
    [ "gaia::ecs::ChildOf_", "structgaia_1_1ecs_1_1ChildOf__.html", null ],
    [ "gaia::ecs::Chunk", "classgaia_1_1ecs_1_1Chunk.html", null ],
    [ "detail::ChunkIterImpl", null, [
      [ "gaia::ecs::Iter", "classgaia_1_1ecs_1_1Iter.html", null ]
    ] ],
    [ "gaia::ecs::QueryInfo::CleanUpTmpArchetypeMatches", "structgaia_1_1ecs_1_1QueryInfo_1_1CleanUpTmpArchetypeMatches.html", null ],
    [ "gaia::ecs::detail::CommandBuffer< AccessContext >", "classgaia_1_1ecs_1_1detail_1_1CommandBuffer.html", null ],
    [ "gaia::ecs::Component", "structgaia_1_1ecs_1_1Component.html", null ],
    [ "gaia::ecs::ComponentCursor", "structgaia_1_1ecs_1_1ComponentCursor.html", null ],
    [ "gaia::ecs::ComponentDesc", "structgaia_1_1ecs_1_1ComponentDesc.html", null ],
    [ "gaia::ecs::detail::ComponentDesc< T >", "structgaia_1_1ecs_1_1detail_1_1ComponentDesc.html", null ],
    [ "gaia::ecs::ComponentGetter", "structgaia_1_1ecs_1_1ComponentGetter.html", [
      [ "gaia::ecs::ComponentSetter", "structgaia_1_1ecs_1_1ComponentSetter.html", null ]
    ] ],
    [ "gaia::ecs::ComponentIndexEntry", "structgaia_1_1ecs_1_1ComponentIndexEntry.html", null ],
    [ "gaia::ecs::ComponentIndexEntryArray", "classgaia_1_1ecs_1_1ComponentIndexEntryArray.html", null ],
    [ "gaia::ecs::ComponentRawMutView", "structgaia_1_1ecs_1_1ComponentRawMutView.html", null ],
    [ "gaia::ecs::ComponentRawView", "structgaia_1_1ecs_1_1ComponentRawView.html", null ],
    [ "std::conditional_t", null, [
      [ "gaia::core::unique< std::tuple< Ts... >, U, Us... >", "structgaia_1_1core_1_1unique_3_01std_1_1tuple_3_01Ts_8_8_8_01_4_00_01U_00_01Us_8_8_8_01_4.html", null ]
    ] ],
    [ "gaia::cnt::const_page_iterator< T, Allocator, IsFwd >", "structgaia_1_1cnt_1_1const__page__iterator.html", null ],
    [ "gaia::cnt::const_page_iterator_soa< T, Allocator, IsFwd >", "structgaia_1_1cnt_1_1const__page__iterator__soa.html", null ],
    [ "gaia::cnt::const_sparse_iterator< T, PageCapacity, Allocator, typename >", "structgaia_1_1cnt_1_1const__sparse__iterator.html", null ],
    [ "gaia::cnt::const_sparse_iterator< T, PageCapacity, Allocator, std::enable_if_t< std::is_empty_v< T > > >", "structgaia_1_1cnt_1_1const__sparse__iterator_3_01T_00_01PageCapacity_00_01Allocator_00_01std_1_1ac6071468172e14d5e0cd6a6d6bb0e21.html", null ],
    [ "gaia::ecs::CopyIter", "classgaia_1_1ecs_1_1CopyIter.html", null ],
    [ "gaia::ecs::detail::CopyIterGroupState", "structgaia_1_1ecs_1_1detail_1_1CopyIterGroupState.html", null ],
    [ "gaia::ecs::Core_", "structgaia_1_1ecs_1_1Core__.html", null ],
    [ "gaia::ecs::CursorResult< T >", "structgaia_1_1ecs_1_1CursorResult.html", null ],
    [ "gaia::ecs::CursorResult< void >", "structgaia_1_1ecs_1_1CursorResult_3_01void_01_4.html", null ],
    [ "gaia::cnt::darr< T, Allocator >", "classgaia_1_1cnt_1_1darr.html", [
      [ "gaia::cnt::darray_ilist_storage< TListItem >", "structgaia_1_1cnt_1_1darray__ilist__storage.html", null ]
    ] ],
    [ "gaia::cnt::darr< char >", "classgaia_1_1cnt_1_1darr.html", null ],
    [ "gaia::cnt::darr< ChunkBatch >", "classgaia_1_1cnt_1_1darr.html", null ],
    [ "gaia::cnt::darr< const gaia::ecs::Archetype * >", "classgaia_1_1cnt_1_1darr.html", null ],
    [ "gaia::cnt::darr< const gaia::ecs::Chunk * >", "classgaia_1_1cnt_1_1darr.html", null ],
    [ "gaia::cnt::darr< const void * >", "classgaia_1_1cnt_1_1darr.html", null ],
    [ "gaia::cnt::darr< Ctx >", "classgaia_1_1cnt_1_1darr.html", null ],
    [ "gaia::cnt::darr< detail::BfsChunkRun >", "classgaia_1_1cnt_1_1darr.html", null ],
    [ "gaia::cnt::darr< gaia::cnt::darr< gaia::ecs::Entity > >", "classgaia_1_1cnt_1_1darr.html", null ],
    [ "gaia::cnt::darr< gaia::ecs::ArchetypeChunkPair >", "classgaia_1_1cnt_1_1darr.html", null ],
    [ "gaia::cnt::darr< gaia::ecs::ArchetypeCompIndices >", "classgaia_1_1cnt_1_1darr.html", null ],
    [ "gaia::cnt::darr< gaia::ecs::ArchetypeInheritedData >", "classgaia_1_1cnt_1_1darr.html", null ],
    [ "gaia::cnt::darr< gaia::ecs::Chunk * >", "classgaia_1_1cnt_1_1darr.html", null ],
    [ "gaia::cnt::darr< gaia::ecs::ComponentIndexEntry >", "classgaia_1_1cnt_1_1darr.html", null ],
    [ "gaia::cnt::darr< gaia::ecs::detail::PendingSystemJob >", "classgaia_1_1cnt_1_1darr.html", null ],
    [ "gaia::cnt::darr< gaia::ecs::detail::SystemPhaseScheduleItem >", "classgaia_1_1cnt_1_1darr.html", null ],
    [ "gaia::cnt::darr< gaia::ecs::detail::SystemScheduleEdge >", "classgaia_1_1cnt_1_1darr.html", null ],
    [ "gaia::cnt::darr< gaia::ecs::detail::SystemScheduleItem >", "classgaia_1_1cnt_1_1darr.html", null ],
    [ "gaia::cnt::darr< gaia::ecs::DirectChunkEntry >", "classgaia_1_1cnt_1_1darr.html", null ],
    [ "gaia::cnt::darr< gaia::ecs::Entity >", "classgaia_1_1cnt_1_1darr.html", null ],
    [ "gaia::cnt::darr< gaia::ecs::QueryMatchScratch * >", "classgaia_1_1cnt_1_1darr.html", null ],
    [ "gaia::cnt::darr< gaia::ser::JsonDiagnostic >", "classgaia_1_1cnt_1_1darr.html", null ],
    [ "gaia::cnt::darr< GroupData >", "classgaia_1_1cnt_1_1darr.html", null ],
    [ "gaia::cnt::darr< GroupId >", "classgaia_1_1cnt_1_1darr.html", null ],
    [ "gaia::cnt::darr< page_type * >", "classgaia_1_1cnt_1_1darr.html", null ],
    [ "gaia::cnt::darr< page_type >", "classgaia_1_1cnt_1_1darr.html", null ],
    [ "gaia::cnt::darr< SortData >", "classgaia_1_1cnt_1_1darr.html", null ],
    [ "gaia::cnt::darr< sparse_id >", "classgaia_1_1cnt_1_1darr.html", null ],
    [ "gaia::cnt::darr< SrcTravSnapshotItem >", "classgaia_1_1cnt_1_1darr.html", null ],
    [ "gaia::cnt::darr< uint32_t >", "classgaia_1_1cnt_1_1darr.html", null ],
    [ "gaia::cnt::darr< uint64_t >", "classgaia_1_1cnt_1_1darr.html", null ],
    [ "gaia::cnt::darr< uint8_t >", "classgaia_1_1cnt_1_1darr.html", null ],
    [ "gaia::cnt::darr_ext< T, N, Allocator >", "classgaia_1_1cnt_1_1darr__ext.html", null ],
    [ "gaia::cnt::darr_ext< gaia::ecs::Entity, 128 >", "classgaia_1_1cnt_1_1darr__ext.html", null ],
    [ "gaia::cnt::darr_ext< gaia::ecs::Entity, 16 >", "classgaia_1_1cnt_1_1darr__ext.html", null ],
    [ "gaia::cnt::darr_ext< Op, 128 >", "classgaia_1_1cnt_1_1darr__ext.html", null ],
    [ "gaia::cnt::darr_ext_soa< T, N, Allocator >", "classgaia_1_1cnt_1_1darr__ext__soa.html", null ],
    [ "gaia::cnt::darr_soa< T, Allocator >", "classgaia_1_1cnt_1_1darr__soa.html", null ],
    [ "gaia::ecs::QueryCtx::Data", "structgaia_1_1ecs_1_1QueryCtx_1_1Data.html", null ],
    [ "gaia::mem::data_layout_properties< TDataLayout, TItem >", "structgaia_1_1mem_1_1data__layout__properties.html", null ],
    [ "gaia::mem::data_layout_properties< DataLayout::AoS, TItem >", "structgaia_1_1mem_1_1data__layout__properties_3_01DataLayout_1_1AoS_00_01TItem_01_4.html", null ],
    [ "gaia::mem::data_layout_properties< DataLayout::SoA, TItem >", "structgaia_1_1mem_1_1data__layout__properties_3_01DataLayout_1_1SoA_00_01TItem_01_4.html", null ],
    [ "gaia::mem::data_layout_properties< DataLayout::SoA16, TItem >", "structgaia_1_1mem_1_1data__layout__properties_3_01DataLayout_1_1SoA16_00_01TItem_01_4.html", null ],
    [ "gaia::mem::data_layout_properties< DataLayout::SoA8, TItem >", "structgaia_1_1mem_1_1data__layout__properties_3_01DataLayout_1_1SoA8_00_01TItem_01_4.html", null ],
    [ "gaia::mem::data_view_policy< TDataLayout, TItem >", "structgaia_1_1mem_1_1data__view__policy.html", null ],
    [ "gaia::mem::data_view_policy_aos< ValueType >", "structgaia_1_1mem_1_1data__view__policy__aos.html", [
      [ "gaia::mem::data_view_policy< DataLayout::AoS, ValueType >", "structgaia_1_1mem_1_1data__view__policy_3_01DataLayout_1_1AoS_00_01ValueType_01_4.html", null ]
    ] ],
    [ "gaia::mem::data_view_policy_aos_get< ValueType >", "structgaia_1_1mem_1_1data__view__policy__aos__get.html", [
      [ "gaia::mem::data_view_policy_get< DataLayout::AoS, ValueType >", "structgaia_1_1mem_1_1data__view__policy__get_3_01DataLayout_1_1AoS_00_01ValueType_01_4.html", null ]
    ] ],
    [ "gaia::mem::data_view_policy_aos_set< ValueType >", "structgaia_1_1mem_1_1data__view__policy__aos__set.html", [
      [ "gaia::mem::data_view_policy_set< DataLayout::AoS, ValueType >", "structgaia_1_1mem_1_1data__view__policy__set_3_01DataLayout_1_1AoS_00_01ValueType_01_4.html", null ]
    ] ],
    [ "gaia::mem::data_view_policy_get< TDataLayout, TItem >", "structgaia_1_1mem_1_1data__view__policy__get.html", null ],
    [ "gaia::mem::data_view_policy_get_idx< TDataLayout, TItem, Ids >", "structgaia_1_1mem_1_1data__view__policy__get__idx.html", null ],
    [ "gaia::mem::data_view_policy_soa_get< TDataLayout, ValueType >::data_view_policy_idx_info< Item >", "structgaia_1_1mem_1_1data__view__policy__soa__get_1_1data__view__policy__idx__info.html", null ],
    [ "gaia::mem::data_view_policy_soa_set< TDataLayout, ValueType >::data_view_policy_idx_info< Item >", "structgaia_1_1mem_1_1data__view__policy__soa__set_1_1data__view__policy__idx__info.html", null ],
    [ "gaia::mem::data_view_policy_set< TDataLayout, TItem >", "structgaia_1_1mem_1_1data__view__policy__set.html", null ],
    [ "gaia::mem::data_view_policy_set_idx< TDataLayout, TItem, Ids >", "structgaia_1_1mem_1_1data__view__policy__set__idx.html", null ],
    [ "gaia::mem::data_view_policy_soa< TDataLayout, ValueType >", "structgaia_1_1mem_1_1data__view__policy__soa.html", null ],
    [ "gaia::mem::data_view_policy_soa< DataLayout::SoA, ValueType >", "structgaia_1_1mem_1_1data__view__policy__soa.html", [
      [ "gaia::mem::data_view_policy< DataLayout::SoA, ValueType >", "structgaia_1_1mem_1_1data__view__policy_3_01DataLayout_1_1SoA_00_01ValueType_01_4.html", null ]
    ] ],
    [ "gaia::mem::data_view_policy_soa< DataLayout::SoA16, ValueType >", "structgaia_1_1mem_1_1data__view__policy__soa.html", [
      [ "gaia::mem::data_view_policy< DataLayout::SoA16, ValueType >", "structgaia_1_1mem_1_1data__view__policy_3_01DataLayout_1_1SoA16_00_01ValueType_01_4.html", null ]
    ] ],
    [ "gaia::mem::data_view_policy_soa< DataLayout::SoA8, ValueType >", "structgaia_1_1mem_1_1data__view__policy__soa.html", [
      [ "gaia::mem::data_view_policy< DataLayout::SoA8, ValueType >", "structgaia_1_1mem_1_1data__view__policy_3_01DataLayout_1_1SoA8_00_01ValueType_01_4.html", null ]
    ] ],
    [ "gaia::mem::data_view_policy_soa_erased", "structgaia_1_1mem_1_1data__view__policy__soa__erased.html", null ],
    [ "gaia::mem::data_view_policy_soa_get< TDataLayout, ValueType >", "structgaia_1_1mem_1_1data__view__policy__soa__get.html", null ],
    [ "gaia::mem::data_view_policy_soa_get< DataLayout::SoA, ValueType >", "structgaia_1_1mem_1_1data__view__policy__soa__get.html", [
      [ "gaia::mem::data_view_policy_get< DataLayout::SoA, ValueType >", "structgaia_1_1mem_1_1data__view__policy__get_3_01DataLayout_1_1SoA_00_01ValueType_01_4.html", null ]
    ] ],
    [ "gaia::mem::data_view_policy_soa_get< DataLayout::SoA16, ValueType >", "structgaia_1_1mem_1_1data__view__policy__soa__get.html", [
      [ "gaia::mem::data_view_policy_get< DataLayout::SoA16, ValueType >", "structgaia_1_1mem_1_1data__view__policy__get_3_01DataLayout_1_1SoA16_00_01ValueType_01_4.html", null ]
    ] ],
    [ "gaia::mem::data_view_policy_soa_get< DataLayout::SoA8, ValueType >", "structgaia_1_1mem_1_1data__view__policy__soa__get.html", [
      [ "gaia::mem::data_view_policy_get< DataLayout::SoA8, ValueType >", "structgaia_1_1mem_1_1data__view__policy__get_3_01DataLayout_1_1SoA8_00_01ValueType_01_4.html", null ]
    ] ],
    [ "gaia::mem::data_view_policy_soa_set< TDataLayout, ValueType >", "structgaia_1_1mem_1_1data__view__policy__soa__set.html", null ],
    [ "gaia::mem::data_view_policy_soa_set< DataLayout::SoA, ValueType >", "structgaia_1_1mem_1_1data__view__policy__soa__set.html", [
      [ "gaia::mem::data_view_policy_set< DataLayout::SoA, ValueType >", "structgaia_1_1mem_1_1data__view__policy__set_3_01DataLayout_1_1SoA_00_01ValueType_01_4.html", null ]
    ] ],
    [ "gaia::mem::data_view_policy_soa_set< DataLayout::SoA16, ValueType >", "structgaia_1_1mem_1_1data__view__policy__soa__set.html", [
      [ "gaia::mem::data_view_policy_set< DataLayout::SoA16, ValueType >", "structgaia_1_1mem_1_1data__view__policy__set_3_01DataLayout_1_1SoA16_00_01ValueType_01_4.html", null ]
    ] ],
    [ "gaia::mem::data_view_policy_soa_set< DataLayout::SoA8, ValueType >", "structgaia_1_1mem_1_1data__view__policy__soa__set.html", [
      [ "gaia::mem::data_view_policy_set< DataLayout::SoA8, ValueType >", "structgaia_1_1mem_1_1data__view__policy__set_3_01DataLayout_1_1SoA8_00_01ValueType_01_4.html", null ]
    ] ],
    [ "gaia::cnt::dbitset< Allocator >", "classgaia_1_1cnt_1_1dbitset.html", null ],
    [ "gaia::cnt::dbitset< gaia::mem::DefaultAllocatorAdaptor >", "classgaia_1_1cnt_1_1dbitset.html", null ],
    [ "gaia::mem::DefaultAllocator", "structgaia_1_1mem_1_1DefaultAllocator.html", null ],
    [ "gaia::mem::DefaultAllocatorAdaptor", "structgaia_1_1mem_1_1DefaultAllocatorAdaptor.html", null ],
    [ "gaia::util::delegate< typename >", "classgaia_1_1util_1_1delegate.html", null ],
    [ "gaia::util::delegate< Ret(Args...)>", "classgaia_1_1util_1_1delegate_3_01Ret_07Args_8_8_8_08_4.html", null ],
    [ "gaia::ecs::Delete_", "structgaia_1_1ecs_1_1Delete__.html", null ],
    [ "gaia::ecs::QueryCtx::Data::Dependencies", "structgaia_1_1ecs_1_1QueryCtx_1_1Data_1_1Dependencies.html", null ],
    [ "gaia::ecs::DependsOn_", "structgaia_1_1ecs_1_1DependsOn__.html", null ],
    [ "gaia::core::direct_hash_key< T >", "structgaia_1_1core_1_1direct__hash__key.html", null ],
    [ "gaia::core::direct_hash_key< uint32_t >", "structgaia_1_1core_1_1direct__hash__key.html", null ],
    [ "gaia::core::direct_hash_key< uint64_t >", "structgaia_1_1core_1_1direct__hash__key.html", null ],
    [ "gaia::ecs::DirectChunkEntry", "structgaia_1_1ecs_1_1DirectChunkEntry.html", null ],
    [ "gaia::ecs::QueryInfo::QueryState::DynamicCacheState::DirectSourcePayload", "structgaia_1_1ecs_1_1QueryInfo_1_1QueryState_1_1DynamicCacheState_1_1DirectSourcePayload.html", null ],
    [ "std::disjunction", null, [
      [ "gaia::ser::is_flt_kind_id< T >", "structgaia_1_1ser_1_1is__flt__kind__id.html", null ],
      [ "gaia::ser::is_int_kind_id< T >", "structgaia_1_1ser_1_1is__int__kind__id.html", null ]
    ] ],
    [ "gaia::ecs::DontFragment_", "structgaia_1_1ecs_1_1DontFragment__.html", null ],
    [ "gaia::ecs::DontInherit_", "structgaia_1_1ecs_1_1DontInherit__.html", null ],
    [ "gaia::core::dyn_singleton< T >", "classgaia_1_1core_1_1dyn__singleton.html", null ],
    [ "gaia::ecs::QueryInfo::QueryState::DynamicCacheState", "structgaia_1_1ecs_1_1QueryInfo_1_1QueryState_1_1DynamicCacheState.html", null ],
    [ "gaia::ecs::Entity", "structgaia_1_1ecs_1_1Entity.html", null ],
    [ "gaia::ecs::World::EntityBuilder", "structgaia_1_1ecs_1_1World_1_1EntityBuilder.html", null ],
    [ "gaia::ecs::EntityDesc", "structgaia_1_1ecs_1_1EntityDesc.html", null ],
    [ "gaia::ecs::EntityLookupKey", "structgaia_1_1ecs_1_1EntityLookupKey.html", null ],
    [ "gaia::core::equal_to< T >", "structgaia_1_1core_1_1equal__to.html", null ],
    [ "gaia::ecs::Error_", "structgaia_1_1ecs_1_1Error__.html", null ],
    [ "gaia::mt::Event", "classgaia_1_1mt_1_1Event.html", null ],
    [ "gaia::ecs::Exclusive_", "structgaia_1_1ecs_1_1Exclusive__.html", null ],
    [ "gaia::ecs::QueryInfo::QueryState::ExecPayload", "structgaia_1_1ecs_1_1QueryInfo_1_1QueryState_1_1ExecPayload.html", null ],
    [ "std::false_type", null, [
      [ "gaia::core::has_data_size< T, Probe >", "structgaia_1_1core_1_1has__data__size.html", null ],
      [ "gaia::core::has_size_begin_end< T, Probe >", "structgaia_1_1core_1_1has__size__begin__end.html", null ],
      [ "gaia::ser::detail::has_bytes_fn< T, typename >", "structgaia_1_1ser_1_1detail_1_1has__bytes__fn.html", null ],
      [ "gaia::ser::detail::has_data_ptr< T, typename >", "structgaia_1_1ser_1_1detail_1_1has__data__ptr.html", null ],
      [ "gaia::ser::detail::has_load_raw_ptr< T, typename >", "structgaia_1_1ser_1_1detail_1_1has__load__raw__ptr.html", null ],
      [ "gaia::ser::detail::has_reset_fn< T, typename >", "structgaia_1_1ser_1_1detail_1_1has__reset__fn.html", null ],
      [ "gaia::ser::detail::has_save_raw_ptr< T, typename >", "structgaia_1_1ser_1_1detail_1_1has__save__raw__ptr.html", null ],
      [ "gaia::ser::detail::has_seek_fn< T, typename >", "structgaia_1_1ser_1_1detail_1_1has__seek__fn.html", null ],
      [ "gaia::ser::detail::has_tell_fn< T, typename >", "structgaia_1_1ser_1_1detail_1_1has__tell__fn.html", null ]
    ] ],
    [ "gaia::core::func_type_list< Type >", "structgaia_1_1core_1_1func__type__list.html", null ],
    [ "gaia::mt::Futex", "structgaia_1_1mt_1_1Futex.html", null ],
    [ "gaia::cnt::fwd_llist< T >", "structgaia_1_1cnt_1_1fwd__llist.html", null ],
    [ "gaia::cnt::fwd_llist< gaia::mem::MemoryPage< T, RequestedBlockSize > >", "structgaia_1_1cnt_1_1fwd__llist.html", null ],
    [ "gaia::cnt::fwd_llist_base< T >", "structgaia_1_1cnt_1_1fwd__llist__base.html", null ],
    [ "gaia::cnt::fwd_llist_base< MemoryPage< T, RequestedBlockSize > >", "structgaia_1_1cnt_1_1fwd__llist__base.html", [
      [ "gaia::mem::MemoryPage< T, RequestedBlockSize >", "structgaia_1_1mem_1_1MemoryPage.html", null ]
    ] ],
    [ "gaia::cnt::fwd_llist_iterator< T >", "structgaia_1_1cnt_1_1fwd__llist__iterator.html", null ],
    [ "gaia::cnt::fwd_llist_link< T >", "structgaia_1_1cnt_1_1fwd__llist__link.html", null ],
    [ "gaia::cnt::fwd_llist_link< MemoryPage< T, RequestedBlockSize > >", "structgaia_1_1cnt_1_1fwd__llist__link.html", null ],
    [ "gaia::ecs::QueryInfo::QueryState::GroupedPayload", "structgaia_1_1ecs_1_1QueryInfo_1_1QueryState_1_1GroupedPayload.html", null ],
    [ "gaia::core::has_ffunc_equals< T >", "structgaia_1_1core_1_1has__ffunc__equals.html", null ],
    [ "gaia::core::has_func_equals< T >", "structgaia_1_1core_1_1has__func__equals.html", null ],
    [ "gaia::cnt::ilist< TListItem, TItemHandle, TInternalStorage >", "structgaia_1_1cnt_1_1ilist.html", null ],
    [ "gaia::cnt::ilist_handle_traits< TItemHandle, typename >", "structgaia_1_1cnt_1_1ilist__handle__traits.html", null ],
    [ "gaia::cnt::ilist_handle_traits< TItemHandle, std::void_t< decltype(std::declval< const TItemHandle & >().prio())> >", "structgaia_1_1cnt_1_1ilist__handle__traits_3_01TItemHandle_00_01std_1_1void__t_3_01decltype_07st2a0d0d6f9c6aac50cc62708895916597.html", null ],
    [ "gaia::cnt::ilist_item", "structgaia_1_1cnt_1_1ilist__item.html", null ],
    [ "gaia::cnt::ilist_item_traits< TListItem >", "structgaia_1_1cnt_1_1ilist__item__traits.html", null ],
    [ "gaia::ecs::Inherit_", "structgaia_1_1ecs_1_1Inherit__.html", null ],
    [ "gaia::core::input_iterator_tag", "structgaia_1_1core_1_1input__iterator__tag.html", [
      [ "gaia::core::forward_iterator_tag", "structgaia_1_1core_1_1forward__iterator__tag.html", [
        [ "gaia::core::bidirectional_iterator_tag", "structgaia_1_1core_1_1bidirectional__iterator__tag.html", [
          [ "gaia::core::random_access_iterator_tag", "structgaia_1_1core_1_1random__access__iterator__tag.html", [
            [ "gaia::core::contiguous_iterator_tag", "structgaia_1_1core_1_1contiguous__iterator__tag.html", null ]
          ] ]
        ] ]
      ] ],
      [ "gaia::core::reverse_iterator_tag", "structgaia_1_1core_1_1reverse__iterator__tag.html", null ]
    ] ],
    [ "gaia::ecs::Component::InternalData", "structgaia_1_1ecs_1_1Component_1_1InternalData.html", null ],
    [ "gaia::ecs::Entity::InternalData", "structgaia_1_1ecs_1_1Entity_1_1InternalData.html", null ],
    [ "gaia::ecs::Is_", "structgaia_1_1ecs_1_1Is__.html", null ],
    [ "gaia::core::is_greater< T >", "structgaia_1_1core_1_1is__greater.html", null ],
    [ "gaia::ecs::is_pair< T >", "structgaia_1_1ecs_1_1is__pair.html", null ],
    [ "gaia::core::is_smaller< T >", "structgaia_1_1core_1_1is__smaller.html", null ],
    [ "gaia::core::is_smaller_or_equal< T >", "structgaia_1_1core_1_1is__smaller__or__equal.html", null ],
    [ "gaia::ser::is_trivially_serializable< T >", "structgaia_1_1ser_1_1is__trivially__serializable.html", null ],
    [ "gaia::cnt::ilist_item::ItemData", "structgaia_1_1cnt_1_1ilist__item_1_1ItemData.html", null ],
    [ "gaia::ecs::detail::QueryImpl::IterModeAcceptAll", "structgaia_1_1ecs_1_1detail_1_1QueryImpl_1_1IterModeAcceptAll.html", null ],
    [ "gaia::ecs::detail::QueryImpl::IterModeDisabledOnly", "structgaia_1_1ecs_1_1detail_1_1QueryImpl_1_1IterModeDisabledOnly.html", null ],
    [ "gaia::ecs::detail::QueryImpl::IterModeEnabled", "structgaia_1_1ecs_1_1detail_1_1QueryImpl_1_1IterModeEnabled.html", null ],
    [ "gaia::mt::Job", "structgaia_1_1mt_1_1Job.html", null ],
    [ "gaia::mt::JobAllocCtx", "structgaia_1_1mt_1_1JobAllocCtx.html", null ],
    [ "gaia::mt::JobArgs", "structgaia_1_1mt_1_1JobArgs.html", null ],
    [ "gaia::mt::JobArgsFunc", "classgaia_1_1mt_1_1JobArgsFunc.html", null ],
    [ "gaia::mt::JobHandle", "structgaia_1_1mt_1_1JobHandle.html", null ],
    [ "gaia::mt::JobNull_t", "structgaia_1_1mt_1_1JobNull__t.html", null ],
    [ "gaia::mt::JobParallel", "structgaia_1_1mt_1_1JobParallel.html", null ],
    [ "gaia::mt::JobParallelRef", "structgaia_1_1mt_1_1JobParallelRef.html", null ],
    [ "gaia::ser::JsonDiagnostic", "structgaia_1_1ser_1_1JsonDiagnostic.html", null ],
    [ "gaia::ser::JsonDiagnostics", "structgaia_1_1ser_1_1JsonDiagnostics.html", null ],
    [ "gaia::core::lock_scope< T >", "structgaia_1_1core_1_1lock__scope.html", null ],
    [ "gaia::ecs::QueryCtx::Data::LookupIdentity", "structgaia_1_1ecs_1_1QueryCtx_1_1Data_1_1LookupIdentity.html", null ],
    [ "gaia::ecs::vm::MatchingCtx", "structgaia_1_1ecs_1_1vm_1_1MatchingCtx.html", null ],
    [ "gaia::mem::MemoryPageContainer< T, RequestedBlockSize >", "structgaia_1_1mem_1_1MemoryPageContainer.html", null ],
    [ "gaia::mem::MemoryPageHeader", "structgaia_1_1mem_1_1MemoryPageHeader.html", [
      [ "gaia::mem::MemoryPage< T, RequestedBlockSize >", "structgaia_1_1mem_1_1MemoryPage.html", null ]
    ] ],
    [ "gaia::mem::MemoryPageStats", "structgaia_1_1mem_1_1MemoryPageStats.html", null ],
    [ "gaia::util::MoveFunc< Signature >", "classgaia_1_1util_1_1MoveFunc.html", null ],
    [ "gaia::util::MoveFunc< R(Args...)>", "classgaia_1_1util_1_1MoveFunc_3_01R_07Args_8_8_8_08_4.html", null ],
    [ "gaia::ecs::detail::NonFragmentingRelationStore", "structgaia_1_1ecs_1_1detail_1_1NonFragmentingRelationStore.html", null ],
    [ "gaia::ecs::QueryInfo::QueryState::NonTrivialPayload", "structgaia_1_1ecs_1_1QueryInfo_1_1QueryState_1_1NonTrivialPayload.html", null ],
    [ "gaia::ecs::Observer_", "structgaia_1_1ecs_1_1Observer__.html", null ],
    [ "gaia::ecs::OnDelete_", "structgaia_1_1ecs_1_1OnDelete__.html", null ],
    [ "gaia::ecs::OnDeleteTarget_", "structgaia_1_1ecs_1_1OnDeleteTarget__.html", null ],
    [ "gaia::ecs::OnInstantiate_", "structgaia_1_1ecs_1_1OnInstantiate__.html", null ],
    [ "gaia::ecs::detail::QueryImpl::OrderByTravView", "classgaia_1_1ecs_1_1detail_1_1QueryImpl_1_1OrderByTravView.html", null ],
    [ "gaia::core::output_iterator_tag", "structgaia_1_1core_1_1output__iterator__tag.html", null ],
    [ "gaia::ecs::Override_", "structgaia_1_1ecs_1_1Override__.html", null ],
    [ "gaia::cnt::page_iterator< T, Allocator, IsFwd >", "structgaia_1_1cnt_1_1page__iterator.html", null ],
    [ "gaia::cnt::page_iterator_soa< T, Allocator, IsFwd >", "structgaia_1_1cnt_1_1page__iterator__soa.html", null ],
    [ "gaia::cnt::page_storage< T >", "classgaia_1_1cnt_1_1page__storage.html", null ],
    [ "gaia::cnt::paged_ilist< TListItem, TItemHandle, MaxPages >", "structgaia_1_1cnt_1_1paged__ilist.html", null ],
    [ "gaia::cnt::paged_ilist_iterator< TPagedIList, IsConst >", "classgaia_1_1cnt_1_1paged__ilist__iterator.html", null ],
    [ "detail::pair_base", null, [
      [ "gaia::ecs::pair< Rel, Tgt >", "classgaia_1_1ecs_1_1pair.html", null ],
      [ "gaia::ecs::pair< Entity, Entity >", "classgaia_1_1ecs_1_1pair_3_01Entity_00_01Entity_01_4.html", null ]
    ] ],
    [ "gaia::ecs::Archetype::PairIndexData::PairCountBucket", "structgaia_1_1ecs_1_1Archetype_1_1PairIndexData_1_1PairCountBucket.html", null ],
    [ "gaia::ecs::Parent_", "structgaia_1_1ecs_1_1Parent__.html", null ],
    [ "gaia::ecs::detail::PendingSystemJob", "structgaia_1_1ecs_1_1detail_1_1PendingSystemJob.html", null ],
    [ "gaia::ecs::Prefab_", "structgaia_1_1ecs_1_1Prefab__.html", null ],
    [ "gaia::ecs::detail::PrefabChildEdge", "structgaia_1_1ecs_1_1detail_1_1PrefabChildEdge.html", null ],
    [ "gaia::ecs::detail::PrefabInstantiatePlanNode", "structgaia_1_1ecs_1_1detail_1_1PrefabInstantiatePlanNode.html", null ],
    [ "gaia::ecs::Archetype::Properties", "structgaia_1_1ecs_1_1Archetype_1_1Properties.html", null ],
    [ "gaia::ecs::query_sort_cond", "structgaia_1_1ecs_1_1query__sort__cond.html", null ],
    [ "gaia::ecs::QueryAccessSet", "structgaia_1_1ecs_1_1QueryAccessSet.html", null ],
    [ "gaia::ecs::QueryArchetypeCacheCursor", "structgaia_1_1ecs_1_1QueryArchetypeCacheCursor.html", null ],
    [ "gaia::ecs::detail::QueryImpl::QueryCacheRange", "structgaia_1_1ecs_1_1detail_1_1QueryImpl_1_1QueryCacheRange.html", null ],
    [ "gaia::ecs::QueryCtx", "structgaia_1_1ecs_1_1QueryCtx.html", null ],
    [ "gaia::ecs::QueryHandle", "structgaia_1_1ecs_1_1QueryHandle.html", null ],
    [ "gaia::ecs::QueryHandleLookupKey", "structgaia_1_1ecs_1_1QueryHandleLookupKey.html", null ],
    [ "gaia::ecs::QueryIdentity", "structgaia_1_1ecs_1_1QueryIdentity.html", null ],
    [ "gaia::ecs::detail::QueryImpl", "classgaia_1_1ecs_1_1detail_1_1QueryImpl.html", null ],
    [ "gaia::ecs::QueryInfo", "classgaia_1_1ecs_1_1QueryInfo.html", null ],
    [ "gaia::ecs::QueryInfoCreationCtx", "structgaia_1_1ecs_1_1QueryInfoCreationCtx.html", null ],
    [ "gaia::ecs::QueryInput", "structgaia_1_1ecs_1_1QueryInput.html", null ],
    [ "gaia::ecs::QueryMatchScratch", "structgaia_1_1ecs_1_1QueryMatchScratch.html", null ],
    [ "gaia::ecs::detail::QueryImpl::QueryPlan", "structgaia_1_1ecs_1_1detail_1_1QueryImpl_1_1QueryPlan.html", null ],
    [ "gaia::ecs::QueryTerm", "structgaia_1_1ecs_1_1QueryTerm.html", null ],
    [ "gaia::ecs::QueryTermOptions", "structgaia_1_1ecs_1_1QueryTermOptions.html", null ],
    [ "gaia::ecs::RawSparseStoreOps", "structgaia_1_1ecs_1_1RawSparseStoreOps.html", null ],
    [ "gaia::ecs::QueryInfo::QueryState::DynamicCacheState::RelationPayload", "structgaia_1_1ecs_1_1QueryInfo_1_1QueryState_1_1DynamicCacheState_1_1RelationPayload.html", null ],
    [ "gaia::ecs::Remove_", "structgaia_1_1ecs_1_1Remove__.html", null ],
    [ "gaia::ecs::Requires_", "structgaia_1_1ecs_1_1Requires__.html", null ],
    [ "gaia::ecs::RuntimeConstant", "structgaia_1_1ecs_1_1RuntimeConstant.html", null ],
    [ "gaia::ecs::RuntimeConstantDesc", "structgaia_1_1ecs_1_1RuntimeConstantDesc.html", null ],
    [ "gaia::ecs::RuntimeField", "structgaia_1_1ecs_1_1RuntimeField.html", null ],
    [ "gaia::ecs::RuntimeFieldDesc", "structgaia_1_1ecs_1_1RuntimeFieldDesc.html", null ],
    [ "gaia::ser::RuntimeJsonPolicy", "structgaia_1_1ser_1_1RuntimeJsonPolicy.html", null ],
    [ "gaia::ecs::RuntimeOpaqueAdapter", "structgaia_1_1ecs_1_1RuntimeOpaqueAdapter.html", null ],
    [ "gaia::ecs::RuntimeOpaqueScope", "structgaia_1_1ecs_1_1RuntimeOpaqueScope.html", null ],
    [ "gaia::ecs::RuntimeOpaqueValue", "structgaia_1_1ecs_1_1RuntimeOpaqueValue.html", null ],
    [ "gaia::ecs::RuntimeSequenceAdapter", "structgaia_1_1ecs_1_1RuntimeSequenceAdapter.html", null ],
    [ "gaia::ecs::RuntimeSequenceElement", "structgaia_1_1ecs_1_1RuntimeSequenceElement.html", null ],
    [ "gaia::ecs::RuntimeSequenceScope", "structgaia_1_1ecs_1_1RuntimeSequenceScope.html", null ],
    [ "gaia::cnt::sarr< T, N >", "classgaia_1_1cnt_1_1sarr.html", null ],
    [ "gaia::cnt::sarr< Entity, MAX_ITEMS_IN_QUERY >", "classgaia_1_1cnt_1_1sarr.html", null ],
    [ "gaia::cnt::sarr< gaia::ecs::Entity, MAX_ITEMS_IN_QUERY >", "classgaia_1_1cnt_1_1sarr.html", null ],
    [ "gaia::cnt::sarr< gaia::ecs::Entity, MaxVarCnt >", "classgaia_1_1cnt_1_1sarr.html", null ],
    [ "gaia::cnt::sarr< gaia::ecs::QueryTerm, MAX_ITEMS_IN_QUERY >", "classgaia_1_1cnt_1_1sarr.html", null ],
    [ "gaia::cnt::sarr< gaia::util::str, MaxVarCnt >", "classgaia_1_1cnt_1_1sarr.html", null ],
    [ "gaia::cnt::sarr< uint32_t, MAX_ITEMS_IN_QUERY >", "classgaia_1_1cnt_1_1sarr.html", null ],
    [ "gaia::cnt::sarr< uint8_t, BlockArrayBytes >", "classgaia_1_1cnt_1_1sarr.html", null ],
    [ "gaia::cnt::sarr< uint8_t, MAX_ITEMS_IN_QUERY >", "classgaia_1_1cnt_1_1sarr.html", null ],
    [ "gaia::cnt::sarr_ext< T, N >", "classgaia_1_1cnt_1_1sarr__ext.html", null ],
    [ "gaia::cnt::sarr_ext< gaia::mt::ThreadCtx, MaxWorkers >", "classgaia_1_1cnt_1_1sarr__ext.html", null ],
    [ "gaia::cnt::sarr_ext< GAIA_THREAD, MaxWorkers >", "classgaia_1_1cnt_1_1sarr__ext.html", null ],
    [ "gaia::cnt::sarr_ext_soa< T, N >", "classgaia_1_1cnt_1_1sarr__ext__soa.html", null ],
    [ "gaia::cnt::sarr_soa< T, N >", "classgaia_1_1cnt_1_1sarr__soa.html", null ],
    [ "gaia::ecs::Sched", "structgaia_1_1ecs_1_1Sched.html", null ],
    [ "gaia::ecs::SchedJob", "classgaia_1_1ecs_1_1SchedJob.html", null ],
    [ "gaia::ecs::SchedParDesc", "structgaia_1_1ecs_1_1SchedParDesc.html", null ],
    [ "gaia::ecs::SchedTaskDesc", "structgaia_1_1ecs_1_1SchedTaskDesc.html", null ],
    [ "gaia::ecs::SchedToken", "structgaia_1_1ecs_1_1SchedToken.html", null ],
    [ "gaia::mt::Semaphore", "classgaia_1_1mt_1_1Semaphore.html", null ],
    [ "gaia::mt::SemaphoreFast", "classgaia_1_1mt_1_1SemaphoreFast.html", null ],
    [ "detail::ser_buffer_binary_impl", null, [
      [ "gaia::ser::ser_buffer_binary", "classgaia_1_1ser_1_1ser__buffer__binary.html", null ],
      [ "gaia::ser::ser_buffer_binary_dyn", "classgaia_1_1ser_1_1ser__buffer__binary__dyn.html", null ]
    ] ],
    [ "gaia::ser::ser_json", "classgaia_1_1ser_1_1ser__json.html", null ],
    [ "gaia::ser::serializer", "structgaia_1_1ser_1_1serializer.html", null ],
    [ "gaia::ser::serializer_ctx", "structgaia_1_1ser_1_1serializer__ctx.html", null ],
    [ "gaia::util::signal< Function >", "classgaia_1_1util_1_1signal.html", null ],
    [ "gaia::util::signal< Ret(Args...)>", "classgaia_1_1util_1_1signal_3_01Ret_07Args_8_8_8_08_4.html", null ],
    [ "gaia::ecs::SingleArchetypeLookupItem", "structgaia_1_1ecs_1_1SingleArchetypeLookupItem.html", null ],
    [ "gaia::util::sink< Function >", "classgaia_1_1util_1_1sink.html", null ],
    [ "gaia::util::sink< Ret(Args...)>", "classgaia_1_1util_1_1sink_3_01Ret_07Args_8_8_8_08_4.html", null ],
    [ "gaia::mem::SmallBlockAllocatorPageStats", "structgaia_1_1mem_1_1SmallBlockAllocatorPageStats.html", null ],
    [ "gaia::mem::SmallBlockAllocatorStats", "structgaia_1_1mem_1_1SmallBlockAllocatorStats.html", null ],
    [ "gaia::util::SmallFunc", "classgaia_1_1util_1_1SmallFunc.html", null ],
    [ "gaia::core::span< T, Extent >", "classgaia_1_1core_1_1span.html", null ],
    [ "gaia::ecs::Sparse_", "structgaia_1_1ecs_1_1Sparse__.html", null ],
    [ "gaia::cnt::sparse_iterator< T, PageCapacity, Allocator, typename >", "structgaia_1_1cnt_1_1sparse__iterator.html", null ],
    [ "gaia::cnt::sparse_iterator< T, PageCapacity, Allocator, std::enable_if_t< std::is_empty_v< T > > >", "structgaia_1_1cnt_1_1sparse__iterator_3_01T_00_01PageCapacity_00_01Allocator_00_01std_1_1enable_a04ec75195309ee4c5d26ce99aa078a9.html", null ],
    [ "gaia::cnt::sparse_storage< T, PageCapacity, Allocator, typename >", "classgaia_1_1cnt_1_1sparse__storage.html", null ],
    [ "gaia::cnt::sparse_storage< T, PageCapacity, Allocator, std::enable_if_t< std::is_empty_v< T > > >", "classgaia_1_1cnt_1_1sparse__storage_3_01T_00_01PageCapacity_00_01Allocator_00_01std_1_1enable__ie087b7e8314b32ca924843d3e0f50e85.html", null ],
    [ "gaia::mt::SpinLock", "classgaia_1_1mt_1_1SpinLock.html", null ],
    [ "gaia::cnt::sringbuffer< T, N >", "classgaia_1_1cnt_1_1sringbuffer.html", null ],
    [ "gaia::cnt::sringbuffer_iterator< T, N >", "structgaia_1_1cnt_1_1sringbuffer__iterator.html", null ],
    [ "gaia::mem::StackAllocator< CapacityInBytes >", "classgaia_1_1mem_1_1StackAllocator.html", null ],
    [ "gaia::util::str", "structgaia_1_1util_1_1str.html", null ],
    [ "gaia::util::str_view", "structgaia_1_1util_1_1str__view.html", null ],
    [ "gaia::core::StringLookupKey< MaxLen >", "structgaia_1_1core_1_1StringLookupKey.html", null ],
    [ "gaia::core::StringLookupKey< 256 >", "structgaia_1_1core_1_1StringLookupKey.html", null ],
    [ "gaia::ecs::detail::SystemCollectCtx", "structgaia_1_1ecs_1_1detail_1_1SystemCollectCtx.html", null ],
    [ "gaia::ecs::detail::SystemPhaseScheduleItem", "structgaia_1_1ecs_1_1detail_1_1SystemPhaseScheduleItem.html", null ],
    [ "gaia::ecs::detail::SystemRunCtx", "structgaia_1_1ecs_1_1detail_1_1SystemRunCtx.html", null ],
    [ "gaia::ecs::detail::SystemScheduleEdge", "structgaia_1_1ecs_1_1detail_1_1SystemScheduleEdge.html", null ],
    [ "gaia::ecs::detail::SystemScheduleItem", "structgaia_1_1ecs_1_1detail_1_1SystemScheduleItem.html", null ],
    [ "gaia::ecs::detail::SystemScheduleScratch", "structgaia_1_1ecs_1_1detail_1_1SystemScheduleScratch.html", null ],
    [ "gaia::mt::ThreadCtx", "structgaia_1_1mt_1_1ThreadCtx.html", null ],
    [ "gaia::mt::ThreadPool", "classgaia_1_1mt_1_1ThreadPool.html", null ],
    [ "gaia::cnt::to_page_storage_id< T >", "structgaia_1_1cnt_1_1to__page__storage__id.html", null ],
    [ "gaia::cnt::to_sparse_id< T >", "structgaia_1_1cnt_1_1to__sparse__id.html", null ],
    [ "gaia::cnt::to_sparse_id< ecs::Entity >", "structgaia_1_1cnt_1_1to__sparse__id_3_01ecs_1_1Entity_01_4.html", null ],
    [ "gaia::ecs::Traversable_", "structgaia_1_1ecs_1_1Traversable__.html", null ],
    [ "gaia::ecs::QueryInfo::QueryState::DynamicCacheState::TraversedSourcePayload", "structgaia_1_1ecs_1_1QueryInfo_1_1QueryState_1_1DynamicCacheState_1_1TraversedSourcePayload.html", null ],
    [ "std::true_type", null, [
      [ "gaia::core::has_data_size< T, std::void_t< decltype(detail::data(std::declval< T >())), decltype(detail::size(std::declval< T >())) > >", "structgaia_1_1core_1_1has__data__size_3_01T_00_01std_1_1void__t_3_01decltype_07detail_1_1data_0731442a81cf4e1da91ee338fd93279e3c.html", null ],
      [ "gaia::core::has_size_begin_end< T, std::void_t< decltype(std::declval< T >().begin()), decltype(std::declval< T >().end()), decltype(detail::size(std::declval< T >())) > >", "structgaia_1_1core_1_1has__size__begin__end_3_01T_00_01std_1_1void__t_3_01decltype_07std_1_1decled3338d74af8cc0bacdf33bd2a865cfb.html", null ],
      [ "gaia::ser::detail::has_bytes_fn< T, std::void_t< decltype(std::declval< const T & >().bytes())> >", "structgaia_1_1ser_1_1detail_1_1has__bytes__fn_3_01T_00_01std_1_1void__t_3_01decltype_07std_1_1de17d36e20086ed372e222cd5cabdcf227.html", null ],
      [ "gaia::ser::detail::has_data_ptr< T, std::void_t< decltype(std::declval< const T & >().data())> >", "structgaia_1_1ser_1_1detail_1_1has__data__ptr_3_01T_00_01std_1_1void__t_3_01decltype_07std_1_1de5398e0f4947d84658557aa964b5cdec7.html", null ],
      [ "gaia::ser::detail::has_load_raw_ptr< T, std::void_t< decltype(std::declval< T & >().load_raw((void *) nullptr, uint32_t{}, ser::serialization_type_id{}))> >", "structgaia_1_1ser_1_1detail_1_1has__load__raw__ptr_3_01T_00_01std_1_1void__t_3_01decltype_07std_c7f992cfb0294954c1bac9f9d1fc1e64.html", null ],
      [ "gaia::ser::detail::has_reset_fn< T, std::void_t< decltype(std::declval< T & >().reset())> >", "structgaia_1_1ser_1_1detail_1_1has__reset__fn_3_01T_00_01std_1_1void__t_3_01decltype_07std_1_1dee4d6fcff1588f9093c259ebf893e533d.html", null ],
      [ "gaia::ser::detail::has_save_raw_ptr< T, std::void_t< decltype(std::declval< T & >().save_raw((const void *) nullptr, uint32_t{}, ser::serialization_type_id{}))> >", "structgaia_1_1ser_1_1detail_1_1has__save__raw__ptr_3_01T_00_01std_1_1void__t_3_01decltype_07std_c728a9c81f6de8c25093ad94bfbbbc30.html", null ],
      [ "gaia::ser::detail::has_seek_fn< T, std::void_t< decltype(std::declval< T & >().seek(uint32_t{}))> >", "structgaia_1_1ser_1_1detail_1_1has__seek__fn_3_01T_00_01std_1_1void__t_3_01decltype_07std_1_1decde0c993735b2058fbd9b080718d84786.html", null ],
      [ "gaia::ser::detail::has_tell_fn< T, std::void_t< decltype(std::declval< const T & >().tell())> >", "structgaia_1_1ser_1_1detail_1_1has__tell__fn_3_01T_00_01std_1_1void__t_3_01decltype_07std_1_1dec16493ebf98a8d23d7877f9f2a01cd59a.html", null ]
    ] ],
    [ "detail::type_identity", null, [
      [ "gaia::core::unique< T, Ts >", "structgaia_1_1core_1_1unique.html", null ]
    ] ],
    [ "gaia::meta::type_info", "structgaia_1_1meta_1_1type__info.html", null ],
    [ "gaia::core::type_list< Type >", "structgaia_1_1core_1_1type__list.html", null ],
    [ "gaia::core::type_list_concat< TypesA, TypesB >", "structgaia_1_1core_1_1type__list__concat.html", null ],
    [ "gaia::core::type_list_concat< type_list< TypesA... >, type_list< TypesB... > >", "structgaia_1_1core_1_1type__list__concat_3_01type__list_3_01TypesA_8_8_8_01_4_00_01type__list_3_01TypesB_8_8_8_01_4_01_4.html", null ],
    [ "gaia::mem::unaligned_ref< T >", "classgaia_1_1mem_1_1unaligned__ref.html", null ],
    [ "gaia::ecs::uni< T >", "structgaia_1_1ecs_1_1uni.html", null ],
    [ "gaia::ecs::QueryInfo::QueryState::DynamicCacheState::VariablePayload", "structgaia_1_1ecs_1_1QueryInfo_1_1QueryState_1_1DynamicCacheState_1_1VariablePayload.html", null ],
    [ "gaia::ecs::vm::VirtualMachine", "classgaia_1_1ecs_1_1vm_1_1VirtualMachine.html", null ],
    [ "gaia::ecs::World", "classgaia_1_1ecs_1_1World.html", null ],
    [ "gaia::core::zero_t", "structgaia_1_1core_1_1zero__t.html", null ]
];