var searchData=
[
  ['sarr_0',['sarr',['../classgaia_1_1cnt_1_1sarr.html',1,'gaia::cnt']]],
  ['sarr_3c_20entity_2c_20max_5fitems_5fin_5fquery_20_3e_1',['sarr&lt; Entity, MAX_ITEMS_IN_QUERY &gt;',['../classgaia_1_1cnt_1_1sarr.html',1,'gaia::cnt']]],
  ['sarr_3c_20gaia_3a_3aecs_3a_3aentity_2c_20max_5fitems_5fin_5fquery_20_3e_2',['sarr&lt; gaia::ecs::Entity, MAX_ITEMS_IN_QUERY &gt;',['../classgaia_1_1cnt_1_1sarr.html',1,'gaia::cnt']]],
  ['sarr_3c_20gaia_3a_3aecs_3a_3aentity_2c_20maxvarcnt_20_3e_3',['sarr&lt; gaia::ecs::Entity, MaxVarCnt &gt;',['../classgaia_1_1cnt_1_1sarr.html',1,'gaia::cnt']]],
  ['sarr_3c_20gaia_3a_3aecs_3a_3aqueryterm_2c_20max_5fitems_5fin_5fquery_20_3e_4',['sarr&lt; gaia::ecs::QueryTerm, MAX_ITEMS_IN_QUERY &gt;',['../classgaia_1_1cnt_1_1sarr.html',1,'gaia::cnt']]],
  ['sarr_3c_20gaia_3a_3autil_3a_3astr_2c_20maxvarcnt_20_3e_5',['sarr&lt; gaia::util::str, MaxVarCnt &gt;',['../classgaia_1_1cnt_1_1sarr.html',1,'gaia::cnt']]],
  ['sarr_3c_20uint32_5ft_2c_20max_5fitems_5fin_5fquery_20_3e_6',['sarr&lt; uint32_t, MAX_ITEMS_IN_QUERY &gt;',['../classgaia_1_1cnt_1_1sarr.html',1,'gaia::cnt']]],
  ['sarr_3c_20uint8_5ft_2c_20blockarraybytes_20_3e_7',['sarr&lt; uint8_t, BlockArrayBytes &gt;',['../classgaia_1_1cnt_1_1sarr.html',1,'gaia::cnt']]],
  ['sarr_3c_20uint8_5ft_2c_20max_5fitems_5fin_5fquery_20_3e_8',['sarr&lt; uint8_t, MAX_ITEMS_IN_QUERY &gt;',['../classgaia_1_1cnt_1_1sarr.html',1,'gaia::cnt']]],
  ['sarr_5fext_9',['sarr_ext',['../classgaia_1_1cnt_1_1sarr__ext.html',1,'gaia::cnt']]],
  ['sarr_5fext_3c_20gaia_3a_3aecs_3a_3aentity_2c_20max_5fitems_5fin_5fquery_20_3e_10',['sarr_ext&lt; gaia::ecs::Entity, MAX_ITEMS_IN_QUERY &gt;',['../classgaia_1_1cnt_1_1sarr__ext.html',1,'gaia::cnt']]],
  ['sarr_5fext_3c_20gaia_3a_3aecs_3a_3avm_3a_3adetail_3a_3aquerycompilectx_3a_3asourcetermop_2c_20max_5fitems_5fin_5fquery_20_3e_11',['sarr_ext&lt; gaia::ecs::vm::detail::QueryCompileCtx::SourceTermOp, MAX_ITEMS_IN_QUERY &gt;',['../classgaia_1_1cnt_1_1sarr__ext.html',1,'gaia::cnt']]],
  ['sarr_5fext_3c_20gaia_3a_3aecs_3a_3avm_3a_3adetail_3a_3aquerycompilectx_3a_3avarprogramstep_2c_20maxvarcnt_20_3e_12',['sarr_ext&lt; gaia::ecs::vm::detail::QueryCompileCtx::VarProgramStep, MaxVarCnt &gt;',['../classgaia_1_1cnt_1_1sarr__ext.html',1,'gaia::cnt']]],
  ['sarr_5fext_3c_20gaia_3a_3aecs_3a_3avm_3a_3adetail_3a_3aquerycompilectx_3a_3avartermop_2c_20max_5fitems_5fin_5fquery_20_3e_13',['sarr_ext&lt; gaia::ecs::vm::detail::QueryCompileCtx::VarTermOp, MAX_ITEMS_IN_QUERY &gt;',['../classgaia_1_1cnt_1_1sarr__ext.html',1,'gaia::cnt']]],
  ['sarr_5fext_3c_20gaia_3a_3amt_3a_3athreadctx_2c_20maxworkers_20_3e_14',['sarr_ext&lt; gaia::mt::ThreadCtx, MaxWorkers &gt;',['../classgaia_1_1cnt_1_1sarr__ext.html',1,'gaia::cnt']]],
  ['sarr_5fext_3c_20gaia_5fthread_2c_20maxworkers_20_3e_15',['sarr_ext&lt; GAIA_THREAD, MaxWorkers &gt;',['../classgaia_1_1cnt_1_1sarr__ext.html',1,'gaia::cnt']]],
  ['sarr_5fext_5fsoa_16',['sarr_ext_soa',['../classgaia_1_1cnt_1_1sarr__ext__soa.html',1,'gaia::cnt']]],
  ['sarr_5fext_5fsoa_5fiterator_17',['sarr_ext_soa_iterator',['../structgaia_1_1cnt_1_1sarr__ext__soa__iterator.html',1,'gaia::cnt']]],
  ['sarr_5fsoa_18',['sarr_soa',['../classgaia_1_1cnt_1_1sarr__soa.html',1,'gaia::cnt']]],
  ['sarr_5fsoa_5fiterator_19',['sarr_soa_iterator',['../structgaia_1_1cnt_1_1sarr__soa__iterator.html',1,'gaia::cnt']]],
  ['save_5ftag_20',['save_tag',['../structgaia_1_1ser_1_1save__tag.html',1,'gaia::ser']]],
  ['sched_21',['Sched',['../structgaia_1_1ecs_1_1Sched.html',1,'gaia::ecs']]],
  ['schedjob_22',['SchedJob',['../classgaia_1_1ecs_1_1SchedJob.html',1,'gaia::ecs']]],
  ['schedpardesc_23',['SchedParDesc',['../structgaia_1_1ecs_1_1SchedParDesc.html',1,'gaia::ecs']]],
  ['schedtaskdesc_24',['SchedTaskDesc',['../structgaia_1_1ecs_1_1SchedTaskDesc.html',1,'gaia::ecs']]],
  ['schedtoken_25',['SchedToken',['../structgaia_1_1ecs_1_1SchedToken.html',1,'gaia::ecs']]],
  ['schedtokendefdata_26',['SchedTokenDefData',['../structgaia_1_1ecs_1_1detail_1_1SchedTokenDefData.html',1,'gaia::ecs::detail']]],
  ['semaphore_27',['Semaphore',['../classgaia_1_1mt_1_1Semaphore.html',1,'gaia::mt']]],
  ['semaphorefast_28',['SemaphoreFast',['../classgaia_1_1mt_1_1SemaphoreFast.html',1,'gaia::mt']]],
  ['ser_5fbuffer_5fbinary_29',['ser_buffer_binary',['../classgaia_1_1ser_1_1ser__buffer__binary.html',1,'gaia::ser']]],
  ['ser_5fbuffer_5fbinary_5fdyn_30',['ser_buffer_binary_dyn',['../classgaia_1_1ser_1_1ser__buffer__binary__dyn.html',1,'gaia::ser']]],
  ['ser_5fbuffer_5fbinary_5fimpl_31',['ser_buffer_binary_impl',['../classgaia_1_1ser_1_1detail_1_1ser__buffer__binary__impl.html',1,'gaia::ser::detail']]],
  ['ser_5fbuffer_5fbinary_5fimpl_3c_20ser_5fbuffer_5fbinary_5fstorage_20_3e_32',['ser_buffer_binary_impl&lt; ser_buffer_binary_storage &gt;',['../classgaia_1_1ser_1_1detail_1_1ser__buffer__binary__impl.html',1,'gaia::ser::detail']]],
  ['ser_5fbuffer_5fbinary_5fimpl_3c_20ser_5fbuffer_5fbinary_5fstorage_5fdyn_20_3e_33',['ser_buffer_binary_impl&lt; ser_buffer_binary_storage_dyn &gt;',['../classgaia_1_1ser_1_1detail_1_1ser__buffer__binary__impl.html',1,'gaia::ser::detail']]],
  ['ser_5fjson_34',['ser_json',['../classgaia_1_1ser_1_1ser__json.html',1,'gaia::ser']]],
  ['serializer_35',['serializer',['../structgaia_1_1ser_1_1serializer.html',1,'gaia::ser']]],
  ['serializer_5fctx_36',['serializer_ctx',['../structgaia_1_1ser_1_1serializer__ctx.html',1,'gaia::ser']]],
  ['signal_37',['signal',['../classgaia_1_1util_1_1signal.html',1,'gaia::util']]],
  ['signal_3c_20ret_28args_2e_2e_2e_29_3e_38',['signal&lt; Ret(Args...)&gt;',['../classgaia_1_1util_1_1signal_3_01Ret_07Args_8_8_8_08_4.html',1,'gaia::util']]],
  ['singlearchetypelookupitem_39',['SingleArchetypeLookupItem',['../structgaia_1_1ecs_1_1SingleArchetypeLookupItem.html',1,'gaia::ecs']]],
  ['sink_40',['sink',['../classgaia_1_1util_1_1sink.html',1,'gaia::util']]],
  ['sink_3c_20ret_28args_2e_2e_2e_29_3e_41',['sink&lt; Ret(Args...)&gt;',['../classgaia_1_1util_1_1sink_3_01Ret_07Args_8_8_8_08_4.html',1,'gaia::util']]],
  ['size_5fcounter_42',['size_counter',['../classgaia_1_1ser_1_1detail_1_1size__counter.html',1,'gaia::ser::detail']]],
  ['smallblockallocatorimpl_43',['SmallBlockAllocatorImpl',['../classgaia_1_1mem_1_1detail_1_1SmallBlockAllocatorImpl.html',1,'gaia::mem::detail']]],
  ['smallblockallocatorpagestats_44',['SmallBlockAllocatorPageStats',['../structgaia_1_1mem_1_1SmallBlockAllocatorPageStats.html',1,'gaia::mem']]],
  ['smallblockallocatorstats_45',['SmallBlockAllocatorStats',['../structgaia_1_1mem_1_1SmallBlockAllocatorStats.html',1,'gaia::mem']]],
  ['smallblockheader_46',['SmallBlockHeader',['../structgaia_1_1mem_1_1detail_1_1SmallBlockHeader.html',1,'gaia::mem::detail']]],
  ['smallblockpage_47',['SmallBlockPage',['../structgaia_1_1mem_1_1detail_1_1SmallBlockPage.html',1,'gaia::mem::detail']]],
  ['smallblockpagecontainer_48',['SmallBlockPageContainer',['../structgaia_1_1mem_1_1detail_1_1SmallBlockPageContainer.html',1,'gaia::mem::detail']]],
  ['smallfunc_49',['SmallFunc',['../classgaia_1_1util_1_1SmallFunc.html',1,'gaia::util']]],
  ['soatermfieldreadproxy_50',['SoATermFieldReadProxy',['../structgaia_1_1ecs_1_1detail_1_1SoATermFieldReadProxy.html',1,'gaia::ecs::detail']]],
  ['soatermfieldreadproxyentity_51',['SoATermFieldReadProxyEntity',['../structgaia_1_1ecs_1_1detail_1_1SoATermFieldReadProxyEntity.html',1,'gaia::ecs::detail']]],
  ['soatermfieldreadproxypointer_52',['SoATermFieldReadProxyPointer',['../structgaia_1_1ecs_1_1detail_1_1SoATermFieldReadProxyPointer.html',1,'gaia::ecs::detail']]],
  ['soatermfieldwriteproxy_53',['SoATermFieldWriteProxy',['../structgaia_1_1ecs_1_1detail_1_1SoATermFieldWriteProxy.html',1,'gaia::ecs::detail']]],
  ['soatermfieldwriteproxyentity_54',['SoATermFieldWriteProxyEntity',['../structgaia_1_1ecs_1_1detail_1_1SoATermFieldWriteProxyEntity.html',1,'gaia::ecs::detail']]],
  ['soatermfieldwriteproxypointer_55',['SoATermFieldWriteProxyPointer',['../structgaia_1_1ecs_1_1detail_1_1SoATermFieldWriteProxyPointer.html',1,'gaia::ecs::detail']]],
  ['soatermrowwriteproxy_56',['SoATermRowWriteProxy',['../structgaia_1_1ecs_1_1detail_1_1SoATermRowWriteProxy.html',1,'gaia::ecs::detail']]],
  ['soatermrowwriteproxyentity_57',['SoATermRowWriteProxyEntity',['../structgaia_1_1ecs_1_1detail_1_1SoATermRowWriteProxyEntity.html',1,'gaia::ecs::detail']]],
  ['soatermrowwriteproxypointer_58',['SoATermRowWriteProxyPointer',['../structgaia_1_1ecs_1_1detail_1_1SoATermRowWriteProxyPointer.html',1,'gaia::ecs::detail']]],
  ['soatermviewget_59',['SoATermViewGet',['../structgaia_1_1ecs_1_1detail_1_1SoATermViewGet.html',1,'gaia::ecs::detail']]],
  ['soatermviewgetentity_60',['SoATermViewGetEntity',['../structgaia_1_1ecs_1_1detail_1_1SoATermViewGetEntity.html',1,'gaia::ecs::detail']]],
  ['soatermviewgetpointer_61',['SoATermViewGetPointer',['../structgaia_1_1ecs_1_1detail_1_1SoATermViewGetPointer.html',1,'gaia::ecs::detail']]],
  ['soatermviewset_62',['SoATermViewSet',['../structgaia_1_1ecs_1_1detail_1_1SoATermViewSet.html',1,'gaia::ecs::detail']]],
  ['soatermviewsetentity_63',['SoATermViewSetEntity',['../structgaia_1_1ecs_1_1detail_1_1SoATermViewSetEntity.html',1,'gaia::ecs::detail']]],
  ['soatermviewsetpointer_64',['SoATermViewSetPointer',['../structgaia_1_1ecs_1_1detail_1_1SoATermViewSetPointer.html',1,'gaia::ecs::detail']]],
  ['sourcelookupcursor_65',['SourceLookupCursor',['../structgaia_1_1ecs_1_1vm_1_1detail_1_1SourceLookupCursor.html',1,'gaia::ecs::vm::detail']]],
  ['sourcetermop_66',['SourceTermOp',['../structgaia_1_1ecs_1_1vm_1_1detail_1_1QueryCompileCtx_1_1SourceTermOp.html',1,'gaia::ecs::vm::detail::QueryCompileCtx']]],
  ['span_67',['span',['../classgaia_1_1core_1_1span.html',1,'gaia::core']]],
  ['span_3c_20const_20componentindexentry_20_3e_68',['span&lt; const ComponentIndexEntry &gt;',['../classgaia_1_1core_1_1span.html',1,'gaia::core']]],
  ['span_3c_20const_20entity_20_3e_69',['span&lt; const Entity &gt;',['../classgaia_1_1core_1_1span.html',1,'gaia::core']]],
  ['span_3c_20const_20gaia_3a_3aecs_3a_3aarchetype_20_2a_20_3e_70',['span&lt; const gaia::ecs::Archetype * &gt;',['../classgaia_1_1core_1_1span.html',1,'gaia::core']]],
  ['span_3c_20const_20gaia_3a_3aecs_3a_3aentity_20_3e_71',['span&lt; const gaia::ecs::Entity &gt;',['../classgaia_1_1core_1_1span.html',1,'gaia::core']]],
  ['span_3c_20const_20uint8_5ft_20_3e_72',['span&lt; const uint8_t &gt;',['../classgaia_1_1core_1_1span.html',1,'gaia::core']]],
  ['span_3c_20const_20void_20_2aconst_20_3e_73',['span&lt; const void *const &gt;',['../classgaia_1_1core_1_1span.html',1,'gaia::core']]],
  ['span_3c_20uint8_5ft_20_3e_74',['span&lt; uint8_t &gt;',['../classgaia_1_1core_1_1span.html',1,'gaia::core']]],
  ['span_5fstorage_75',['span_storage',['../structgaia_1_1core_1_1detail_1_1span__storage.html',1,'gaia::core::detail']]],
  ['span_5fstorage_3c_20const_20componentindexentry_2c_20extent_20_3e_76',['span_storage&lt; const ComponentIndexEntry, Extent &gt;',['../structgaia_1_1core_1_1detail_1_1span__storage.html',1,'gaia::core::detail']]],
  ['span_5fstorage_3c_20const_20entity_2c_20extent_20_3e_77',['span_storage&lt; const Entity, Extent &gt;',['../structgaia_1_1core_1_1detail_1_1span__storage.html',1,'gaia::core::detail']]],
  ['span_5fstorage_3c_20const_20gaia_3a_3aecs_3a_3aarchetype_20_2a_2c_20extent_20_3e_78',['span_storage&lt; const gaia::ecs::Archetype *, Extent &gt;',['../structgaia_1_1core_1_1detail_1_1span__storage.html',1,'gaia::core::detail']]],
  ['span_5fstorage_3c_20const_20gaia_3a_3aecs_3a_3aentity_2c_20extent_20_3e_79',['span_storage&lt; const gaia::ecs::Entity, Extent &gt;',['../structgaia_1_1core_1_1detail_1_1span__storage.html',1,'gaia::core::detail']]],
  ['span_5fstorage_3c_20const_20uint8_5ft_2c_20extent_20_3e_80',['span_storage&lt; const uint8_t, Extent &gt;',['../structgaia_1_1core_1_1detail_1_1span__storage.html',1,'gaia::core::detail']]],
  ['span_5fstorage_3c_20const_20void_20_2aconst_2c_20extent_20_3e_81',['span_storage&lt; const void *const, Extent &gt;',['../structgaia_1_1core_1_1detail_1_1span__storage.html',1,'gaia::core::detail']]],
  ['span_5fstorage_3c_20t_2c_20dynamicspanextent_20_3e_82',['span_storage&lt; T, DynamicSpanExtent &gt;',['../structgaia_1_1core_1_1detail_1_1span__storage_3_01T_00_01DynamicSpanExtent_01_4.html',1,'gaia::core::detail']]],
  ['span_5fstorage_3c_20uint8_5ft_2c_20extent_20_3e_83',['span_storage&lt; uint8_t, Extent &gt;',['../structgaia_1_1core_1_1detail_1_1span__storage.html',1,'gaia::core::detail']]],
  ['sparse_5f_84',['Sparse_',['../structgaia_1_1ecs_1_1Sparse__.html',1,'gaia::ecs']]],
  ['sparse_5fiterator_85',['sparse_iterator',['../structgaia_1_1cnt_1_1sparse__iterator.html',1,'gaia::cnt']]],
  ['sparse_5fiterator_3c_20t_2c_20pagecapacity_2c_20allocator_2c_20std_3a_3aenable_5fif_5ft_3c_20std_3a_3ais_5fempty_5fv_3c_20t_20_3e_20_3e_20_3e_86',['sparse_iterator&lt; T, PageCapacity, Allocator, std::enable_if_t&lt; std::is_empty_v&lt; T &gt; &gt; &gt;',['../structgaia_1_1cnt_1_1sparse__iterator_3_01T_00_01PageCapacity_00_01Allocator_00_01std_1_1enable_a04ec75195309ee4c5d26ce99aa078a9.html',1,'gaia::cnt']]],
  ['sparse_5fpage_87',['sparse_page',['../classgaia_1_1cnt_1_1detail_1_1sparse__page.html',1,'gaia::cnt::detail']]],
  ['sparse_5fpage_3c_20t_2c_20pagecapacity_2c_20allocator_2c_20std_3a_3aenable_5fif_5ft_3c_20std_3a_3ais_5fempty_5fv_3c_20t_20_3e_20_3e_20_3e_88',['sparse_page&lt; T, PageCapacity, Allocator, std::enable_if_t&lt; std::is_empty_v&lt; T &gt; &gt; &gt;',['../classgaia_1_1cnt_1_1detail_1_1sparse__page_3_01T_00_01PageCapacity_00_01Allocator_00_01std_1_1en6e95dfa070ac2a122b9692da81356b71.html',1,'gaia::cnt::detail']]],
  ['sparse_5fstorage_89',['sparse_storage',['../classgaia_1_1cnt_1_1sparse__storage.html',1,'gaia::cnt']]],
  ['sparse_5fstorage_3c_20gaia_3a_3aecs_3a_3aruntimesparsecomponentrecord_20_3e_90',['sparse_storage&lt; gaia::ecs::RuntimeSparseComponentRecord &gt;',['../classgaia_1_1cnt_1_1sparse__storage.html',1,'gaia::cnt']]],
  ['sparse_5fstorage_3c_20gaia_3a_3aecs_3a_3asparsecomponentrecord_3c_20t_20_3e_20_3e_91',['sparse_storage&lt; gaia::ecs::SparseComponentRecord&lt; T &gt; &gt;',['../classgaia_1_1cnt_1_1sparse__storage.html',1,'gaia::cnt']]],
  ['sparse_5fstorage_3c_20t_2c_20pagecapacity_2c_20allocator_2c_20std_3a_3aenable_5fif_5ft_3c_20std_3a_3ais_5fempty_5fv_3c_20t_20_3e_20_3e_20_3e_92',['sparse_storage&lt; T, PageCapacity, Allocator, std::enable_if_t&lt; std::is_empty_v&lt; T &gt; &gt; &gt;',['../classgaia_1_1cnt_1_1sparse__storage_3_01T_00_01PageCapacity_00_01Allocator_00_01std_1_1enable__ie087b7e8314b32ca924843d3e0f50e85.html',1,'gaia::cnt']]],
  ['sparsecomponentrecord_93',['SparseComponentRecord',['../structgaia_1_1ecs_1_1SparseComponentRecord.html',1,'gaia::ecs']]],
  ['sparsecomponentstore_94',['SparseComponentStore',['../structgaia_1_1ecs_1_1detail_1_1SparseComponentStore.html',1,'gaia::ecs::detail']]],
  ['sparsecomponentstoreerased_95',['SparseComponentStoreErased',['../structgaia_1_1ecs_1_1detail_1_1SparseComponentStoreErased.html',1,'gaia::ecs::detail']]],
  ['spinlock_96',['SpinLock',['../classgaia_1_1mt_1_1SpinLock.html',1,'gaia::mt']]],
  ['sringbuffer_97',['sringbuffer',['../classgaia_1_1cnt_1_1sringbuffer.html',1,'gaia::cnt']]],
  ['sringbuffer_5fiterator_98',['sringbuffer_iterator',['../structgaia_1_1cnt_1_1sringbuffer__iterator.html',1,'gaia::cnt']]],
  ['stackallocator_99',['StackAllocator',['../classgaia_1_1mem_1_1StackAllocator.html',1,'gaia::mem']]],
  ['str_100',['str',['../structgaia_1_1util_1_1str.html',1,'gaia::util']]],
  ['str_5fview_101',['str_view',['../structgaia_1_1util_1_1str__view.html',1,'gaia::util']]],
  ['stringlookupkey_102',['StringLookupKey',['../structgaia_1_1core_1_1StringLookupKey.html',1,'gaia::core']]],
  ['stringlookupkey_3c_20256_20_3e_103',['StringLookupKey&lt; 256 &gt;',['../structgaia_1_1core_1_1StringLookupKey.html',1,'gaia::core']]],
  ['stringlookupkey_3c_20512_20_3e_104',['StringLookupKey&lt; 512 &gt;',['../structgaia_1_1core_1_1StringLookupKey.html',1,'gaia::core']]],
  ['systemcollectctx_105',['SystemCollectCtx',['../structgaia_1_1ecs_1_1detail_1_1SystemCollectCtx.html',1,'gaia::ecs::detail']]],
  ['systemphasescheduleitem_106',['SystemPhaseScheduleItem',['../structgaia_1_1ecs_1_1detail_1_1SystemPhaseScheduleItem.html',1,'gaia::ecs::detail']]],
  ['systemrunctx_107',['SystemRunCtx',['../structgaia_1_1ecs_1_1detail_1_1SystemRunCtx.html',1,'gaia::ecs::detail']]],
  ['systemscheduleedge_108',['SystemScheduleEdge',['../structgaia_1_1ecs_1_1detail_1_1SystemScheduleEdge.html',1,'gaia::ecs::detail']]],
  ['systemscheduleitem_109',['SystemScheduleItem',['../structgaia_1_1ecs_1_1detail_1_1SystemScheduleItem.html',1,'gaia::ecs::detail']]],
  ['systemschedulescratch_110',['SystemScheduleScratch',['../structgaia_1_1ecs_1_1detail_1_1SystemScheduleScratch.html',1,'gaia::ecs::detail']]]
];
